### ISSUE TITLE
Rqlite client for .NET

### ISSUE THREAD

**Issue by arthrp** [rqlite/rqlite#1000]
I've made a simple Rqlite client library for .NET - https://github.com/arthrp/RqliteDotnet. Planning to publish package on Nuget (.NET package manager). I think it could be referenced somewhere in the docs for people who look for .NET client lib. What would be the best place to put that reference?

**Comment by otoolep** [comment]
Thanks for your contribution. I do not have any .NET client.

I just created https://github.com/rqlite/rqlite-dotnet. If I gave you commit rights to that repo, would you be interested in adding the code there? And perhaps extending it?

**Comment by arthrp** [comment]
@otoolep sounds good, I can add my code there. I'm planning to work on that client, yes.

**Comment by otoolep** [comment]
Done, sent you an invite. Looking forward to your work.
