### ISSUE TITLE
Idea: libsqlite3.so wrapper library

### ISSUE THREAD

**Issue by orent** [rqlite/rqlite#1003]
Idea: a library exposing the same api as libsqlite3.so that can be loaded with LD_PRELOAD and turn any sqlite3 client into a rqlite client, possibly including the standard sqlite3 cli executable. When opening a regular sqlite file it will act as transparent wrapper.

The connection parameters can be passed as a url or a small textfile that acts as a placeholder.

I think this might require changes to the connection protocol to support the exact same API. Perhaps a binary protocol closely modeled on the API structures.

**Comment by otoolep** [comment]
Thanks for your suggestion, however this not the direction rqlite will move in.  You probably want to look at https://github.com/canonical/dqlite
