### ISSUE TITLE
Update SQLite dependency to 3.38 as soon as it's available

### ISSUE THREAD

**Issue by dihedron** [rqlite/rqlite#1005]
**Is your feature request related to a problem? Please describe.**
Not a problem, an enhancement: SQLite 3.38 is out with support for **-> and ->> operators** in JSON queries and JSON on by default.

**Describe the solution you'd like**
A [pull request](https://github.com/mattn/go-sqlite3/pull/1019#issue-1147566436) is pending merge on mattn/go-sqlite; I would love to see the dependency bumped and a shiny new release of rqlite ASAP!

**Describe alternatives you've considered**
None.

**Additional context**
[SQLite release notes](https://sqlite.org/releaselog/3_38_0.html); also see the updated documentation on operators [here](https://www.sqlite.org/json1.html#jptr).

**Comment by otoolep** [comment]
Merged it into HEAD of rqlite. Need to make one final change, and then I will release a new version of rqlite.

**Comment by dihedron** [comment]
Super cool!
