### ISSUE TITLE
rqlite gui 

### ISSUE THREAD

**Issue by micpeng365** [rqlite/rqlite#1006]
Can you provide a GUI to operate, like Navicat....

**Comment by adminy** [comment]
Did you try pointing to a remote link sqlite in navicat? instead of selecting a file, you can select a network location in some UI databases, I wonder if its as simple as that.

**Comment by rathboma** [comment]
Hey! I'm the owner and maintainer of [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio). This project looks amazing. I'm going to add RQLite to my app soon 👍

**Comment by rathboma** [comment]
Honestly in an ideal world I'd use RQLite to provide remote access to ANY SQLite file by starting it using SSH, but I'm not confident enough to do that yet, so I'll probably just add RQLite as a dropdown option

**Comment by otoolep** [comment]
There are now two UI applications which support rqlite: https://rqlite.io/docs/ui/

So I consider this addresses.

**Comment by Suleman-Elahi** [comment]
Here's my attempt at creating a webui for it: https://github.com/Suleman-Elahi/rqLui

I was using it for my internal use so I recreated it polished it a bit and pushed it there.

~ps it's vibe coded.
