### ISSUE TITLE
restart data loss

### ISSUE THREAD

**Issue by tiswo** [rqlite/rqlite#1010]
hi, I have a problem. I use the `on-disk` mode and use the `-on-disk-startup ` parameter to start rqlite. When I kill the process and restart, if the startup process fails, the `db.sqlite`  file size becomes 0，the previous table records will be lost.

**Comment by otoolep** [comment]
I need a lot more information than this. You haven't event told me what version you are running. I need you to show:

- starting a node, showing me the command line you use
- show me the logs for the node
- inserting records, either via the CLI or via `curl`.
- how you restart the node
- show me the logs
- show me you connecting to the node again
- show me via the CLI or via `curl` that the records are gone.

**Comment by otoolep** [comment]
Also, what do you mean "the startup process fails". That could mean a lot of things. If a node doesn't start properly then the database may not be rebuilt from the Raft log.....because it hasn't started properly. We need to fix why it isn't starting properly.

**Comment by tiswong** [comment]
![4076392061482572262](https://user-images.githubusercontent.com/17022644/156961301-14f7878a-5a2c-40bf-a971-209583370fcc.jpg)
This is how I reproduce it. First start it with `root`, then kill the process, and then start it with other users. At this time, The `db.sqlite` file becomes empty, even if you restart with root.

**Comment by tiswong** [comment]
> 

However, even if raft is restarted, the data will not be restored to sqlite again.

**Comment by otoolep** [comment]
Thanks.

Screenshots are not a great way to get the log to me, I also don't have access to the full log, as the screenshot is cut off at the end. You also seem to be running a modified version of rqlite, since I do not recognize the command-line option `-start-raft`. What have you changed in the software?

**Comment by tiswong** [comment]
I start rqlite through another program, and the `-start-raft` parameter is determines whether to start rqlite. The version of rqlite i use is 6.3.0.

**Comment by otoolep** [comment]
I just tested 7.3.2 -- ran a single node in the same way you seem to run it, inserted some records, killed the node. When the node came back, data is there and the SQLite file is non-zero. I started it like this:

```rqlited -on-disk-startup -on-disk data```

I'm going to need much more detailed directions on how to reproduce your failure, as I cannot reproduce any problems.

**Comment by otoolep** [comment]
The screenshot does state that the there is no database data available at startup, so that explains why the database file is not recreated. Does it happen with all restarts? Or just with some restarts?

As for more data, when a node gets into the problem state I need:

- Full logs from the node from the moment it started to when it failed to recreate the on-disk database. I need those logs as text, not as a screenshot.
- The output of:
```bash
curl localhost:4001/status?pretty
curl localhost:4001/nodes?pretty
curl localhost:4001/readyz
curl localhost:4001/debug/vars```
but replace `localhost` with the actual address of the node.

**Comment by otoolep** [comment]
I would also need to see the logs from the node before you kill it. I am particularly interested in seeing logs about the Raft snapshotting system such as:
```
2022-03-09T08:35:34.614-0500 [INFO]  raft: starting snapshot up to: index=17
2022-03-09T08:35:34.615-0500 [INFO]  snapshot: creating new snapshot: path=data/snapshots/2-17-1646832934615.tmp
[store] 2022/03/09 08:35:34 snapshot and persist took 42.844582ms
2022-03-09T08:35:34.657-0500 [INFO]  raft: compacting logs: from=1 to=5
2022-03-09T08:35:34.667-0500 [INFO]  raft: snapshot complete up to: index=17
```
as something may be going wrong when the node is snapshotting prior to it being killed.

**Comment by otoolep** [comment]
So perhaps you can keep the logs for every node, and then if it happens, send me the logs from the failed node before it went down, and the logs from when it comes back up. That would be most helpful.

**Comment by tiswong** [comment]
I suspect that the snapshot cannot be loaded due to the permission problem. I'll delete all files and retest later

**Comment by otoolep** [comment]
No further updates, assuming fixed.
