### ISSUE TITLE
How to build rqlite based on a tag.

### ISSUE THREAD

**Issue by fengzhenqiong** [rqlite/rqlite#1014]
seems currently the appveyor only builds the latest codes.

https://ci.appveyor.com/api/projects/otoolep/rqlite/artifacts/rqlite-latest-win64.zip?branch=master

but this may not be stable so maybe someone wants to build a windows version in appveyor based on a tag (say, v7.2.0)

Is this possible? I tried to change the branch=master to branch=v7.2.0 or tag=v7.2.0 but that does not work.

sorry that I'm not very familiar with AppVeyor. Thanks a lot.

**Comment by otoolep** [comment]
Unfortunately I'm not that familiar with it either -- my main goal for appveyor is to ensure rqlite can be built for, and runs on, Windows. My assumption is that others will be able to then follow the build directions for Windows, for their own purposes.

https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite

**Comment by otoolep** [comment]
You could try asking on the Slack channel or Google group
