### ISSUE TITLE
When the TCP port times out, the previous packet is returned

### ISSUE THREAD

**Issue by zhangyongding** [rqlite/rqlite#1029]
**What version are you running?**
6.6.2
**What did you do?**
Run in cluster mode
**What did you expect to happen?**

**What happened instead?**
the previous packet is returned
**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**

https://github.com/rqlite/rqlite/blob/master/cluster/client.go

error code:
```
_, err = io.ReadFull(conn, b)
if err != nil {
	return "", err
}
```

correct code:
```
_, err = io.ReadFull(conn, b)
if err != nil {
        handleConnError(conn)
	return "", err
}
```

**Comment by otoolep** [comment]
Thanks, yeah, seems like it should be fixed. Will be fixed in 7.5.0.

**Comment by zhangyongding** [comment]
GetNodeAPIAddr and Query function must also be fixed

**Comment by otoolep** [comment]
Got it, thanks, fixing.
