### ISSUE TITLE
Trivially easy to deploy, with no need to separately install SQLite?

### ISSUE THREAD

**Issue by hiqsociety** [rqlite/rqlite#1040]
with no need to separately install SQLite? really? needing it for on disk storage. is the db format compatible with sqlite?

how many files are created per database / table?

**Comment by otoolep** [comment]
A single SQLite file is created on each node, if you run in on-disk mode.  If you wish rqlite to use an actual file-based SQLite database, pass `-on-disk` to rqlite on start-up.
