### ISSUE TITLE
if i want to access a key from a db, does it read the whole file into mem or just that particular key section? just wondering if i need to have lots of mem available for this. 100GB per db size advisable etc?

### ISSUE THREAD

**Issue by hiqsociety** [rqlite/rqlite#1041]
if i want to access a key from a db, does it read the whole file into mem or just that particular key section? just wondering if i need to have lots of mem available for this. 100GB per db size advisable etc?

**Comment by otoolep** [comment]
rqlite is built directly on SQLite. Whatever a read of a row from SQLite normally requires in term of memory is what rqlite will require. If you have SQLite-specific questions, posting on the SQLite forum should get you your answers.

https://sqlite.org/forum/forummain

**Comment by otoolep** [comment]
Note that by default rqlite stores the entire SQLite database in RAM and does not store any SQLite information on disk. So the whole database is in RAM anyway.
