### ISSUE TITLE
The timeout between nodes is too large

### ISSUE THREAD

**Issue by zhangyongding** [rqlite/rqlite#1042]
**Is your feature request related to a problem? Please describe.**
In cluster mode, it takes 30 seconds to establish a connection between nodes. When nodes are shut down, the waiting time is too long. You are advised to set the timeout period to 1 second 

**Describe the solution you'd like**
cluster.NewClient set timeout = 1s

**Describe alternatives you've considered**

**Additional context**

**Comment by otoolep** [comment]
Yeah, maybe too long. Instead of changing existing behaviour, which would technically be a breaking change, I'll allow it to be configurable.
