### ISSUE TITLE
insert large data via http API

### ISSUE THREAD

**Issue by agusibrahim** [rqlite/rqlite#1044]
**What version are you running?**
7

**What did you do?**
import large json file (1m data) using curl
`curl -XPOST 'localhost:4001/db/execute?pretty&transaction' -H "Content-Type: application/json" -d @largedata.json`
respon OK with insertid and affectedrow result.

**What did you expect to happen?**
data inserted and i able to query data via cli or api

**What happened instead?**
i don't see any data when i query with `SELECT` via cli.
i cut the data, only 20 data in json file. import it and it's working, i see the data

there is alternative way insert large data from json(sql insert) or csv with more efficient than restore from sqlite3 db??

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
seem working normal

**Comment by otoolep** [comment]
Thanks for your report. This is not enough information to help you however. Can you supply the JSON file? Without seeing what data you are inserting, it's not possible to debug this.

Also, pass `-v` to `curl` so I can see the entire response from rqlite.

**Comment by agusibrahim** [comment]
sorry data is to large (220mb) to upload here, i generate from csv file. this is capture head of data (array of sql insert right?)
![Screenshot_20220615-060330_MiXplorer~2](https://user-images.githubusercontent.com/5948377/173703501-5cb8c4dd-b51d-4bb3-a619-9339ac76c07a.png)

this is result from curl (19.6mb)
![Screenshot_20220615-060353_MiXplorer~2](https://user-images.githubusercontent.com/5948377/173703521-d718bd50-f565-4105-97d9-0d3d4e99a22e.png)

**Comment by otoolep** [comment]
This is still going to be difficult to reproduce without your source data -- and the screenshots you have showed me don't show any actual issues. Can't you compress the file, and put it in an AWS S3 bucket, or something similar?

In any event, a 220MB HTTP request is very large and not a good use of the `/db/execute` API. Is this a once-off load? If so, why not generate a SQLite file with the data you wish to upload, then use the Restore API? You already have the INSERT statements. Loading directly from the generated SQLite file will take seconds. 

https://github.com/rqlite/rqlite/blob/master/DOC/RESTORE_FROM_SQLITE.md#http

```bash
curl -v -XPOST localhost:4001/db/load -H "Content-type: application/octet-stream" --data-binary @largedata.sqlite
```

**Comment by agusibrahim** [comment]
here is my data [largedata.zip](https://github.com/agusibrahim/apiassets/releases/download/largedatatest/largedata.zip)

yes i've been try restore using sqlite file, it cool. but its take more time when making sqlite file. will be look simple if we could restore from a csv or sql file

**Comment by otoolep** [comment]
>here is my data [largedata.zip](https://github.com/agusibrahim/apiassets/releases/download/largedatatest/largedata.zip)

Thanks, I will try it out.

**Comment by otoolep** [comment]
@agusibrahim -- your zip file is `Not Found`.
```bash
$ curl -v https://github.com/agusibrahim/apiassets/releases/download/largedatatest/largedata.zip
*   Trying 140.82.113.3:443...
* TCP_NODELAY set
* Connected to github.com (140.82.113.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: Mar 15 00:00:00 2022 GMT
*  expire date: Mar 15 23:59:59 2023 GMT
*  subjectAltName: host "github.com" matched cert's "github.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55862c2332f0)
> GET /agusibrahim/apiassets/releases/download/largedatatest/largedata.zip HTTP/2
> Host: github.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 404 
< server: GitHub.com
< date: Thu, 16 Jun 2022 00:11:20 GMT
< content-type: text/plain; charset=utf-8
< vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
< permissions-policy: interest-cohort=()
< cache-control: no-cache
< strict-transport-security: max-age=31536000; includeSubdomains; preload
< x-frame-options: deny
< x-content-type-options: nosniff
< x-xss-protection: 0
< referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
< expect-ct: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
< content-security-policy: default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'
< content-length: 9
< x-github-request-id: ECF6:60C4:14E8B3:2A4776:62AA7528
< 
* Connection #0 to host github.com left intact
```

**Comment by agusibrahim** [comment]
download with
`curl -L "https://github.com/agusibrahim/apiassets/releases/download/largedatatest/largedata.zip" --output largedata.zip`

**Comment by otoolep** [comment]
Do you issue any other SQL commands to rqlite before attempting to load the 220MB of JSON?

**Comment by otoolep** [comment]
Because you realise there are no `CREATE TABLE` statements in the file, right? Every single one of those `INSERT`s will fail unless a table has been created.

**Comment by otoolep** [comment]
I need the `CREATE TABLE` command you issue before trying to load this file.

**Comment by agusibrahim** [comment]
of course
`CREATE TABLE 'data' ('nopol' TEXT UNIQUE, 'mobil' TEXT, 'lesing' TEXT, 'overdue' TEXT, 'saldo' TEXT, 'cabang' TEXT, 'nama' TEXT, 'noka' TEXT, 'nosin' TEXT, PRIMARY KEY('nopol') ON CONFLICT REPLACE);`

**Comment by agusibrahim** [comment]
> Do you issue any other SQL commands ...

No, table successfully created. after that i insert large data via curl

**Comment by otoolep** [comment]
The problem is that SQLite does like your data. And because you request the load operation to take place within a transaction (`transaction`) the entire load operation is rolled back in the event of any error. Also, assuming this is the cause, this should have been clear if you just examine the output from `curl`.

Session below.

```bash
$ curl -v -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
    " CREATE TABLE 'data' ('nopol' TEXT UNIQUE, 'mobil' TEXT, 'lesing' TEXT, 'overdue' TEXT, 'saldo' TEXT, 'cabang' TEXT, 'nama' TEXT, 'noka' TEXT, 'nosin' TEXT, PRIMARY KEY('nopol') ON CONFLICT REPLACE)"
]'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1:4001...
* TCP_NODELAY set
* connect to ::1 port 4001 failed: Connection refused
*   Trying 127.0.0.1:4001...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4001 (#0)
> POST /db/execute?pretty&timings HTTP/1.1
> Host: localhost:4001
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 186
> 
* upload completely sent off: 186 out of 186 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< X-Rqlite-Version: 7
< Date: Thu, 16 Jun 2022 01:35:35 GMT
< Content-Length: 102
< 
{
    "results": [
        {
            "time": 0.00024734
        }
    ],
    "time": 0.010329136
* Connection #0 to host localhost left intact
}
$ curl XPOST 'localhost:4001/db/execute?pretty&transaction' -H "Content-Type: application/json" -d @largedata.json
.
.
.
        {
            "last_insert_id": 229853,
            "rows_affected": 1
        },
        {
            "last_insert_id": 229854,
            "rows_affected": 1
        },
        {
            "last_insert_id": 229855,
            "rows_affected": 1
        },
        {
            "last_insert_id": 229856,
            "rows_affected": 1
        },
        {
            "error": "unrecognized token: \"')\""
        }
    ]
}
```

**Comment by otoolep** [comment]
I'm going to close this issue, please re-open if you can show your `curl` operation is running completely successfully. I suggest you examine the data you are trying to load, and correct it.

**Comment by otoolep** [comment]
I corrected the comment above at https://github.com/rqlite/rqlite/issues/1044#issuecomment-1157139530

To repeat, SQLite does not like the data you are trying to load.
