### ISSUE TITLE
error：no such table 

### ISSUE THREAD

**Issue by junode** [rqlite/rqlite#1047]
hi, google and search had done, but doesn't work.

i use postman to mock curl and send request：http://localhost:4001/db/query?level=weak&q='select * from insert_test'，the request is ok, response i want.

but when i change my request param level=weak to level=none, wrong happen: "error: no such table". the whole request ： http://localhost:4001/db/query?level=weak&q='select * from insert_test'

please help me , thanks!

**Comment by otoolep** [comment]
I'll need more information. What version are you running? Are you running a cluster? How do you create the table?

What you are doing works fine for me on a single node (rqlite is extensively tested, I'm not suprised):
```bash
~ $ curl -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
>     "CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT, age INTEGER)"
> ]'
{
    "results": [
        {
            "time": 0.000306983
        }
    ],
    "time": 0.0048623
}~ $ curl -G 'localhost:4001/db/query?pretty&timings&level=weak' --data-urlencode 'q=SELECT * FROM foo'
{
    "results": [
        {
            "columns": [
                "id",
                "name",
                "age"
            ],
            "types": [
                "integer",
                "text",
                "integer"
            ],
            "time": 0.000159977
        }
    ],
    "time": 0.000187934
}~ $ curl -G 'localhost:4001/db/query?pretty&timings&level=none' --data-urlencode 'q=SELECT * FROM foo'
{
    "results": [
        {
            "columns": [
                "id",
                "name",
                "age"
            ],
            "types": [
                "integer",
                "text",
                "integer"
            ],
            "time": 0.000172205
        }
    ],
    "time": 0.000228649
~ $ 
```

**Comment by otoolep** [comment]
Unless I can reproduce your issue (and will need a lot more detail) I can't debug it.

**Comment by junode** [comment]
thanks! yes,  version is 7, running cluster, windows environment, not Linux. And download the rqlite of the window environment to start the cluster. 

Now the company can't connect to the Internet and can't take screenshots. I will go back in the evening and reproduce the screenshots for you. You can reply tomorrow or later.

**Comment by junode** [comment]
sorry, waste your time. to insure the situation, i try again, but it work...
