### ISSUE TITLE
Unable to build rqlite on arm64

### ISSUE THREAD

**Issue by biradarsb** [rqlite/rqlite#1050]
Following steps were followed to make the build:
mkdir rqlite # Or any directory of your choice.
cd rqlite/
export GOPATH=$PWD
export GOARCH=arm64
mkdir -p src/github.com/rqlite
cd src/github.com/rqlite
git clone https://github.com/rqlite/rqlite.git
cd rqlite
go install ./...

apuser@ap-build-vm:~$ mkdir rqlite
apuser@ap-build-vm:~$ cd rqlite
apuser@ap-build-vm:~/rqlite$ export GOPATH=$PWD
apuser@ap-build-vm:~/rqlite$ export GOARCH=arm64
apuser@ap-build-vm:~/rqlite$ mkdir -p src/github.com/rqlite
apuser@ap-build-vm:~/rqlite$ cd src/github.com/rqlite/
apuser@ap-build-vm:~/rqlite/src/github.com/rqlite$ git clone https://github.com/rqlite/                                                                                          rqlite.git
Cloning into 'rqlite'...
remote: Enumerating objects: 12780, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 12780 (delta 54), reused 101 (delta 54), pack-reused 12670
Receiving objects: 100% (12780/12780), 3.44 MiB | 15.37 MiB/s, done.
Resolving deltas: 100% (7620/7620), done.
apuser@ap-build-vm:~/rqlite/src/github.com/rqlite$ cd rqlite
apuser@ap-build-vm:~/rqlite/src/github.com/rqlite/rqlite$ . /opt/new/environment-setup-aarch64-fslc-linux
apuser@ap-build-vm:~/rqlite/src/github.com/rqlite/rqlite$ go install ./...
go: downloading golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e
go: downloading github.com/Bowery/prompt v0.0.0-20190916142128-fa8279994f75
go: downloading github.com/mkideal/cli v0.2.7
go: downloading github.com/mkideal/pkg v0.1.3
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/rqlite/rqlite-disco-clients v0.0.0-20220328160918-ec33ecd01491
go: downloading github.com/rqlite/go-sqlite3 v1.25.0
go: downloading github.com/hashicorp/raft v1.3.9
go: downloading github.com/hashicorp/raft-boltdb/v2 v2.2.2
go: downloading github.com/hashicorp/raft-boltdb v0.0.0-20210409134258-03c10cc3d4ea
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading golang.org/x/sys v0.0.0-20220520151302-bc2c85ada10a
go: downloading github.com/labstack/gommon v0.3.1
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/mkideal/expr v0.1.0
go: downloading github.com/hashicorp/consul/api v1.12.0
go: downloading go.etcd.io/etcd/client/v3 v3.5.4
go: downloading github.com/armon/go-metrics v0.4.0
go: downloading github.com/hashicorp/go-hclog v1.2.0
go: downloading github.com/hashicorp/go-msgpack v1.1.5
go: downloading github.com/boltdb/bolt v1.3.1
go: downloading golang.org/x/term v0.0.0-20220526004731-065cf7ba2467
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
go: downloading github.com/hashicorp/go-rootcerts v1.0.2
go: downloading github.com/hashicorp/serf v0.9.8
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.4
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.4
go: downloading go.uber.org/zap v1.21.0
go: downloading google.golang.org/grpc v1.46.2
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/hashicorp/go-immutable-radix v1.3.1
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/golang/protobuf v1.5.2
go: downloading google.golang.org/genproto v0.0.0-20220526192754-51939a95c655
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/coreos/go-systemd/v22 v22.3.2
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading golang.org/x/net v0.0.0-20220526153639-5463443f8c37
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading golang.org/x/text v0.3.7
# github.com/rqlite/rqlite/db
db/db.go:43:28: undefined: sqlite3.Version
db/db.go:229:19: srcConn.Deserialize undefined (type *sqlite3.SQLiteConn has no field or method Deserialize)
db/db.go:233:17: srcConn.Close undefined (type *sqlite3.SQLiteConn has no field or method Close)
db/db.go:554:22: c.Prepare undefined (type *sqlite3.SQLiteConn has no field or method Prepare)
db/db.go:694:9: c.Serialize undefined (type *sqlite3.SQLiteConn has no field or method Serialize)
db/db.go:854:17: dst.Backup undefined (type *sqlite3.SQLiteConn has no field or method Backup)

**Comment by otoolep** [comment]
What operating system and CPU architecture is your host machine?

**Comment by otoolep** [comment]
Also, are you cross-compiling?

**Comment by otoolep** [comment]
I've added ARM and ARM64 builds to the official release process going forward.

https://github.com/rqlite/rqlite/commit/b28816d6062b7f7a9501e0447c065eb0cbcf4643

**Comment by NerdyShawn** [comment]
I'm trying to run the latest 7.6.1 image on some arm64 nodes but the image doesn't look to be compatible on a pi4 64bit node.

This is the has of the image[sha256-f8c03dd597a6fb9c4f10a2f275ff7a8b80994f3169324c102c13be395750a02a]( https://hub.docker.com/layers/rqlite/rqlite/latest/images/sha256-f8c03dd597a6fb9c4f10a2f275ff7a8b80994f3169324c102c13be395750a02a?context=explore)
```c
k get sts -n rqlite rqlite -o yaml | grep  image
        image: rqlite/rqlite:7.6.1

k logs -n rqlite rqlite-0 
exec /bin/docker-entrypoint.sh: exec format error
```
Am I missing something or is there somewhere else to get an the arm64 build? Thanks!

**Comment by otoolep** [comment]
Yes, you may have to build for a specific CPU, you can see the ARM build options I use for the ARM release in the packaging script.

https://github.com/rqlite/rqlite/blob/master/package.sh#L127

**Comment by NerdyShawn** [comment]
Ah ok, I think the[ ci build scrpt in rqlite-docker that publishes to docker hub](https://github.com/rqlite/rqlite-docker/commit/1e8fcf818daae5876c3ae0176f176c3f9163d3f3#r84754899), I think can use an update though with **buildx** then have multi-platform in the image, so that whatever nodes in a given kuberentes cluster, armv7,armv8,amd64 can all use the same image. I got it working yesterday with setting up a buildx with the buildkit

```c
/rqlite/rqlite-docker/7.6.1$ docker buildx build . --platform linux/arm64,linux/amd64,linux/arm/v7
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 0.8s (19/19) FINISHED                                                                                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 891B                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [linux/arm/v7 internal] load metadata for docker.io/library/alpine:latest                                                                                                                                 0.6s
 => [linux/arm64 internal] load metadata for docker.io/library/alpine:latest                                                                                                                                  0.6s
 => [linux/amd64 internal] load metadata for docker.io/library/alpine:latest                                                                                                                                  0.6s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                                                 0.0s
 => [linux/amd64 1/4] FROM docker.io/library/alpine:latest@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                                            0.1s
 => => resolve docker.io/library/alpine:latest@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                                                        0.1s
 => [internal] load build context                                                                                                                                                                             0.0s
 => => transferring context: 42B                                                                                                                                                                              0.0s
 => [linux/arm64 1/4] FROM docker.io/library/alpine:latest@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                                            0.1s
 => => resolve docker.io/library/alpine:latest@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                                                        0.1s
 => [linux/arm/v7 1/4] FROM docker.io/library/alpine:latest@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                                           0.1s
 => => resolve docker.io/library/alpine:latest@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                                                                        0.1s
 => CACHED [linux/amd64 2/4] RUN apk update &&     apk --no-cache add curl tar &&     curl -L https://github.com/rqlite/rqlite/releases/download/v7.6.1/rqlite-v7.6.1-linux-amd64-musl.tar.gz -o rqlite-v7.6  0.0s
 => CACHED [linux/amd64 3/4] RUN mkdir -p /rqlite/file                                                                                                                                                        0.0s
 => CACHED [linux/amd64 4/4] COPY docker-entrypoint.sh /bin/docker-entrypoint.sh                                                                                                                              0.0s
 => CACHED [linux/arm64 2/4] RUN apk update &&     apk --no-cache add curl tar &&     curl -L https://github.com/rqlite/rqlite/releases/download/v7.6.1/rqlite-v7.6.1-linux-amd64-musl.tar.gz -o rqlite-v7.6  0.0s
 => CACHED [linux/arm64 3/4] RUN mkdir -p /rqlite/file                                                                                                                                                        0.0s
 => CACHED [linux/arm64 4/4] COPY docker-entrypoint.sh /bin/docker-entrypoint.sh                                                                                                                              0.0s
 => CACHED [linux/arm/v7 2/4] RUN apk update &&     apk --no-cache add curl tar &&     curl -L https://github.com/rqlite/rqlite/releases/download/v7.6.1/rqlite-v7.6.1-linux-amd64-musl.tar.gz -o rqlite-v7.  0.0s
 => CACHED [linux/arm/v7 3/4] RUN mkdir -p /rqlite/file                                                                                                                                                       0.0s
 => CACHED [linux/arm/v7 4/4] COPY docker-entrypoint.sh /bin/docker-entrypoint.sh    
```
