### ISSUE TITLE
Kernel issues while running rqlite

### ISSUE THREAD

**Issue by kushwaha-aman** [rqlite/rqlite#1062]
**What version are you running?**
v7.6.1

**What did you do?**
Trying to start a node on my Centos machine.

**What happened instead?**
I ran the binary in default fashion:
./rqlited -node-id 1 ~/node.1

The binary crashes with following error:
FATAL: kernel too old
Aborted (core dumped)

It doesn't give any other logs as well.

I'm running Centos 6.4 with glibc version 2.12
I tried to run it on my other Centos machine with glibc 2.17 and it seems to be working.
If this is the case, maybe a patch is required, if it cannot be patched maybe we should be put as a limitation.

**Comment by otoolep** [comment]
Thanks for the report. It looks like Centos 6.4 is almost 10 years old? https://wiki.centos.org/Manuals/ReleaseNotes/CentOS6.4

I probably won't look into this issue much, as I think it's quite unlikely folks are running distros that old.

**Comment by otoolep** [comment]
Again, thanks for the report, but I don't plan to look into this. If you believe this is incorrect, please let me know why.
