### ISSUE TITLE
API should support nil as parameter

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#1073]
https://rqlite.slack.com/archives/C0324J4LC91/p1665626647783139

**Comment by otoolep** [comment]
It supports it fine, actually. Looks like a Go client issue.

**Comment by otoolep** [comment]
https://rqlite.slack.com/archives/C0324J4LC91/p1665629560821889

**Comment by otoolep** [comment]
Actually, may not quite be right.

**Comment by otoolep** [comment]
```bash
$ curl -XPOST 'http://kotsadm:password@10.43.141.224:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
    ["INSERT INTO test(name, value) VALUES(?, ?)", "fiona", null]
```
]'
unsupported type

**Comment by sgalsaleh** [comment]
Note: this is only an issue with parameter binding. Title can be changed to something like:

"API should support null values when using parameter binding"
