### ISSUE TITLE
Support graceful restarts without client impact

### ISSUE THREAD

**Issue by jtackaberry** [rqlite/rqlite#1132]
I was looking for a lightweight, simple, HA database for a small web app and rqlite seems perfect for my use case.  I plan to host the app in low-cost Kubernetes cluster and small footprint was a key requirement.  So, firstly, thanks for your work on this project.

As I'm an SRE by trade, one of the first things I tried with rqlite wasn't to start coding with it -- far too practical for my tastes -- but rather stood it up in Kubernetes (adapting the StatefulSet example) and began beating the hell out of it, knocking nodes out, SIGKILLing the processes, doing rolling restarts, etc. while querying in the background in order to observe the impact on clients.

While a vicious SIGKILL is naturally visible to clients, I felt graceful restarts disrupted clients more than should be necessary.

As I'm sure you know, when Kubernetes terminates a pod (such as during a rolling restart), it sends a SIGTERM to pid 1 and waits for `terminationGracePeriodSeconds` before stepping in with harsher measures.   The idea here is for rqlite to hook SIGTERM and handle it in the following ways:
   1. If a follower, continue to forward queries to the leader as usual for a configurable amount of time.  Kubernetes will meanwhile withdraw the terminating rqlite pod from the list of endpoints for the client-facing service which will naturally shift incoming connections away from it.
  2. If a leader, induce an election that excludes itself from being eligible for subsequent leader role. This will move the leader somewhere else, and requests being forwarded from followers will shift there.   Process in-flight reads as normal in the meantime.  K8s will soon stop sending direct client requests (which typically happens less than a second after the pod enters terminating state), so at that point we know all new reads are being forwarded.
     
     Writes seem trickier, because I think there could be a race where a follower forwards a write to a leader at the same time as a new leader is elected.  The solution that comes to my mind is, upon receipt of SIGTERM, before initiating the new election complete all in-flight writes but refuse to accept new ones (returning 503 leader not found as usual) .  Your intuitions are surely better. :)

In both cases, the amount of time should be configurable, which the user would likely tune based on the realistic max query/execute time, to allow any in-flight transactions to complete.   After this amount of time elapses, exit.

This should make graceful pod restarts transparent for most reads (except those whose duration exceeds the configurable threshold), and least improve the situation for writes by reducing the window where the cluster is without a healthy leader.

These things are always more slippery and nuanced than they seem, so I'm sure there are dragons lurking around corners, but I hope the basic premise is salvageable.

**Comment by otoolep** [comment]
Thanks for your write-up -- good to read. I have one question.

>The idea here is for rqlite to hook SIGTERM and handle it in the following ways:

For suggestion #1, isn't that exactly what you see now? The follower will continue to forward queries to the leader until it's actually shutdown. So it's not entirely what you'd like.

As for #2: what are you seeing now, just so I am clear? I presume the leader is killed suddenly, and then leadership election kicks off. For a few seconds there is no leader (which will block writes) -- is this the issue? Getting ahead of this, as you suggest, may be possible -- see [this call](https://pkg.go.dev/github.com/hashicorp/raft#Raft.LeadershipTransfer) in the Raft library. However it may still mean a few seconds of no-leader during the handover (I'd need to test it). Is this what you mean? So it sounds like you want something like this:
- I've just got SIGTERM!
- I'm the leader!
- Better handoff leadership to another node before I'm shut down for good.

Right? This sounds reasonable, I could look into it.

**Comment by otoolep** [comment]
Update, to quote the Raft docs: _This message has the same effect as if the election timeout on the target server fires._ So adding this in response to the Leader receiving SIGTERM probably won't make Leader shutdown completely invisible to clients. Might save a second or two, depending on your config however. Probably worth a try, and may be easy to code.

**Comment by otoolep** [comment]
Try the latest release, 7.12.0, and see if shutdown is a bit easier on clients. If a node is leader it can be instructed to stepdown as Leader before shutting down. You need to pass `-raft-shutdown-stepdown` as an arg to enable this.

See https://github.com/rqlite/kubernetes-configuration/blob/master/statefulset-1-node.yaml#L21

**Comment by jtackaberry** [comment]
@otoolep  wow, the improvement is beyond my wildest expectations.  I repeatedly knocked out the leader about a dozen or so times, and in every case the client disruption was fully resolved in less than 100ms. Nicely done!

**Comment by otoolep** [comment]
Glad to hear it. My testing did show that the leadership change happened quite quickly too -- faster than I was expecting.

As for #1, I'm not I'll do anything extra at this time. One idea would be *not* to exit when receiving SIGTERM -- just transfer leadership (if the leader) and then just wait to be killed. Alternatively try out 7.12.1 when it comes out as it will more cleanly shutdown the HTTP server and that might actually result in a better experience too.

**Comment by otoolep** [comment]
@jtackaberry -- since you're seeing such better operations when you knock out a node, perhaps I should default this behaviour to on by default? I can't think of any reason not do so. Can you? It's just speeding up something that was was happening anyway (node shutdown followed by leader election).

**Comment by jtackaberry** [comment]
Yeah I don't really see any downside to enabling it by default.  Being conservative, it makes some sense to tuck a behavior change behind a feature flag initially, but I can't think of a scenario where you *wouldn't* want this behavior.

**Comment by otoolep** [comment]
Going to close for now, thanks for your feedback.

**Comment by jtackaberry** [comment]
> One idea would be not to exit when receiving SIGTERM -- just transfer leadership (if the leader) and then just wait to be killed.

IMO this somewhat violates the contract of SIGTERM.  It might be perfectly safe in the context of rqlite, but absent that prior knowledge a user wouldn't be unreasonable in assuming the application is misbehaving.

> Alternatively try out 7.12.1 when it comes out as it will more cleanly shutdown the HTTP server and that might actually result in a better experience too.

That's definitely more correct and will help to further narrow the window of client impact.  It technically won't address the specific issue I described assuming in-flight transactions complete quickly (and on average I'm sure they would), which would get us to exit that much more quickly.

But ultimately I'm happy to leave this one alone.  The preStop lifecycle hook I mentioned earlier entirely solves the problem, and as long as the rqlite container has the sleep command available it's also a trivial thing to add.  I'm currently sleeping for 5 seconds in the preStop (as in my example) and have set terminationGracePeriodSeconds to 10 seconds and rqlite v7.12.0 has been very robust when killing both leaders and followers. :+1:
