### ISSUE TITLE
Cache auth results when using hashed passwords

### ISSUE THREAD

**Issue by jtackaberry** [rqlite/rqlite#1138]
Enabling auth with the default bcrypt cost (5) makes simple queries a bit less than an order of magnitude slower (from about 3ms to 25ms in my environment) .   Higher bcrypt costs (such as 10) jump to about 2 orders slower (over 100ms).  And of course there is a corresponding CPU increase on the server side.

A simple solution is to just cache the validity of successful auth requests so rqlite can avoid recomputing the hash on every request. Unsuccessful auth should probably not be cached.

**Comment by otoolep** [comment]
Interesting idea - hadn't occurred to me before. It sounds reasonable. To be specific, the code would cache the "cleartext password" -> "bcrypted hash" mapping, avoiding the need to bcrypt the cleartext password if it was already in map.

One question: any practical concerns about a malicious user dumping the memory space of `rqlited` and getting access to the map? That would tell them which cleartext passwords were valid. Perhaps if the user has that kind of access there are bigger issues.

**Comment by otoolep** [comment]
https://security.stackexchange.com/questions/10520/is-it-safe-or-even-common-to-cache-bcrypt-checks-in-memory for example. The thread seems to think it's probably OK to do.

**Comment by otoolep** [comment]
https://stackoverflow.com/questions/29483493/is-it-a-bad-practice-to-cache-users-hashed-credentials-on-the-server

**Comment by jtackaberry** [comment]
Does the Go GC zero out memory when it collects an object? Being resistant to memory dumps would require that too.  So this may not actually introduce a new security weakness.

But even if it did, to your point, someone with access to dump the process space almost certainly could also just read the underlying raft log and SQLite snapshot anyway, which is all the credentials ultimately protect.

**Comment by otoolep** [comment]
```bash
$ go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/rqlite/rqlite/auth
cpu: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
BenchmarkCredentialStore-8          	33748196	        34.42 ns/op
BenchmarkCredentialStoreNoCache-8   	      19	  59543518 ns/op
PASS
ok  	github.com/rqlite/rqlite/auth	4.696s
```

Big difference in performance.
