### ISSUE TITLE
Is there any method to run rqlite on Andriod device?  

### ISSUE THREAD

**Issue by tomly2019m** [rqlite/rqlite#1154]
I am using rqlite to do task schedule with different type of devices, include PC, TV and mobile phone. And I get into with running rqlite on Andriod devices, so I wander if there is any possible to relize it;

**Comment by otoolep** [comment]
Have you reviewed? https://rqlite.io/docs/install-rqlite/building-from-source/

**Comment by otoolep** [comment]
I also suggest you join the Slack channel, or send an email to the rqlite Google Group.

https://rqlite.io/community/
