### ISSUE TITLE
Support for RETURNING in api response

### ISSUE THREAD

**Issue by alexgreendesign** [rqlite/rqlite#1157]
Thanks so much for your great work on RQLite - it's fantastic.

Would it be possible to add support for RETURNING in the api response?

For example, a query like:
`DELETE FROM table WHERE column = 'value' RETURNING other_column;`
Should return other_column. 

It does return last_insert_id, which in the case of inserts can be followed by a SELECT to get the data as a workaround, but this doesn't work for deletes.

**Comment by otoolep** [comment]
Thanks for your report.

What do you mean it isn't supported? Can you show me using actual API calls what happens, and what you expect? To address this issue as fast as possible, a full reproduction case would be best. I.e. create your table, do your query, show me what you get, and explain what you actually want. I would need to see all of this in, say, the form of `curl` requests (or at least as actual rqlite shell session).

https://rqlite.io/docs/api/api/ for examples on using `curl`.

**Comment by alexgreendesign** [comment]
Sure:

```
curl -XPOST 'localhost:4001/db/execute?pretty' -H "Content-Type: application/json" -d '[
    "CREATE TABLE _test (id INTEGER NOT NULL PRIMARY KEY, name TEXT)"
]'

curl -XPOST 'localhost:4001/db/execute?pretty' -H "Content-Type: application/json" -d '[
    "INSERT INTO _test ( name ) VALUES( '1' ) RETURNING id;"
]'
```

Returns:
```
{
    "results": [
        {
            "last_insert_id": 1
        }
    ]
}
```

Expected something like:
```
{
    "results": [
        {
            "last_insert_id": 1,
            "types": {
                "id": "integer"
            },
            "rows": [
                {
                    "id": 1
                }
            ]
        }
    ]
}
```

Also for example:
```
curl -XPOST 'localhost:4001/db/execute?pretty' -H "Content-Type: application/json" -d '[
    "INSERT INTO _test ( name ) VALUES( '2' ) RETURNING name;"
]'
```

Returns:
```
{
    "results": [
        {
            "last_insert_id": 2,
            "rows_affected": 1
        }
    ]
}
```

Expected something like:
```
{
    "results": [
        {
            "last_insert_id": 2,
            "rows_affected": 1,
            "types": {
                "name": "text"
            },
            "rows": [
                {
                    "name": "2"
                }
            ]
        }
    ]
}
```

And:
```
curl -XPOST 'localhost:4001/db/execute?pretty' -H "Content-Type: application/json" -d '[
    "DELETE FROM _test WHERE name = '1' RETURNING id;"
]'
```

Returns:

```
{
    "results": [
        {}
    ]
}
```

**Comment by otoolep** [comment]
Got it, thanks. 

I'll have to look into the SQLite API itself, and see how to use it when passing a `RETURNING`. It's not immediately obvious to me, so it might take a little time. I'll let you know what I find.

**Comment by otoolep** [comment]
There seems to be an easy way, and a hard way, to help you. It depends on how you are using the rqlite.

One possible way is to send your statement to the query endpoint with STRONG read consistency, something like so:

```bash
curl -XPOST 'localhost:4001/db/query?pretty*level=strong' -H "Content-Type: application/json" -d '[
    "DELETE FROM _test WHERE name = '1' RETURNING id;"
]'
```
This is basically telling rqlite to a) send the SQL statement through the Raft log, but also get a rows object back. This won't work as is, but will require some more coding. It wouldn't be too difficult, but would require you to talk to rqlite differently than perhaps you do now. Are you using any client library to talk to rqlite?

The hard way, but which would be transparent, would be for rqlite to parse the SQL statement, and if it finds a `RETURNING` statement, then just do the right thing automatically. I prefer the hard way, but it will take longer to code.

**Comment by alexgreendesign** [comment]
Hi Philip, thanks for looking at this so quickly.

I'm not using any libraries to talk to rqlite apart from the one I've made myself, so I'd be happy to adjust the query when `RETURNING` is in the sql, although I think I prefer the hard way too, which would keep the api usage a bit simpler.

**Comment by otoolep** [comment]
https://github.com/axllent/mailpit/issues/254#issuecomment-1975140163

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/pull/1721 pulls in the latest SQL parser, which supports `RETURNING`.
