### ISSUE TITLE
`-node-ca-cert` leads to rejection of peer node certificates from the correct CA

### ISSUE THREAD

**Issue by otto-dev** [rqlite/rqlite#1165]
Setting `-node-ca-cert` to the root CA leads to `rqlite` rejecting other nodes via raft, even though they present a matching client certificate.

Workaround is to `export SSL_CERT_FILE=/path/to/ca.crt` to overwrite the CA store manually in the golang library - then the incoming node connections are accepted, even though the CA files are the same. (tested on arch linux)

With `-node-ca-cert /secrets/ca.crt` only:

```
2023-02-24T00:09:02.033Z [ERROR] raft: failed to make requestVote RPC: target="{Voter 0 [fd00:xxxx:a:3]:4002}" error="x509: certificate signed by unknown authority" term=2
```

With `SSL_CERT_FILE=/secrets/ca.crt` and `-node-ca-cert /secrets/ca.crt`:

```
2023-02-24T00:10:58.503Z [INFO]  raft: election won: term=2 tally=2
2023-02-24T00:10:58.503Z [INFO]  raft: entering leader state: leader="Node at [fd00:xxxx:a:1]:4002 [Leader]"
2023-02-24T00:10:58.504Z [INFO]  raft: added peer, starting replication: peer=1
2023-02-24T00:10:58.504Z [INFO]  raft: added peer, starting replication: peer=0
```

rqlite v7.13.1

**Comment by otoolep** [comment]
Same thing as the other bug. Whatever cert supplied via `-node-ca-cert` is loaded here: https://github.com/rqlite/rqlite/blob/v7.13.2/tcp/mux.go#L285. Do you think that is incorrect?

**Comment by otto-dev** [comment]
Firstly, thanks for making this great software!

> Do you think that is incorrect?

It must be insufficient, at least, because because I'm seeing the error `x509: certificate signed by unknown authority`, even though `-node-ca-cert` should instruct the node to trust the CA (which was used to sign `-node-cert`). If I use the `SSL_CERT_FILE` environment variable hack to set the CA, then I get the expected behavior.

I might dig a bit deeper when I find some time. First I'd have to find out where the error is coming from. Grepping for "failed to make requestVote" doesn't give me anything in the code-base. It seems there is some connection that the CA is not properly propagated to.

```
[ERROR] raft: failed to make requestVote RPC: target="{Voter 0 [fd00:xxxx:a:3]:4002}" error="x509: certificate signed by unknown authority" term=2
```
