### ISSUE TITLE
Setting `-http-ca-cert` has no effect on verification of incoming HTTPS client connections

### ISSUE THREAD

**Issue by otto-dev** [rqlite/rqlite#1166]
`-http-ca-cert` should be used to validate the certificate of incoming TLS connections via HTTPS for mutual TLS. However, setting the flag does not have any effect.

The server responds to the request whether or not `-http-ca-cert /secrets/ca.crt` is set and without a valid client cert provided:
```
$ curl -k -G 'https://xxxx:4001/db/query' --data-urlencode 'q=SELECT * FROM foo' # should fail to establish a connection
{"results":[{"error":"no such table: foo"}]}
```
`-http-no-verify` is not set.

The workaround from #1165 does not work here.

rqlite v7.13.1

PS: Or is `-http-ca-cert` only used for some form of HTTPS node-to-node communication, to validate the peers cert? In any case mTLS for client connections would be good to have.

**Comment by otoolep** [comment]
`-http-ca-cert` is used to set the Certificate Authority root certificate. Why do you think it has anything to do with mutual TLS? rqlite has no support for mutual TLS.

**Comment by otoolep** [comment]
From `rqlited` help:

```
  -http-ca-cert string
    	Path to root X.509 certificate for HTTP endpoint
  -http-cert string
    	Path to X.509 certificate for HTTP endpoint
```

If you want to set the HTTP cert, then set `-http-cert`. Perhaps I am missing something, but the only thing rqlite supports is presenting a cert to the HTTPS clients, so they can validate that the rqlite node is who it says it is (just like when you go to https://www.google.com and can be sure it's Google because Google presents a signed cert to prove it is who you say it is).

The code that sets up TLS config is here: https://github.com/rqlite/rqlite/blob/master/http/service.go#L1741

Perhaps some detail on TLS setup is lost on me?

**Comment by otoolep** [comment]
I guess I may not fully appreciate what setting up the CertPool actually does? But as you can see from the code above, if a CA cert file is supplied, it is read and loaded into the `config.RootCAs` variable.

**Comment by otoolep** [comment]
Any CA cert you supply via `-http-ca-cert` is read and this variable is set:
```
// RootCAs defines the set of root certificate authorities
// that clients use when verifying server certificates.
// If RootCAs is nil, TLS uses the host's root CA set.
RootCAs *[x509](https://pkg.go.dev/crypto/x509).[CertPool](https://pkg.go.dev/crypto/x509#CertPool)
``

What rqlite does not do is set:
```
// ClientCAs defines the set of root certificate authorities
// that servers use if required to verify a client certificate
// by the policy in ClientAuth.
ClientCAs *[x509](https://pkg.go.dev/crypto/x509).[CertPool](https://pkg.go.dev/crypto/x509#CertPool)
```

Code snippets taken from https://pkg.go.dev/crypto/tls#Config. This is not an area I know a huge amount about, so if you think rqlite is doing something wrong, let me know.

**Comment by otto-dev** [comment]
> Why do you think it has anything to do with mutual TLS?

I falsely thought so, because it escaped me that the nodes also communicate with each other via HTTPS. So I thought the `ca-cert`'s purpose can only be to validate the client cert of incoming connections (i.e. from applications), which implies mutual TLS. But in fact, as I understand now, it's used to accept the self-signed certificate of peer nodes via HTTPS.

>  rqlite has no support for mutual TLS.

That changes things, we can close this issue.
