### ISSUE TITLE
[Question] Clarification on securing inter-node raft communication

### ISSUE THREAD

**Issue by otto-dev** [rqlite/rqlite#1167]
I've reviewed the [Security guide](https://rqlite.io/docs/guides/security/) and would like to confirm my understanding. By default, I enable mutual TLS on all services as a best practice for blocking malicious actors within the same data-center. However, since rqlite doesn't currently support mutual TLS, I need to reconsider my security approach.

Specifically, while I can secure HTTPS traffic via Baisc Auth, I'm concerned about securing inter-node raft communication. If an attacker within the same data-center connects to the unsecured raft ports with a rogue version of rqlite, how much access can they gain? Is it possible (and necessary) to prevent such connections by setting `-node-ca-cert` to a CA that only I have access to?

**Comment by otoolep** [comment]
I am interested in implementing mutual TLS, rqlite security is important to me. The current TLS support in rqlite is mostly about preventing eavesdropping of internode traffic. To prevent rogue nodes connecting to the Raft port I suggested network-based protections, as you probably saw in the guide.

A rogue node could probably cause some damage by connecting to the Raft port -- in fact any program could send TCP traffic to the port. That's why I suggest network-based security (only allowing connections from specific IP addresses, for example).

However I think your request is valid -- and presumably it's easy enough to add to rqlite. Let me look into it.

**Comment by otoolep** [comment]
After some quick study of the Go TLS docs, I think I can add mutual-TLS support fairly easily.

@otto-dev -- can you build rqlite yourself and deploy, if I push changes to the `master` branch? Otherwise I can add the functionality I think, and make a candidate release which you can test. Or are you running Docker images?

**Comment by otoolep** [comment]
I would add the support for both the HTTP server (port 4001) *and* inter-node communications (port 4002).

**Comment by otoolep** [comment]
For my own reference: https://venilnoronha.io/a-step-by-step-guide-to-mtls-in-go

**Comment by otto-dev** [comment]
Thank you so much for taking the time to investigate this and for considering my request. I also wanted to share some high-level thoughts on the implementation.

Regarding mutual TLS for raft communication, it should be possible to add it transparently. What I mean is that making it the new default when `-node-cert` is provided shouldn't cause any issues for existing users, since -node-cert is already trusted by either -node-ca-cert or system defaults. By using the certificates and CA in both directions, nothing should break.

In terms of convenience for users, you could consider adding a flag like `-node-no-hostname-verify` to disable TLS hostname verification. While I personally wouldn't use this flag, it could be helpful for others who want the security of a private CA without having to include each node's hostname and IP in their certificates. However, it's not strictly necessary and can be skipped for now.

For HTTPS communication, I would recommend adding a new flag like` -http-verify-client` to maintain backwards-compatibility. Additionally, reusing the CA from `-http-ca-cert` (if any) for mTLS is a common practice, so a separate flag like `-http-client-ca-cert` may not be necessary.

As in the `raft` case, it may also be worth considering whether to include a flag like `-http-no-hostname-verify`, although this is not strictly required and would mainly be for convenience.

So for raft communication, present and expect the `-node-cert` both ways, if defined, and honor `-node-no-verify` and `-node-ca-cert` both ways.

Same for HTTP, except there it has to be enabled using ` -http-verify-client`.

> can you build rqlite yourself and deploy

Can definitely build and deploy rqlite myself for now if you push the changes to the master branch. Thank you again for your time and effort!

**Comment by otoolep** [comment]
>In terms of convenience for users, you could consider adding a flag like -node-no-hostname-verify to disable TLS hostname verification. 
Just so I am clear, this means that if should be enough for the client to send a cert that has been signed by the right CA, but ignore all other checks, is that?

**Comment by otto-dev** [comment]
Yes, basically. See https://github.com/golang/go/issues/21971.

Here is how to implement it: https://github.com/golang/go/commit/29cfb4d3c3a97b6f426d1b899234da905be699aa

It seems there is no built-in configuration flag for this in `go`. I would consider this feature optional for the first mTLS iteration.

**Comment by otoolep** [comment]
OK, thanks, let me work on this. I've started some exploratory work https://github.com/rqlite/rqlite/pull/1169 so that I learn this whole area a bit better. Most of the work will be some x509 and TLS utilities to create (and test) TLS configs correctly. Once I've done that, it should be quite straightforward. I'll also look into adding "no hostname verify" in a follow-up.

**Comment by otto-dev** [comment]
If there is any way I can help with along the way, please let me know. 
I haven't studied and used `go` as a programming language yet, but I can still act as a rubber duck for some question, testing some TLS functionality, having a look at some piece of code...

**Comment by otoolep** [comment]
Thanks, unless you're a Go programmer the best thing you can do is to help me test releases. That would actually be best -- and much appreciated.

**Comment by otoolep** [comment]
I'll implement mTLS for the HTTP connection first, would you be interested in testing that first?

**Comment by otto-dev** [comment]
Absolutely, as soon as there is anything I can test (even partial functionality) let me know.

**Comment by otoolep** [comment]
I do see one reason why HTTP mTLS was not working -- I wasn't setting `ClientAuth` in the TLS config. I was just setting the CA cert that would be used to check client-presented certs, but not telling the HTTP service to actualy check. I need to set it to one of these options: https://pkg.go.dev/crypto/tls#ClientAuthType

I could make it configurable, but perhaps we can come back to that. So for the first version I suggest I set it to the most strict option, which is `RequireAndVerifyClientCert`. Sound good?

(I'm going to add a lot more testing around this whole area).

**Comment by otoolep** [comment]
You can see the first mTLS unit test here (certs on both side, both certs signed by the same CA): https://github.com/rqlite/rqlite/blob/7852b27dcb796e00a3d6f0e64eec7f4a5ea1f9b7/http/service_tls_test.go#L141

Not passing yet, client still not trusted, but getting there.

**Comment by otoolep** [comment]
The tests pass now, just a matter of doing some final hooking up of the code.

**Comment by otto-dev** [comment]
Looking good so far, if I intercept the `Test_TLSServiceSecureMutual` with `openssl s_client -connect 127.0.0.1:xxxxx -prexit` I can see that the server is asking for the right client-side certificate:

```
Server certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
subject=CN = server.rqlite.io
issuer=CN = ca.rqlite.io
---
Acceptable client certificate CA names
CN = ca.rqlite.io
```

**Comment by otoolep** [comment]
@otto-dev -- can you build a branch? Working code should be available at https://github.com/rqlite/rqlite/pull/1171

I added a bunch of new command-line params, full details in the PR description. Let me know what you think.

**Comment by otoolep** [comment]
There is one thing to understand about how rqlite clustering work.

When a node first joins a cluster, it accesses that cluster via the HTTP API of any node which is already a member of the cluster. That is why nodes must have a HTTP client cert and key if you want to do full mutual TLS. Once a node joins successfully, it switches over to "node communications" (port 4002 by default) and will then use the other certs and keys (`-node...`). There is no reason why they can't be all the same certs of course.

However this does mean that clients -- end-users accessing the query API will also need client certs to access to rqlite, if you enable mTLS on the HTTP API. You probably already realise this.

**Comment by otoolep** [comment]
BTW, for your original use case, were you only interested in mTLS for Raft communications? That's fine, just curious. The PR adds support for mTLS for both the HTTP API and the internode Raft comms. But, as I explained above, there is one time a node talks to another node via HTTP -- and that's when it first tries to join the cluster. So you have two options for authenticating and thorizing that:
- use BasicAuth
- use mTLS on the HTTP API too. But this will then force all rqlite clients to use mTLS too. Let me know if this is an issue.

**Comment by otto-dev** [comment]
Thank you for your considerate questions.

> For your original use case, were you only interested in mTLS for Raft communications?

Interested in both, but raft mTLS was a must. Without raft mTLS I would not have been able to secure the database in my environment. For HTTP, `Basic Auth` + `TLS` gives me reasonable security.

However, I am also interested in HTTP mTLS for the following reasons:
- Easier deployment. I don't have to manage credentials in the vault, and then write them to configuration files and pass them around, bake them into the URLs etc. Instead I can use my existing infrastructure to generate client & server certs and don't have to worry much.
- As a general principle, I trust TLS (transport layer) more than Basic Auth (application layer). Can't even establish a connection without a valid certificate, and the implementation is provided upstream from a trusted source.

So I'll definitely switch to mTLS as soon as I can.

If I was an enterprise company, then I would also appreciate the ability to have all the features that come with SSL certificates, such as expiration dates and renewal, the ability to invalidate stolen certificates, etc.

I believe this PR may also make rqlite more appealing to more paranoid and enterprisy companies who may have mTLS as a requirement in their policies. I was however coming purely from a pragmatic engineering and security perspective.

> This will then force all rqlite clients to use mTLS too. Let me know if this is an issue.

No, this is fantastic and desired. Once you have an good infrastructure for automated certificate generation, you can pump out new certificates wherever you want :+1:

> I added a bunch of new command-line params, full details in the PR description. Let me know what you think.

Will have a look, amazing work, on an already amazing software :star_struck:
