### ISSUE TITLE
Does rqlite have an auto-deletion feature ?

### ISSUE THREAD

**Issue by didiaibiancheng** [rqlite/rqlite#1184]
I want to start using an in-memory database with an auto-deletion feature enabled and set for a couple hours. I have a huge volume of data and requirements to support different types of complex queries (just for data persisted on last one or two hours). Does rqlite support data deletion strategy like TTL ？
If we try to do this in application level, delete the data periodic accroding to the time field. The transaction log may become larger and does rqlite support retaining a specific number of transaction log backup files, like zookeeper？

**Comment by otoolep** [comment]
No, rqlite has nothing like that built in. However you could implement it yourself, though it would require you to run a script (or something similar) outside of rqlite.

Basically create your schema with a "timestamp" column (though, for now, be sure to insert your records with explicit timestamps - see https://rqlite.io/docs/api/non-deterministic/ to learn why), and then have a script run "DELETE WHERE timestamp < now" periodically by making a query to the `db/execute` endpoint. If you're running with on-disk rqlite, you probably want to issue `VACUUM` requests every so often too.

https://www.sqlite.org/lang_vacuum.html

I think this answers your question, so closing the issue.
