### ISSUE TITLE
support for boltdb due to raft-boltdb? boltdb now seems to be an archived project

### ISSUE THREAD

**Issue by ganeshkbhat** [rqlite/rqlite#1214]
**What version are you running?**
Latest 

**Are you using Docker or Kubernetes to run your system?**
No, NA

**Are you running a single node or a cluster?**
No, NA

**What did you do?**
No, NA

**What did you expect to happen?**
what happens to support for boltdb due to raft-boltdb? boltdb now seems to be an archived project

**What happened instead?**
what happens to support for boltdb due to raft-boltdb? boltdb now seems to be an archived project

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
No, NA

**Comment by otoolep** [comment]
rqlite uses the BoltBD folk from etcd, which is maintained.

https://github.com/etcd-io/bbolt

**Comment by otoolep** [comment]
There may still be some small indirect uses of it, but I'm not concerned. BoltDB, while archived, is high-quality and still available. If that's good enough for Hashicorp, it's good enough for me -- but I'll remove any remaining references to original BoltDB and replace with etcd's version if possible.
