### ISSUE TITLE
With -bootstrap-expect option, cluster does not allow a restarted node to join

### ISSUE THREAD

**Issue by bhushanvadgave** [rqlite/rqlite#1290]
**What version are you running?**
rqlite-v7.20.0-darwin-amd64

**Are you using Docker or Kubernetes to run your system?**
Docker. But the below examples are from using rqlited on the terminal of my mac.

**Are you running a single node or a cluster?**
Cluster

**What did you do?**
With a clean disk (first time) following commands are run to start a 3-node cluster

Node 1
```
./rqlited -node-id node_1 -http-addr 0.0.0.0:4001 -raft-addr 0.0.0.0:4002 -http-adv-addr 192.168.0.182:4001 -raft-adv-addr 192.168.0.182:4002 -on-disk -on-disk-startup -on-disk-path /Users/testuser/work/rqlite_data/nodes/node_1/db/bot.sqlite -bootstrap-expect 3 -join http://192.168.0.182:4001,http://192.168.0.182:5001,http://192.168.0.182:6001 -raft-cluster-remove-shutdown=true -raft-reap-node-timeout 5s /Users/testuser/work/rqlite_data/nodes/node_1/data
```

Node 2
```
./rqlited -node-id node_2 -http-addr 0.0.0.0:5001 -raft-addr 0.0.0.0:5002 -http-adv-addr 192.168.0.182:5001 -raft-adv-addr 192.168.0.182:5002 -on-disk -on-disk-startup -on-disk-path /Users/testuser/work/rqlite_data/nodes/node_2/db/bot.sqlite -bootstrap-expect 3 -join http://192.168.0.182:4001,http://192.168.0.182:5001,http://192.168.0.182:6001 -raft-cluster-remove-shutdown=true -raft-reap-node-timeout 5s /Users/testuser/work/rqlite_data/nodes/node_2/data
```

Node 3
```
./rqlited -node-id node_3 -http-addr 0.0.0.0:6001 -raft-addr 0.0.0.0:6002 -http-adv-addr 192.168.0.182:6001 -raft-adv-addr 192.168.0.182:6002 -on-disk -on-disk-startup -on-disk-path /Users/testuser/work/rqlite_data/nodes/node_3/db/bot.sqlite -bootstrap-expect 3 -join http://192.168.0.182:4001,http://192.168.0.182:5001,http://192.168.0.182:6001 -raft-cluster-remove-shutdown=true -raft-reap-node-timeout 5s /Users/testuser/work/rqlite_data/nodes/node_3/data
```

It worked as expected. The cluster is formed. 

Now, Node 2 restarts and comes up with a new HTTP and raft address. It uses the below command to join

```
./rqlited -node-id node_2 -http-addr 0.0.0.0:5101 -raft-addr 0.0.0.0:5102 -http-adv-addr 192.168.0.182:5101 -raft-adv-addr 192.168.0.182:5102 -on-disk -on-disk-startup -on-disk-path /Users/testuser/work/rqlite_data/nodes/node_2/db/bot.sqlite -bootstrap-expect 3 -join http://192.168.0.182:4001,http://192.168.0.182:5101,http://192.168.0.182:6001 /Users/testuser/work/rqlite_data/nodes/node_2/data
```

**What did you expect to happen?**
I expect the cluster accepts Node 2's join request and add it to the cluster

**What happened instead?**
Node 2 does not get added to the cluster.

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
/nodes API response from all 3 nodes before Node 2 restarted
```
{
"node_1": {
"api_addr": "http://192.168.0.182:4001/",
"addr": "192.168.0.182:4002",
"reachable": true,
"leader": false,
"time": 0.000917959
},
"node_2": {
"api_addr": "http://192.168.0.182:5001/",
"addr": "192.168.0.182:5002",
"reachable": true,
"leader": true,
"time": 0.000671792
},
"node_3": {
"api_addr": "http://192.168.0.182:6001/",
"addr": "192.168.0.182:6002",
"reachable": true,
"leader": false,
"time": 0.000809125
}
}
```

/nodes API response from all 3 nodes after Node 2 restarted
```
{
"node_1": {
"api_addr": "http://192.168.0.182:4001/",
"addr": "192.168.0.182:4002",
"reachable": true,
"leader": false,
"time": 0.000102958
},
"node_3": {
"api_addr": "http://192.168.0.182:6001/",
"addr": "192.168.0.182:6002",
"reachable": true,
"leader": true,
"time": 0.000645208
}
}
```

**Note**
- Restarted node does not get added to the cluster regardless of whether it uses a new address or the same address.
- We have tried 7.18.2, 7.19.0 and 7.20.0 versions. This issue is present in all these versions.
- This issue does not occur if -bootstrap-expect option is not used and nodes are started in a specific order. But we do not want to have a limitation of starting the nodes in order.

**Comment by otoolep** [comment]
Hmm, thanks for your report. I will look into this today and get back to you.

**Comment by otoolep** [comment]
Actually, I think I see the issue. Do you see the following line in the log, of the node that fails to join?
```
preexisting node configuration detected, ignoring bootstrap request
```

**Comment by otoolep** [comment]
Will be fixed in 7.20.1.

**Comment by otoolep** [comment]
7.20.1 is available, thanks again for the report.

**Comment by bhushanvadgave** [comment]
@otoolep Yes, it's working. Thanks for the quick action.

**Comment by bhushanvadgave** [comment]
@otoolep Created another issue https://github.com/rqlite/rqlite/issues/1293 which is similar to this one (sorry for spamming :)). The issue is - one of the nodes of the cluster becomes unreachable after the nodes restart with new addresses. 
Thanks in advance. :)
