### ISSUE TITLE
db.Query silently converts []byte to string

### ISSUE THREAD

**Issue by bkeroackdsc** [rqlite/rqlite#130]
Here: https://github.com/rqlite/rqlite/blob/master/db/db.go#L283-L291

This means that any ``BLOB`` data types get silently returned as strings. I feel like the more appropriate solution would be to hex or base64-encode the value in the http service.

**Comment by otoolep** [comment]
Thanks @bkeroackdsc -- you are right. This is legacy I need to fix, thanks for pointing it out.

**Comment by otoolep** [comment]
PRs welcome. :-)
