### ISSUE TITLE
Which distributable of v7.21 to use on MacOS Ventura 13.4? Getting zsh exec format error.

### ISSUE THREAD

**Issue by bhushanvadgave** [rqlite/rqlite#1320]
### My System configurations
OS: MacOS Ventura 13.4
Chip: Apple M1 Pro
Rqlite Version: v7.21.0

### Issue
I tried running `./rqlited` file from the below distributables
- rqlite-v7.21.0-linux-arm64
- rqlite-v7.21.0-linux-arm
- rqlite-v7.21.0-linux-amd64
- rqlite-v7.21.0-linux-amd64-musl

But I am getting below error on every occasion. Please help.
`zsh: exec format error: ./rqlited`

**Comment by otoolep** [comment]
Looks like I forgot to release a MacOS build for that tag. However I just released v7.21.1, so you can try rqlite-v7.21.1-darwin-amd64.tar.gz 

https://github.com/rqlite/rqlite/releases/tag/v7.21.1

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/releases/download/v7.21.1/rqlite-v7.21.1-darwin-amd64.tar.gz

**Comment by bhushanvadgave** [comment]
Thanks a lot.
