### ISSUE TITLE
how to enable fts5?

### ISSUE THREAD

**Issue by jasonbigl** [rqlite/rqlite#1361]
Hi,

I have tried rqlite and it seems pretty nice for our project, but we are using ft5, when I execute `PRAGMA module_list;`, I see only ft3 and ft4, how can I enable fts5 in rqlite, thank you :)

+--------------+
| name         |
+--------------+
| json_tree    |
+--------------+
| json_each    |
+--------------+
| dbstat       |
+--------------+
| rtree_i32    |
+--------------+
| rtree        |
+--------------+
| fts3tokenize |
+--------------+
| fts4         |
+--------------+
| fts3         |
+--------------+
| fts4aux      |
+--------------+

**Comment by otoolep** [comment]
You'd need to compile rqlite yourself, as ft5 support is disabled by default in the [underlying SQLite code](https://github.com/mattn/go-sqlite3). You would need to compile rqlite, passing `-tags "sqlite_fts5 fts5"` to `go build`. I haven't tried it myself yet though.

Does that make sense? I can consider enabling fts5 support by default in the 8.0 release, though I am wondering if there are any downsides to it.

**Comment by jasonbigl** [comment]
> You'd need to compile rqlite yourself, as ft5 support is disabled by default in the [underlying SQLite code](https://github.com/mattn/go-sqlite3). You would need to compile rqlite, passing `-tags "sqlite_fts5 fts5"` to `go build`. I haven't tried it myself yet though.
> 
> Does that make sense? I can consider enabling fts5 support by default in the 8.0 release, though I am wondering if there are any downsides to it.

@otoolep thank you very much for your reply!, I'm new to golang, after a few search, I have built it via following line, please correct me if anything wrong :)

```
mkdir ~/rqlite && cd ~/rqlite

curl -L https://github.com/rqlite/rqlite/archive/refs/tags/v7.21.4.tar.gz -o v7.21.4.tar.gz && tar -zxvf v7.21.4.tar.gz

cd rqlite-7.21.4

go build --tags "fts5 sqlite_fts5" github.com/rqlite/rqlite/cmd/rqlite

go build --tags "fts5 sqlite_fts5" github.com/rqlite/rqlite/cmd/rqlited

go build --tags "fts5 sqlite_fts5" github.com/rqlite/rqlite/cmd/rqbench
```

by the way, I suggest to enable fts5 in v8.0, and when do you think v8.0 can be released? we are interested in newer version if possible.

**Comment by otoolep** [comment]
You just need to do:
 
That looks fine, you just need to build `rqlited`. Start it up, and try to create an FTS5 table -- it should work for you. 8.0 won't be out for weeks, so you may just wish to run your own build until then.

**Comment by otoolep** [comment]
This is fixed on master, FTS5 is available if you build that branch. 8.0 will now include FTS5.
