### ISSUE TITLE
failed to remove this node from cluster before shutdown: unauthorized

### ISSUE THREAD

**Issue by jasonbigl** [rqlite/rqlite#1396]
**What version are you running?**
[v7.21.4](https://github.com/rqlite/rqlite/releases/tag/v7.21.4)

**Are you using Docker or Kubernetes to run your system?**
no

**Are you running a single node or a cluster?**
cluster

**What did you do?**
1. setup a voter as leader
2. setup a non-voter to join the leader with user and password, specify `-raft-cluster-remove-shutdown=true`, full example command
`rqlited -raft-non-voter=true -node-id 10.138.0.3 -auth /rqlite/config.json -join http://rqlite-leader.company.internal:14001 -join-as abc123 -raft-cluster-remove-shutdown=true -http-addr 10.138.0.3:14001 -raft-addr 10.138.0.3:14002 -on-disk -on-disk-path /data/database.db /raft`
3. check the noe-voter status, it can join the cluster successfully.
4. gracefully shutdown non-voter

```
# /rqlite/config.json
[
    {
        "username": "abc123",
        "password": "mypassword",
        "perms": [
            "all"
        ]
    }
]
```
**What did you expect to happen?**
The non-voter should remove itself from cluster first, then shutdown

**What happened instead?**
The non-voter can not remove itself from cluster, throwing error in logs:
```
[cluster-remove] 2023/09/12 16:16:57 removing node 10.138.0.3 from cluster via leader at 10.138.15.227:14002
[cluster-remove] 2023/09/12 16:16:57 failed to remove node 10.138.0.3 from cluster via leader at 10.138.15.227:14002: unauthorized
[rqlited] 2023/09/12 16:16:57 failed to remove this node from cluster before shutdown: unauthorized
```

**Comment by otoolep** [comment]
https://rqlite.io/docs/clustering/general-guidelines/#removing-a-node-automatically-on-shutdown

Unfortunately automatic removal is not supported when auth is enabled. This will be addressed in 8.0.
