### ISSUE TITLE
Docker Hub rqlite page states wrong parameters

### ISSUE THREAD

**Issue by bluepuma77** [rqlite/rqlite#1400]
[Docker Hub of rqlite](https://hub.docker.com/r/rqlite/rqlite) describes the ENV vars
```
HTTP_ADDR_ADV
RAFT_ADDR_ADV
```

but in the [script](https://github.com/rqlite/rqlite-docker/blob/master/7.21.4/docker-entrypoint.sh) they don't exist, only
```
HTTP_ADDR
HTTP_ADV_ADDR
RAFT_ADDR
RAFT_ADV_ADDR
```

**Comment by otoolep** [comment]
You're absolutely right, thanks for catching that. I've fixed up the Docker Hub page.

**Comment by bluepuma77** [comment]
@otoolep You could add those to the page, too, if you want:
```
HTTP_ADDR
RAFT_ADDR
```
