### ISSUE TITLE
Encrypt raft.db

### ISSUE THREAD

**Issue by mhmh55516** [rqlite/rqlite#1406]
Is there a way to encrypt raft.db file and only can read with specific key ?

**Comment by otoolep** [comment]
No, no such support exists.

What use case are you trying to meet? What threat are you concerned about?

**Comment by mhmh55516** [comment]
Just for more security.

**Comment by otoolep** [comment]
Right, but what are the threat vectors you're concerned about?

**Comment by mhmh55516** [comment]
I will store a sensitive information in DB, so just wanna make sure there no one can get DB without any encryption.
