### ISSUE TITLE
The JSON result by Nodes API can be improved to meet JSON object presentation semantics

### ISSUE THREAD

**Issue by zbalkan** [rqlite/rqlite#1415]
**What version are you running?**
Version 8, commit 5de1c17d8c3bcf04f12abfadd3f996a34ecaac57, branch master, built on unknown

**Are you using Docker or Kubernetes to run your system?**
No.

**Are you running a single node or a cluster?**
Single node.

**What did you do?**
`curl localhost:4001/nodes?pretty`

**What did you expect to happen?**
```json
{
    "nodes": [
        {
            "id": "1",
            "api_addr": "http://localhost:4001",
            "addr": "localhost:4002",
            "reachable": true,
            "leader": true
        }
    ]
}
```

**What happened instead?**

```json
{
    "1": {
        "api_addr": "http://localhost:4001",
        "addr": "localhost:4002",
        "reachable": true,
        "leader": true
    }
}
```
**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
See https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

Default setup testing with single node.

The nodes are presented by objects with the ID as object type/key. Semantically, nodes are an array of objects of same type. Therefore it is reasonable for the implementation to meet the semantics.

This helps enumeration, sorting, and other JSON parsing operations, especially deserialization.

**Comment by otoolep** [comment]
Thanks, yeah, agreed, it's awkward. Since 8.0 is a major release I can make breaking changes. Let look into this.

**Comment by otoolep** [comment]
I have merged this change, but decided to keep the current behaviour as the default for now. I want to minimize changes in the 8.0 release at this time. At some point in the future I will swap to the new behaviour as the default -- but need to do work on client libraries first.
