### ISSUE TITLE
Build fails: syscall.go:82:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)

### ISSUE THREAD

**Issue by yurivict** [rqlite/rqlite#1476]
**What version are you running?**

[v8.0.3](https://github.com/rqlite/rqlite/releases/tag/v8.0.3)

**What happened instead?**

Build fails with both go-1.19 and go-1.20:
```
vendor/golang.org/x/sys/unix/syscall.go:82:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_bsd.go:247:20: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_unix.go:117:7: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
```

Older go compilers aren't available.

OS: FreeBSD 13.2

**Comment by otoolep** [comment]
Why not just upgrade Go?

**Comment by otoolep** [comment]
Thanks for flagging, I'll update `go.mod`.

**Comment by yurivict** [comment]
> Why not just upgrade Go?

To what version? go.mod says 1.16. The latest go-1.21 also fails to build rqlite.

**Comment by otoolep** [comment]
> The latest go-1.21 also fails to build rqlite

Can you be more specific? Which version of Go fails to build rqlite? I build it fine with Go 1.21 all the time. This is the version I'm running:

```bash
$ go version
go version go1.21.0 linux/amd64
```

Also, CircleCI has no problem. See: https://app.circleci.com/pipelines/github/rqlite/rqlite/3718/workflows/02096cb6-d967-46a0-bb6a-4caad38c3dee/jobs/27357

I just built with Go 1.21.5, and there were no issues either.

**Comment by yurivict** [comment]
This version fails to build rqlite:
```
$ go121 version
go version go1.21.1 freebsd/amd64
```

**Comment by otoolep** [comment]
OK, it must be something specific to that OS. Unfortunately I do not have access to that OS to debug it, and don't have any plans right now to work on freebsd support.

**Comment by otoolep** [comment]
I'm happy to take any patches if you dig into it.
