### ISSUE TITLE
go.mod lists a wrong URL: instead of github.com/rqlite/rqlite it should be github.com/rqlite/rqlite/v8

### ISSUE THREAD

**Issue by yurivict** [rqlite/rqlite#1477]
In order for GoLang servers to pick up a correct version for versions >1 the URL should end with the suffix ```/vN```.

For the version ```8.0.3``` the suffix should be ```/v8```.

[This](https://people.freebsd.org/~yuri/go-retrieve-all-packages.sh) script retrieves all package versions from GoLang servers.

**Comment by otoolep** [comment]
Same as issue #644
