### ISSUE TITLE
Readonly nodes don't work with DNS service discovery

### ISSUE THREAD

**Issue by jtackaberry** [rqlite/rqlite#1521]
I'm working on readonly nodes support for the Helm chart (now using 8.13.4), and I've hit what I think is either a bug or at least a surprising limitation.

Using `dns-srv` discovery (though this issue applies to `dns` as well), in the chart's case, passing `-disco-mode=dns-srv -disco-config={"name":"rqlite-headless","service":"raft"}`.  A discovery mechanism is is obviously going to be needed for both voting and readonly nodes alike.  For voting nodes, I'm passing `-bootstrap-expect=3`, but I excluded this for readonly nodes because they aren't technically involved in bootstrapping (being non-voters).  Conversely, readonly nodes of course get `-raft-non-voter=true`.

Being explicit, here are the rqlited command line args for both (expressed as a yaml list but you get the idea):

#### Voting nodes

```yaml
- -auth=/config/sensitive/users.json
- -join-as=_system_rqlite
- -node-cert=/config/sensitive/node.crt
- -node-key=/config/sensitive/node.key
- -node-verify-server-name=rqlite.data.svc.cluster.local
- -node-ca-cert=/config/sensitive/node-ca.crt
- -node-verify-client
- -http-cert=/config/client-tls/tls.crt
- -http-key=/config/client-tls/tls.key
- -http-ca-cert=/config/sensitive/client-ca.crt
- -disco-mode=dns-srv
- -disco-config={"name":"rqlite-headless","service":"raft"}
- -bootstrap-expect=3
- -join-interval=1s
- -join-attempts=120
- -raft-shutdown-stepdown
```

#### Readonly nodes

```yaml
- -auth=/config/sensitive/users.json
- -join-as=_system_rqlite
- -node-cert=/config/sensitive/node.crt
- -node-key=/config/sensitive/node.key
- -node-verify-server-name=rqlite.data.svc.cluster.local
- -node-ca-cert=/config/sensitive/node-ca.crt
- -node-verify-client
- -http-cert=/config/client-tls/tls.crt
- -http-key=/config/client-tls/tls.key
- -http-ca-cert=/config/sensitive/client-ca.crt
- -disco-mode=dns-srv
- -disco-config={"name":"rqlite-headless","service":"raft"}
- -raft-non-voter=true
- -join-interval=1s
- -join-attempts=120
- -raft-shutdown-stepdown
```

When I start a readonly node with the above, it aborts immediately with:

> fatal: bootstrap-expect value required when using dns-srv

Surprising, but ok, fine, I added `-bootstrap-expect=3` to the readonly node command line, but now:

> fatal: bootstrapping only applicable to voting nodes

Which actually does make sense to me.  The issue ultimately is that I can't add readonly nodes using DNS service discovery.

Is this a bug, or a missing feature?

**Comment by otoolep** [comment]
Thanks for the report, it's a missing feature. TBH I hadn't considered read-only nodes joining through autoclustering, but it's a valid thing to do (can't think of any reason why it shouldn't be supported).

I think it'll be easy enough to fix, but I'll need to think about it. I think the solution will be to remove the requirement that bootstrap-expect is needed when a node is coming up as read-only. In that case the read-only node will simply join with the addresses it gets from DNS.

**Comment by jtackaberry** [comment]
> TBH I hadn't considered read-only nodes joining through autoclustering

What's the currently supported mechanism for readonly nodes to discover the cluster to join?  The docs say "read-only nodes join a cluster in the same manner as a voting node"  but doesn't specifically mention what's required there.

>  I think the solution will be to remove the requirement that bootstrap-expect is needed when a node is coming up as read-only.

If that's all that turns out to be needed, that sounds ideal!

**Comment by otoolep** [comment]
>What's the currently supported mechanism for readonly nodes to discover the cluster to join? 

There is no officially supported mechanism right now for autoclustering and read-only nodes (though etcd and Consul might work), that's what I'll need to add.

**Comment by otoolep** [comment]
There is one thing to consider here. What network addresses do we think should be returned by DNS resolution? All rqlite nodes, or just voting nodes? I can make the code handle both cases, it's not a big deal, but I was wondering if you'd given that any thought.

**Comment by jtackaberry** [comment]
>  What network addresses do we think should be returned by DNS resolution? All rqlite nodes, or just voting nodes?

My intuition was just the voters based on the assumption that readonly nodes needs would need to seek the leader to receive streaming updates -- then voters and non-voters alike would use the same K8s Service for discovery -- but it's easy enough to create a K8s Service that includes all nodes and have the readonly pods use that one for discovery, if that makes more sense.

Bear in mind that with K8s all rqlite pods will come up simultaneously, and the DNS results will evolve over time as pods are scheduled.  That is to say, suppose we have 3 leaders and 3 readonly nodes, it's possible that a readonly node gets scheduled first, is started even before any of the leaders, and the DNS record for discovery doesn't have any results yet.  It could take several seconds before the leaders start trickling in and DNS begins returning those results.

Leaders seem to handle this without issue, but in case the nuances for readonly nodes are subtly different in this regard I thought I'd underline that behavior.

**Comment by otoolep** [comment]
This should be working on master now, simply pass the DNS config to the read-only node (but do not set any bootstrap-expect value). Re-opening this ticket as I need to update docs, and add a bit more unit testing.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/pull/1544

https://github.com/rqlite/rqlite.io/commit/08f3e800ce5de820f3eb0faac54a7f7ff6418314

**Comment by jtackaberry** [comment]
> This should be working on master now, simply pass the DNS config to the read-only node (but do not set any bootstrap-expect value).

Excellent!  Cluster joining is working with DNS now, thanks!  I am seeing something unexpected though, not sure if it's me or a bug, but I'll open a separate issue shortly before I shuffle off for NYE celebrations.

**Comment by jtackaberry** [comment]
>  I am seeing something unexpected though, not sure if it's me or a bug, but I'll open a separate issue

Opened #1545
