### ISSUE TITLE
Create web UI for rqlite

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#153]
This could be a UI that shows cluster status, and also allows the user to execute queries. A simple example is that which comes with https://github.com/ekanite/ekanite

**Comment by otoolep** [comment]
I'm not a front-end person. This would be something I'd really like help with it.

It would be great to have a straightforward single-page app that would show each node in the cluster, the status of each, and diagnostic information.

There is lots of useful information available from rqlite, as explained here: 

https://github.com/rqlite/rqlite/blob/master/doc/DIAGNOSTICS.md

For example, one could imagine the information below being presented for each node graphically, icons indicating which node is leader, the cluster topology etc etc.

```json
{
    "build": {
        "branch": "unknown",
        "build_time": "unknown",
        "commit": "unknown",
        "version": "3"
    },
    "http": {
        "addr": "127.0.0.1:4001",
        "auth": "disabled",
        "redirect": "localhost:4001"
    },
    "node": {
        "start_time": "2016-05-29T14:07:06.376018405-07:00",
        "uptime": "377.641236ms"
    },
    "runtime": {
        "GOARCH": "amd64",
        "GOMAXPROCS": 8,
        "GOOS": "linux",
        "numCPU": 8,
        "numGoroutine": 12,
        "version": "go1.6"
    },
    "store": {
        "addr": "127.0.0.1:4002",
        "dir": "/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/cmd/rqlited/data",
        "leader": "127.0.0.1:4002",
        "meta": {
            "APIPeers": {
                "127.0.0.1:4002": "localhost:4001"
            }
        },
        "peers": [
            "127.0.0.1:4002"
        ],
        "raft": {
            "applied_index": "10",
            "commit_index": "10",
            "fsm_pending": "0",
            "last_contact": "never",
            "last_log_index": "10",
            "last_log_term": "5",
            "last_snapshot_index": "0",
            "last_snapshot_term": "0",
            "num_peers": "0",
            "state": "Leader",
            "term": "5"
        },
        "sqlite3": {
            "dns": "",
            "path": ":memory:",
            "version": "3.10.2"
        }
    }
}
```

**Comment by joeblew99** [comment]
ekanite and rqlite looks really useful.

I am a golang programmer and use Polymer and gopherjs for front ends, so i could through something together pretty fast. Also once its done, it would be really easy for you to make changes to because its not like Javascript at all using polymer. 

I would need to have an idea of what you want. I have not used rqlite, but i think its a perfect match for the current project i am working on.

Let me know what you think.

**Comment by otoolep** [comment]
Thanks Joe -- was thinking a basic query box, and something which returns the results. What would be also cool would be an interface that allows you to drill down into the diagnostic information document here:

https://github.com/rqlite/rqlite/blob/master/doc/DIAGNOSTICS.md

One could imagine a single-page that hits these status and diagnostics endpoints, showing which node is the leader, cluster state, etc.

Ideas include:

https://github.com/lmenezes/elasticsearch-kopf

**Comment by joeblew99** [comment]
https://github.com/jgthms/bulma

Is a ui framework I used on the last 2 projects.
It's lite and easy 


I also like MDL if your into the Google look ;)

Let me know what your preference is.

Btw have you looked at sqllite and disk encryption. This is a use case requirement for me at least.
It would be good if the golang code supported it in someway.
It's 100% same code and API.

**Comment by otoolep** [comment]
@joeblew99 -- don't have a strong preference for this area of work, since it's not an area I know too much about. Obviously I'll be looking for high quality Go code (if any changes) and that any 3rd party packages that we import are stable and well-maintained.

If you want to push up any early ideas as PRs, I'll definitely play with it and provide feedback.

**Comment by joonas-fi** [comment]
For high-quality, typesafe and null-safe code I recommend TypeScript, React + JSX together. This way your HTML ("templates") will also be typesafe. It can also be compiled into a single .js file. Here's example of typed and null-safe frontend code from my project (note: I don't claim it's absolutely high quality code, just that the code is noticeably better than regular JavaScript): https://github.com/function61/pi-security-module/blob/e6c4f7d2c5248ef6715e2fdab787762e49fb21c1/frontend/pages/HomePage.tsx

**Comment by joeblew99** [comment]
There is a Flutter Package that can act as a GUI for a SQLite db.

https://github.com/synw/sqlview
Works on web, desktop and mobile.

There is another here: https://github.com/simolus3/moor
It does not have a Viewer yet though.

**Comment by amitkoth** [comment]
@otoolep @joeblew99 I think that the UI to query rqlite is absolutely fundamental to hot-swap existing UI-based apps that used SQLlite to use RQLite without "needing to do anything".

Is there any way to "fool" any front-end app that expects and needs SQLLite to instead use rqlite, so that we get all the benefits of UI's like datasette, etc. while using rqlite as backend?

**Comment by otoolep** [comment]
>Is there any way to "fool" any front-end app that expects and needs SQLLite to instead use rqlite, so that we get all the benefits of UI's like datasette, etc. while using rqlite as backend?

It is eminently possible, but would require programming to port a given system to the rqlite API. If there were some changes to the rqlite API that would make this easier, I'm definitely interested in learning about it. Does that answer your question @amitkoth

**Comment by amitkoth** [comment]
Thanks a lot @otoolep - we have a front-end app in mind but it uses/requires sqlite. If there was any way to hot-swap it's backend to rqlite, you'd have a whole universe of apps that expect/use sqlite over decades, but with the benefits of rqlite. Not sure where to begin.

cc @muadham

**Comment by soonoo** [comment]
Hi @otoolep,
I made a simple web UI for rqlite. Following features are supported.
- SQL query execution
- Simple view for diagnotics information
  
You can check it in [this link](http://rqman.soonoo.me:3001/menu/query-runner).
There are still a lot of things to improve, but it would be great if I could hear the opinions from the author of rqlite!

**Comment by otoolep** [comment]
Thank you @soonoo -- I took a quick look yesterday. Seems like it's down now? That's OK. 

I'm interested in learning more about this. How does it work? It is a dedicated service running somewhere? Where?

**Comment by soonoo** [comment]
@otoolep It seems like a dns problem.  
Anyway, you can check it out in http://3.39.6.116:3001/menu/query-runner .

rqman is a simple web app built with [Next.js](https://github.com/vercel/next.js) and running in AWS lightsail instance.
You can run your own rqman with below compose file but I'm not sure if It'll work in various use cases. 
```yaml
# docker-compose.yml
services:
  rqlite:
    image: rqlite/rqlite
  rqman:
    image: soonoo/rqman:0.0.3
    environment:
      - RQMAN_USERNAME=admin
      - RQMAN_PASSWORD=admin
      - RQLITE_HOST=http://rqlite:4001
    ports:
      - 3001:3000
```

**Comment by otoolep** [comment]
Thank you, very good.  You are also running a rqlite node behind this? 

Do you have any deployment docs, etc, which I can use to spin up my own instance? I'm not that familiar with Docker compose.

**Comment by soonoo** [comment]
Yes, rqlite is running.
With running rqlite cluster, you can spin up by using [docker image](https://hub.docker.com/r/soonoo/rqman).
```
docker run -p 80:3000 \
  -e RQLITE_HOST=http://{RQLITE_ENDPOINT} \
  soonoo/rqman:0.0.3
```
A more detailed instruction can be found in [README](https://github.com/soonoo/rqman#1-with-docker).  
Let me know if you need any other guidance!

**Comment by otoolep** [comment]
Thanks, I'll try it out.

Any future plans for this system? Do you plan to continue to develop it?

**Comment by otoolep** [comment]
I don't suppose it's possible to serve an application like this directly from the rqlite server?

**Comment by soonoo** [comment]
> Any future plans for this system? Do you plan to continue to develop it?  

If there are additional requirements on UI or changes to the rqlite api, I will continue developing.

> I don't suppose it's possible to serve an application like this directly from the rqlite server?  

Something like `http://{RQLITE_ENDPOINT}/ui/query-runner` by embedding rqman into rqlite?  
I have to try, but I don't think it's that difficult. I'm not sure how I can continuously reflect the changing source code of UI to rqlite though.

**Comment by otoolep** [comment]
>Something like http://{RQLITE_ENDPOINT}/ui/query-runner by embedding rqman into rqlite?
Yes, exactly. After all, rqlite runs a web server. If it was possible to integrate this UI with rqlite it will get way more usage. I would be quite interested in building a simple UI into the system itself.

>If there are additional requirements on UI or changes to the rqlite api, I will continue developing.

The API won't change in a breaking way. The UI can always be improved. :-)

>I'm not sure how I can continuously reflect the changing source code of UI to rqlite though.

You could change it via Pull Requests to the rqlite code bas, assuming it was integrated with rqlite.

**Comment by soonoo** [comment]
I totally agree with you.

Since [rqman](https://github.com/soonoo/rqman) has its own build process, all the sources files and build process should be included in the rqlite's repository to fully integrate.  
Is it okay to do this? Let me know if you have any other options in mind.

**Comment by otoolep** [comment]
I'm ok with it.

I suggest the following next steps. See if you can make rqman be served by an rqlite node. Fork the repo and try it out -- if you don't know how code Go it might be difficult though.

If integrating with rqlite is not an option I can certainly highlight your work on my blog and Twitter, but it will have to remain a standalone tool then.

**Comment by soonoo** [comment]
I'm working on it. You can check progress from the below link if interested.
https://github.com/rqlite/rqlite/compare/master...soonoo:rqlite:master (Only the `http/service.go` file is related to rqlite itself.)

When building the rqlite binary, I want to build the UI assets as well. Which file should I look into to do this?

**Comment by otoolep** [comment]
Great -- thanks for forking and working on it. Does it work?

> When building the rqlite binary, I want to build the UI assets as well. Which file should I look into to do this?

I need to understand what "build the UI assets" actually means. What does this mean, technically?

**Comment by otoolep** [comment]
Does it mean doing `yarn install && yarn build`? I'm not a front-end expert, but I imagine that what ever is the output of your build process would need to be somehow integrated into the rqlite source. But I don't know, as this not my area of expertise.

**Comment by soonoo** [comment]
> Does it mean doing yarn install && yarn build? I'm not a front-end expert, but I imagine that what ever is the output of your build process would need to be somehow integrated into the rqlite source. But I don't know, as this not my area of expertise.

That's right. html/css/javascript files need to be generated from source code before rqlite is built.  
Those generated files will be embedded into rqlite executable using [embed](https://pkg.go.dev/embed) package.

So `yarn install && yarn build` needs to be run somewhere in the deploy/release process, but I don't know where to put it.  
It would be helpful if you could point me to where to check look in this repository.

**Comment by otoolep** [comment]
Could you run your build process, and then make the output of that your file PR? Does that make sense?

**Comment by soonoo** [comment]
That's fine. I'll make a PR and request a review soon.

**Comment by otoolep** [comment]
https://rqlite.io/docs/ui/ -- two UI applications, one of which is open source and runs in the browser.

**Comment by Suleman-Elahi** [comment]
Here's my attempt at creating a webui for it: https://github.com/Suleman-Elahi/rqLui

I was using it for my internal use so I recreated it polished  it a bit and pushed it there.

~ps it's vibe coded.

**Comment by otoolep** [comment]
@Suleman-Elahi -- thanks for your contribution to the rqlite ecosystem.
