### ISSUE TITLE
Support other S3-like targets for auto backups

### ISSUE THREAD

**Issue by jtackaberry** [rqlite/rqlite#1560]
Currently rqlite is relatively opinionated about the target cloud storage for auto backups.  It precludes using S3-like storage backends that are S3 API compatible but don't exactly implement all of S3's behavior.

In my own personal case, this includes Minio and Wasabi.  In both cases, the endpoint doesn't include the bucket name, but rqlite currently (based on how it uses the AWS SDK) always prepends the bucket name to the endpoint, as is AWS's way.

So this FR is just to support S3-compatible APIs but be less opinionated about the endpoint.

I could submit a PR for this one, since I have the ability to test with at least Minio and Wasabi.

**Comment by otoolep** [comment]
Go for it, happy to review a PR.

**Comment by jtackaberry** [comment]
On the to-do list. I may also add some logging as well. Currently uploads are entirely silent unless they fail. :)

**Comment by otoolep** [comment]
Fixed on master.
