### ISSUE TITLE
Don't automatically backup to Cloud on startup

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#1565]
Started with https://github.com/rqlite/rqlite/issues/1561

**Comment by otoolep** [comment]
>This would allow skipping the entire dump/compression work in most cases.

It is skipped in most cases. Unless the "last modified" time of the underlying database files changes, the system no longer even calculates a checksum. It just skips uploading there and then.

https://github.com/rqlite/rqlite/blob/master/auto/backup/uploader.go#L154

https://github.com/rqlite/rqlite/blob/master/store/provider.go#L36

**Comment by jtackaberry** [comment]
> It is skipped in most cases. Unless the "last modified" time of the underlying database files changes, the system no longer even calculates a checksum. It just skips uploading there and then.

Aha, nice, thanks.  I guess the case that doesn't fall under "most cases" is when an rqlite node is restarted, becomes leader, and doesn't had have its lastUploadTime set?  So the restart case will do that potentially unnecessary dump?

Storing the sequence number (I guess "index" is the correct terminology with Raft?) as S3 metadata would close that gap, but given what you said above it's definitely much less useful/valuable than I thought, yeah.
