### ISSUE TITLE
Create Docker image (and add to Docker hub)

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#163]
Would be good to get this done. Would make testing and deployment so much easier.

**Comment by joeblew99** [comment]
same for me too. 
If you can make the actual volume mounted off the host as an option that also is useful.

**Comment by otoolep** [comment]
New repo created at https://github.com/rqlite/rqlite-docker

**Comment by otoolep** [comment]
The very first Docker image for rqlite is available via `docker pull rqlite/rqlite`. There is much to do, including documentation, but it's a start. Issues regarding the Docker image should be opened at https://github.com/rqlite/rqlite-docker
