### ISSUE TITLE
basic question: Can i replicate between WANS

### ISSUE THREAD

**Issue by joeblew99** [rqlite/rqlite#164]
Can i replicate between 2 raspberry Pis thats are in different locations, and not on the same Lan ?

I read a bit about this project and the protocol to the DB is HTTP, but is the protocol between the data bases also http or Web Sockets ? If it is then i could replicate it across WANS

thanks in advance.

**Comment by joeblew99** [comment]
looks like your maybe thinking along the sames lines ? I had to look :)
https://github.com/otoolep/global-rqlite

**Comment by otoolep** [comment]
Yes, you can. See the blog post below:

http://www.philipotoole.com/rqlite-v3-0-1-globally-replicating-sqlite/

The key is to use the '-httpadv' and `-raftadv` options so the nodes advertise a routable address over the WAN.
