### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by joeblew99** [rqlite/rqlite#165]
any chance on making benchmarks on updating the readme.

you know the factors that affect this better than me, but i am wanting to do replication in the same lan but also across WAN.

One other thing for me is what happens when the cross WAN network speed is slower than the write speed to the DB. You end up with a huge buffer or locked transactions ?

**Comment by otoolep** [comment]
You can some very basic numbers here:

http://www.philipotoole.com/rqlite-v3-0-1-globally-replicating-sqlite/

rqlite is fully replicated, synchronous system. Transactions don't travel across the network, but the committed commands do. I haven't done any significant testing, but you should get a few changes a second. More if you batch up.

https://github.com/rqlite/rqlite#performance

**Comment by otoolep** [comment]
Oh, I closed this because I don't plan to do any benchmarking at this time. The numbers on README are up-to-date, but very basic. :-)

If you want more detailed benchmarks, feel to specify exactly what should be tested and I can open a new ticket.
