### ISSUE TITLE
Support queries automatically timing out after X seconds

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#1657]
Offer this as a query parameter. I think the following C call could work:

https://sqlite.org/c3ref/interrupt.html

Start a timer in Go, and if it fires, call this C function on the connection.

**Comment by otoolep** [comment]
Ha, the underlying SQLite Go library already supports setting a timeout, and uses this method.

https://github.com/mattn/go-sqlite3/blob/4702d9b5d640f42488752f5cf70a195b748ffe96/sqlite3.go#L2071

Could be worth trying this out.

**Comment by mauri870** [comment]
I tried working on this and failed miserably. Maybe I'm trying to approach this the wrong way.

I implemented it in such a way that I can invoke [QueryContext](https://github.com/mauri870/rqlite/commit/b2d46800bbf041cf51fd03089acb8ad5ac36e248#diff-30c25f2a7d8ae335d2aada4b0a6013ad9d159595bb6a2a14b1d0022451b6753fR776) and [ExecContext](https://github.com/mauri870/rqlite/commit/b2d46800bbf041cf51fd03089acb8ad5ac36e248#diff-30c25f2a7d8ae335d2aada4b0a6013ad9d159595bb6a2a14b1d0022451b6753fR641) with a context.WithTimeout with the duration specified by the `sql_timeout` query parameter. Even tho the context reached the deadline those functions fail to return an error for it.

Any clues on what should be the proper way to implement this?

**Comment by otoolep** [comment]
Can you show me your code?

**Comment by mauri870** [comment]
Sorry, I forgot to add the link to my reply, here it is

https://github.com/rqlite/rqlite/compare/master...mauri870:rqlite:feature/sql-timeout

**Comment by otoolep** [comment]
>Even tho the context reached the deadline those functions fail to return an error for it.

You mean the deadline doesn't expire? If I was you I would focus on writing a db-level unit test first, to prove to yourself it works/doesn't work and debug that. You are on the right track, as I too believe it'll be a new field in the `command.Request` proto.

But focus on getting it working at the DB level solely via unit tests. And perhaps just focus on `db.Query` to start. Show me that failing.

**Comment by mauri870** [comment]
Thanks, I'll try that

**Comment by mauri870** [comment]
I added a test here https://github.com/rqlite/rqlite/compare/master...mauri870:rqlite:feature/sql-timeout. I can confirm with the debugger that the context is indeed set properly with the deadline from context, but ExecContext does not respect that. I would expect a context.DeadlineExceeded to be returned.

**Comment by otoolep** [comment]
I'm not sure I'm convinced by that test. That creation will run so fast, maybe it will return before runtime checks the timer, I don't know. Not saying the creation will take shorter than 1 nanosecond, just questioning in the runtime is good enough. Maybe you know.

I think a better test is to create 10,000 rows in the database, perhaps with a fair chunk of data, and perform some slow query (say a few hundred milliseconds) and also set your 1 nanosecond time. Then I think we've got something.

Have you checked the tests in the SQLite driver itself (mattn), to see if they test this?

**Comment by otoolep** [comment]
Re-opening until I figure out why the integration test for this functionality is failing.

https://github.com/rqlite/rqlite/pull/1669

**Comment by otoolep** [comment]
The system testing helped improve this feature, I think we're good shape now. Thanks again @mauri870
