### ISSUE TITLE
Can't create a empty database in rqlite shell

### ISSUE THREAD

**Issue by gvsafronov** [rqlite/rqlite#1707]
Hi, Team! 

I'm running rqlite version  8.22.0 as a single node, and I have one trouble.

1. First, I'm running rqlited the follow command:

georg@staut ~$ ./rqlited -node-id 1 ~/node.1

2. In the new tab in my terminal, I run rqlite:

georg@staut ~$ ./rqlited 

3. In the next step I loading rqlite shell

127.0.0.1:4001> 

3. And then I try to create a new empty database and see the next error:

127.0.0.1:4001> CREATE DATABASE myblog;
Error: near "DATABASE": syntax error

I was waiting for a new empty database to be created.

Please, tell me, what I'm doing wrong?

Best regards, 
Grigoriy Safronov

**Comment by otoolep** [comment]
That is not SQLite syntax. There is no `CREATE DATABASE` in SQLite. Review https://www.sqlite.org/lang.html for full information on SQLite syntax.

**Comment by otoolep** [comment]
From https://rqlite.io/docs/cli/
```
127.0.0.1:4001> CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT)
0 row affected
127.0.0.1:4001> INSERT INTO foo(name) VALUES("fiona")
1 row affected
127.0.0.1:4001> SELECT * FROM foo
+----+-------+
| id | name  |
+----+-------+
| 1  | fiona |
+----+-------+
127.0.0.1:4001> quit
bye~
```

**Comment by gvsafronov** [comment]
Thank you very much! I figured it out.
Rqlite fully supports SQLite syntax.
