### ISSUE TITLE
failed to install snapshot

### ISSUE THREAD

**Issue by dwco-z** [rqlite/rqlite#1711]
**What version are you running?**
8.22.1

**Are you using Docker or Kubernetes to run your system?**
No

**Are you running a single node or a cluster?**
3-nodes cluster

**What did you do? **What did you expect to happen? **What happened instead?******
I have a test case whose pseudo-algorithm is:

1. 	Start a three-nodes in parallel, all voters (using bootstrap to form the cluster)
2. 	Continuously hit /readyz?sync&timeout=5s of each rqlite instance until everything returns "ok" or timeout (500ms interval between /readyz calls)
3. 	Stop all three nodes
4. 	Set peers configuring all three nodes as voters (nothing changed, just testing peers functionality)
5. 	Start each node again
6. 	Continuously hit /readyz?sync&timeout=5s for multiple times until everything returns "ok" or timeout

This test has been running for a few months without issues. However, after upgrading from 8.16.6 to 8.22.1 and adding the sync flag, this test case has now become flaky. Sometimes one of the nodes will present a recurring snapshot issue after the second start. For now I just removed the sync flag and until now I couldn't reproduce the issue.

Cluster details:
  -node-id "127.0.0.1:8101" -http-addr "127.0.0.1:7101" -raft-addr "127.0.0.1:8101" (prefix 'Node1' in the logs)
  -node-id "127.0.0.1:8102" -http-addr "127.0.0.1:7102" -raft-addr "127.0.0.1:8102" (prefix 'Node2' in the logs)
  -node-id "127.0.0.1:8103" -http-addr "127.0.0.1:7103" -raft-addr "127.0.0.1:8103" (prefix 'Node3' in the logs)

Logs and more details: https://gist.github.com/dwco-z/352037cbc49a2ff43919144db0112dbc

**Comment by otoolep** [comment]
Thanks for the report. Some questions.

- In step 3, how do you stop the nodes?
- You mean you are executing the "Recovery Process"? By setting the peers.json file? But nothing is actually different in peers.json?

You mean that by adding the `sync` flag you sometimes get the log output you added in the gist?

**Comment by dwco-z** [comment]
> In step 3, how do you stop the nodes?

Sending a ctrl+c signal to stop gracefully

>You mean you are executing the "Recovery Process"? By setting the peers.json file? But nothing is actually different in peers.json?

Exactly, I'm testing the recovery functionality by setting the peers.json, but nothing is actually different (no suffrage change, no removal or addition)

> You mean that by adding the sync flag you sometimes get the log output you added in the gist?

Yes.

**Comment by otoolep** [comment]
OK, when you get this into this state again can I see a full, recursive directory listing of the data directory on each node?

**Comment by dwco-z** [comment]
├───127.0.0.18101
    │   │   db.sqlite
    │   │   db.sqlite-shm
    │   │   db.sqlite-wal
    │   │   raft.db
    │   │
    │   ├───raft
    │   │       peers.info
    │   │
    │   └───rsnapshots
    │       │   3-3-1709231804147.db
    │       │
    │       └───3-3-1709231804147
    │               meta.json
    │
    ├───127.0.0.18102
    │   │   db.sqlite
    │   │   db.sqlite-shm
    │   │   db.sqlite-wal
    │   │   raft.db
    │   │
    │   ├───raft
    │   │       peers.info
    │   │
    │   └───rsnapshots
    │       │   4-4-1709231801294.db
    │       │
    │       └───4-4-1709231801294
    │               meta.json
    │
    └───127.0.0.18103
        │   db.sqlite
        │   db.sqlite-shm
        │   db.sqlite-wal
        │   raft.db
        │
        ├───raft
        │       peers.info
        │
        └───rsnapshots
            │   3-3-1709231801184.db
            │
            └───3-3-1709231801184
                    meta.json

**Comment by otoolep** [comment]
Is that the state of the directories while the nodes are emitting "system cannot find the path specified" messages?

**Comment by otoolep** [comment]
Is your cluster also getting write traffic during this time?

**Comment by otoolep** [comment]
It's hard to believe the `sync` flag could be the cause. It's purely a read operation -- it waits until one variable in the Raft system is equal to, or greater, than another variable in the Raft system. There is no writes, and the variables in question do not grab locks (not at the rqlite level).

**Comment by otoolep** [comment]
One hypothesis I have is that writes are taking place on your cluster, while the recovery is in progress. This could cause the behaviour you are seeing.

**Comment by dwco-z** [comment]
> Is that the state of the directories while the nodes are emitting "system cannot find the path specified" messages?

Yes

**Comment by dwco-z** [comment]
> Is your cluster also getting write traffic during this time?

No. The only steps being conducted are the ones I mentioned, which means the database is not even populated, it is quite a simple start-stop-configure_peers-start test where during the each node's start I'm monitoring the readyz output with the sync flag. This is the database in the broken state: 
[TestDatabase.zip](https://github.com/rqlite/rqlite/files/14460448/TestDatabase.zip)
I tried again reproducing the issue removing the sync flag but I coudn't, maybe it is the determining factor or makes it really rare to cause the issue.

**Comment by otoolep** [comment]
OK, using the sync flag might change the timing of the whole sequence, so it's possible it affects the test output, but it's difficult to see how it's a direct cause.

How reproducible is this for you?

**Comment by dwco-z** [comment]
When I initiate a Run Until Failure, simetimes it fails in the second attempt, simetimes in the 16th attempt, it varies. I just managed to port this scenario I was describing to python and I was able to hit the issue. I put in the "rqlite-8.22.1-issue" branch => https://github.com/dwco-z/rqlite-throubleshooting/tree/rqlite-8.22.1-issue
I have also uploaded the logs (node1.log, node2.log and node3.log)

**Comment by otoolep** [comment]
What version of Python are you running? I could execute your repo last time, but not this time.

I'm running Python 3.8.10

```
$ python3 main.py 
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
starting rqlited...
starting rqlited...
starting rqlited...
stopping rqlited...
stopping rqlited...
stopping rqlited...
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    start_all_instances(all_instances, joinAddresses)
  File "main.py", line 55, in start_all_instances
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 49, in start_manager
    manager.start_rqlited(joinAddresses)
  File "/home/philip/repos/rqlite-throubleshooting/rqlite_manager.py", line 47, in start_rqlited
    self.process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
AttributeError: module 'subprocess' has no attribute 'CREATE_NEW_PROCESS_GROUP'
```

**Comment by otoolep** [comment]
Runs if I patch like so:
```
$ git diff rqlite_manager.py
diff --git a/rqlite_manager.py b/rqlite_manager.py
index f4cb3c8..00e6860 100644
--- a/rqlite_manager.py
+++ b/rqlite_manager.py
@@ -31,7 +31,7 @@ class RqliteManager:
     def start_rqlited(self, join_addresses=""):
         print('starting rqlited...')
         cmd = [
-            "rqlited.exe",  # Path to the rqlited executable
+            "/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/cmd/rqlited/rqlited",  # Path to the rqlited executable
             f"-http-addr={self.host}:{self.http_port}",
             f"-raft-addr={self.host}:{self.raft_port}",
             f"-raft-log-level=DEBUG",
@@ -44,7 +44,7 @@ class RqliteManager:
             cmd.insert(-2, "-join=" + ",".join(join_addresses))
         # print(cmd)
         # exit()
-        self.process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
+        self.process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
 
         # Start a thread to asynchronously log stdout to a file
         self.log_thread = threading.Thread(target=self._log_stdout, daemon=True)
@@ -59,7 +59,7 @@ class RqliteManager:
     def stop_rqlited(self):
         print('stopping rqlited...')
         if self.process:
-            self.process.send_signal(signal.CTRL_BREAK_EVENT)
+            self.process.send_signal(signal.SIGTERM)
             try:
                 self.process.wait(30)
             except:
```

**Comment by otoolep** [comment]
Nice, I seem to have hit it -- good stuff.

**Comment by dwco-z** [comment]
> What version of Python are you running? I could execute your repo last time, but not this time.
> 
> I'm running Python 3.8.10
> 
> ```
> $ python3 main.py 
> /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (3.0.4) doesn't match a supported version!
>   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
> starting rqlited...
> starting rqlited...
> starting rqlited...
> stopping rqlited...
> stopping rqlited...
> stopping rqlited...
> Traceback (most recent call last):
>   File "main.py", line 82, in <module>
>     start_all_instances(all_instances, joinAddresses)
>   File "main.py", line 55, in start_all_instances
>     future.result()
>   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
>     return self.__get_result()
>   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
>   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "main.py", line 49, in start_manager
>     manager.start_rqlited(joinAddresses)
>   File "/home/philip/repos/rqlite-throubleshooting/rqlite_manager.py", line 47, in start_rqlited
>     self.process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
> AttributeError: module 'subprocess' has no attribute 'CREATE_NEW_PROCESS_GROUP'
> ```

I'm using Python 3.12 this time

**Comment by dwco-z** [comment]
> Nice, I seem to have hit it -- good stuff.

Great

**Comment by otoolep** [comment]
I believe https://github.com/rqlite/rqlite/pull/1714 will fix this.

**Comment by otoolep** [comment]
I do not see anything particularly different between earlier versions and 8.22. Start-up timing may have changed, which brought out this issue in later releases. Basically there was an extra call to "snapshot reap" and it was in the problematic place -- that was a bug which you were hitting occasionally.

Thanks for the Python script -- made it very easy to repro.

**Comment by dwco-z** [comment]
Oh that's interesting, I throught it could be something with new code. Thanks! I'm glad the script helped, I really appreciate your prompt action handling this issue. I'll test the most recent version and I'll let you know if something comes up.

**Comment by dwco-z** [comment]
@otoolep I downloaded the 8.22.2 artifact and started using it. I noticed that the the issue is still occurring on my environment.  I put the executable in that python 'rqlite-throubleshooting' repository and I could get the "Exception: something is wrong, leader is not ready..." there as well in the 19th attempt, and then in the 2nd attempt.

```
MD5 hash of .\rqlited.exe:
23e93ae49e554ef691c6514165b4a7c5
```

**Comment by otoolep** [comment]
I can't run Windows binaries.

Is this still the same issue? Are you saying that if I run your script I'll still see the same issue as you initially reported?

**Comment by otoolep** [comment]
OK, I see the logs. This appears to be a different issue. It may have a similar root cause, but the failure is happening at a different place in the start-up sequence (the logs show this). I'll need to look into this, could be a few days before I make any progress.

**Comment by dwco-z** [comment]
Ok, if you need me to test a change or something else, just let me know. Thanks!
