### ISSUE TITLE
Rust sqlx-rqlite

### ISSUE THREAD

**Issue by HaHa421** [rqlite/rqlite#1726]
I just published sqlx-rqlite at https://github.com/HaHa421/sqlx-rqlite and on crates.io to enable rqlite(rqlite.io) in sqlx.
Basic functionnalities are working, you can check simple and simple_chrono examples.

**Comment by otoolep** [comment]
Thanks for your contribution, I added a link to https://rqlite.io/docs/api/client-libraries/
