### ISSUE TITLE
Which version of Sqlite dialect is supported?

### ISSUE THREAD

**Issue by tolgaulas** [rqlite/rqlite#1734]
I've just installed the recent version for testing, the below dialect (latest sqlite3) was not supported I guess since the records in the listreceiver (with Foreign key, delete cascade) remained when i delete the records from the receiver table.  (Single node)

```sql
CREATE TABLE listreceiver (
  list_rowid TEXT NOT NULL,
  receiver_rowid TEXT NOT NULL,
  combined TEXT GENERATED ALWAYS AS ('R' || list_rowid || '-' || 'L' || receiver_rowid) STORED,
  PRIMARY KEY (list_rowid, receiver_rowid)
  FOREIGN KEY (receiver_rowid) REFERENCES receiver(rowid) ON DELETE CASCADE,
  FOREIGN KEY (list_rowid) REFERENCES list(rowid) ON DELETE CASCADE
);
```

**Comment by otoolep** [comment]
Yes, that is correct. You can see the version rqlite runs in the start-up logs, and well as the output from `/status`.

Did you enable Foreign Keys? They are off by default in SQLite.
