### ISSUE TITLE
PRAGMA foreign_keys are turning them off even we turn them on. 

### ISSUE THREAD

**Issue by tolgaulas** [rqlite/rqlite#1735]
**What version are you running?**
8.23.0

**Are you using Docker or Kubernetes to run your system?**
No

**Are you running a single node or a cluster?**
Single

**What did you do?**
Ran `PRAGMA foreign_keys=on` and ran `PRAGMA foreign_keys;` to be sure it's on. it was on.. Then waited a few seconds then ran the `PRAGMA foreign_keys;` again and it showed me foreign_keys were off.
**What did you expect to happen?**
The foreign_keys to remain on. 
**What happened instead?**
Foreign_keys are turning them self off..

**Comment by otoolep** [comment]
I know why this is happening, and make it clearer in the docs. 

However, the best way to enable Foreign Keys in rqlite is via a flag at launch time, like so:

`rqlited -fk node1`

Try that for now, and let me know how it goes.
