### ISSUE TITLE
[FeatureRequest] Make number of retries configurable for /nodes and potentially other relevant http calls

### ISSUE THREAD

**Issue by dwco-z** [rqlite/rqlite#1756]
**Is your feature request related to a problem? Please describe.**
Currently rqlite uses defaultMaxRetries(8) during GetNodeAPIAddr on the cluster client. Considering that unreachable nodes like shutdown rqlite instances will keep failing during the first + 8 retry attempts, having the option to configure this number of retries and possibly decrease it might be useful to avoid having too many retries being ineffectively executed.

**Describe the solution you'd like**
A possible solution could be making the defaultMaxRetries configurable

**Comment by otoolep** [comment]
I may just start by setting the default retry value to 0. This is the second issue that's been filed about the retry behavior, so I think it's time to start removing default retries. It's always been an implementation detail, so I wouldn't consider it a breaking change.

**Comment by otoolep** [comment]
I do plan to allow is to be set on a request-by-request basis, but may just change the default to 0 to see if tests still pass.

**Comment by dwco-z** [comment]
> I do plan to allow is to be set on a request-by-request basis, but may just change the default to 0 to see if tests still pass.



> I may just start by setting the default retry value to 0. This is the second issue that's been filed about the retry behavior, so I think it's time to start removing default retries. It's always been an implementation detail, so I wouldn't consider it a breaking change.

Right, take makes sense and it would help with my issue

**Comment by otoolep** [comment]
@dwco-z -- this is now fixed on master. You will get zero retries without doing anything, but can add `retries=N` to your request (as a query parameter) where `N` is an integer.

**Comment by otoolep** [comment]
I can make a build, but perhaps you just want to build master to check it out.

**Comment by dwco-z** [comment]
Sure, I'll build master to test it
