### ISSUE TITLE
Multiple issues with snapshot process

### ISSUE THREAD

**Issue by dwco-z** [rqlite/rqlite#1774]
**What version are you running?**
8.23.3

**Are you using Docker or Kubernetes to run your system?**
No, windows virtual machines

**Are you running a single node or a cluster?**
Cluster details: 3-nodes cluster, all voters, each node runs in a different windows virtual machine.
First node - NodeID: 192.168.15.99 
Second node - NodeID: 192.168.15.111
Third node - NodeID: 192.168.15.44

**Issue**
I got a rqlite cluster into a failing state (snapshot issues) and I couldn't get one of the nodes to a working state even after performing recovery.

Context:
I have a three-nodes cluster running in three separate virtual machines that I left running for the last days without interacting with them.  Although I never shutdown the virtual machines, usually I shutdown the machine hosting the VMs roughly around 5pm and I turn on the host machine the next morning. Recently, I noticed that some of the machines might not come up running after turning on the host machine, so I might need to manually start the VM again.

For the time being all I have are truncated logs and I can also share the directory tree structure encompassing all nodes. I extracted a portion of the logs of each rqlite instance going from yesterday around 4pm when issues started happening until today. The logs of the node 192.168.15.44 only started to be written today, so this windows virtual machine probably went to sleep since yesterday and I haven't noticed until today that it was offline. I should also add that I haven't interacted with the system that uses the rqlite database for at least three days, although I can confirm that the rqlite cluster receives a /execute request every 5 seconds while there is quorum.

Based on the logs I'm sending, you can see that snapshot issues are present in the logs of node 192.168.15.111, starting around 2024/05/02 16:04:01. The snapshot failures are constantly triggered until I shutdown the host computer yesterday around 5pm. Then, today as the machines went online, a few minutes later I noticed that something was wrong and I tried a recovery around 10:31  (peers.json listing the three nodes, all voters, no change).
I can see that the recovery was successful on machines 192.168.15.99 and 192.168.15.44:

```
192.168.15.99 => [store] 2024/05/03 10:31:24 node recovered successfully using C:\ProgramData\Test\Server\Database\Global\raft\peers.json
192.168.15.44 => [store] 2024/05/03 10:31:19 node recovered successfully using C:\ProgramData\Test\Server\Database\Global\raft\peers.json
```

However, the machine which the snapshot issues (192.168.15.111) still continue to present errors, although the error message changed to:
	`[rqlited] 2024/05/03 10:31:20 failed to open store: failed to create snapshot store: check failed: previous snapshot data is not a SQLite file: 4252-1015713-1714742891553`

[Node192.168.15.44.txt](https://github.com/rqlite/rqlite/files/15203891/Node192.168.15.44.txt)
[Node192.168.15.99.txt](https://github.com/rqlite/rqlite/files/15203892/Node192.168.15.99.txt)
[[Failure]Node192.168.15.111.txt](https://github.com/rqlite/rqlite/files/15203893/Failure.Node192.168.15.111.txt)
[directory-tree.txt](https://github.com/rqlite/rqlite/files/15203894/directory-tree.txt)

**Comment by otoolep** [comment]
From looking the logs it wouldn't surprise me if the PR fixes the entire issue -- and that we're just looking at a single issue here. I'll almost certainly merge the PR -- it addresses a real issue.

@dwco-z -- just let me know if your cluster continues to operate OK with this PR in place.

**Comment by otoolep** [comment]
This is the sequence of events, as I see it (from the log for the failing node).

The failing node can't contact the other node, for whatever reason (it's down):

`[raft] 2024/05/02 16:04:00 [DEBUG] failed to contact: server-id=192.168.15.44 time=7h39m10.9657273s`

It'a trying to stream a snapshot to it (again, for what is probably a perfectly fine reason).

Writes are occurring in parallel, so eventually the node tries to perform a snapshot:

`[store] 2024/05/02 16:04:01 incremental snapshot created in 11.9484ms on node ID 192.168.15.111`

but this snapshotting process fails to complete ("close") because the streaming operation above is in progress and holding an open file handle to the SQLite database in the Snapshot store -- and an incremental snapshot needs to rename that SQLite file.

```
[raft] 2024/05/02 16:04:01 [ERROR] failed to take snapshot: error="failed to close snapshot: rename C:\ProgramData\Test\Server\Database\Global\rsnapshots\4251-1013890-1714675769632.db C:\ProgramData\Test\Server\Database\Global\rsnapshots\4251-1014226-1714676641064.db: The process cannot access the file because it is being used by another process."
```

It just gets worse from there.

So the change in the linked PR will prevent a streaming operation, and a snapshot operation, from running concurrently. Either one or the other will run to completion (or fail) before the other can start.

**Comment by otoolep** [comment]
@dwco-z -- I'm pretty certain this is now fixed on master. Of course, if you hit the issue again, please re-open the bug (or file a new one).

Thanks very much for the report! I had overlooked this possibility, and you may have been the first to hit it. At least it's not easily spotted on Linux.

**Comment by dwco-z** [comment]
> This is the sequence of events, as I see it (from the log for the failing node).
> 
> The failing node can't contact the other node, for whatever reason (it's down):
> 
> `[raft] 2024/05/02 16:04:00 [DEBUG] failed to contact: server-id=192.168.15.44 time=7h39m10.9657273s`
> 
> It'a trying to stream a snapshot to it (again, for what is probably a perfectly fine reason).
> 
> Writes are occurring in parallel, so eventually the node tries to perform a snapshot:
> 
> `[store] 2024/05/02 16:04:01 incremental snapshot created in 11.9484ms on node ID 192.168.15.111`
> 
> but this snapshotting process fails to complete ("close") because the streaming operation above is in progress and holding an open file handle to the SQLite database in the Snapshot store -- and an incremental snapshot needs to rename that SQLite file.
> 
> ```
> [raft] 2024/05/02 16:04:01 [ERROR] failed to take snapshot: error="failed to close snapshot: rename C:\ProgramData\Test\Server\Database\Global\rsnapshots\4251-1013890-1714675769632.db C:\ProgramData\Test\Server\Database\Global\rsnapshots\4251-1014226-1714676641064.db: The process cannot access the file because it is being used by another process."
> ```
> 
> It just gets worse from there.
> 
> So the change in the linked PR will prevent a streaming operation, and a snapshot operation, from running concurrently. Either one or the other will run to completion (or fail) before the other can start.

Thanks for the detailed explanation, made it very clear
