### ISSUE TITLE
Support paging of results

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#179]
It might make sense for rqlite to support paging of results such that something like `SELECT * FROM foo` would only return a certain amount of a results at once. This might prevent against very high memory usage, which could be an issue on nodes with small amounts of RAM.

Perhaps. This needs research.

**Comment by otoolep** [comment]
That said, it may be better to leave this to the user, through `LIMIT` and `SORT'.

**Comment by raindog308** [comment]
I think this would be a radical shift from the stateless model.  You'd have to keep state for each open transaction in the DB, cache, etc.

I might request results 1-1000, fetch 1-100, and another user deletes 200-250.  Or I request 1-1,000,000, fetch 1000 and then go on vacation.  If sqlite supported this kind of paging it would be one thing but as-is I think this would be very difficult to implement.

Of course, it'd be awesome if you did.

**Comment by otoolep** [comment]
Don't plan to do this.
