### ISSUE TITLE
Add Windows CI support for rqlite (appveyor?)

### ISSUE THREAD

**Issue by lygstate** [rqlite/rqlite#180]
I suggest using appveyor for it

**Comment by otoolep** [comment]
https://blog.markvincze.com/setting-up-an-appveyor-pipeline-for-golang/

**Comment by otoolep** [comment]
Trying to bring it online here:

https://github.com/rqlite/rqlite/pull/181

Any advice to solve the gcc issue is welcome. I'm not a Windows person.

**Comment by otoolep** [comment]
https://github.com/mattn/go-sqlite3/issues/214 seems relevant.

This is not something I plan to work on any time soon, if at all. If anyone would like to create an appveyor.yml that works for rqlite, I'll definitely try it out.

**Comment by otoolep** [comment]
The only way I'm going to get this to work is if someone forks rqlite, and generates an `appveyor.yml` file that actually works. I am unable to work on it personally, but would be happy to merge a working PR.

**Comment by otoolep** [comment]
Thank you @lygstate
