### ISSUE TITLE
SELECT MAX() or COUNT() fail on big tables

### ISSUE THREAD

**Issue by softwaremarkdahl** [rqlite/rqlite#1802]
**What version are you running?**
8.25

**Are you using Docker or Kubernetes to run your system?**
NO

**Are you running a single node or a cluster?**
CLUSTER

**What did you do?**
1. executed query "SELECT MAX(rowid) FROM table;"
2. executed query "SELECT MAX(timestamp) FROM table;" (timestamp is indexed)
3. executed query "SELECT COUNT(timestamp) FROM table;" (timestamp is indexed)
4. executed query "SELECT COUNT(1) FROM table;"

**What did you expect to happen?**
to get the max/count values

**What happened instead?**
on small table (~400 rows):
1, 2, 3, 4: value returned

on big tables (~200million rows):
1, 2, 3: immediately returns "ERR! database disk image is malformed"
4: after some seconds returns "ERR! database disk image is malformed"

**Comment by otoolep** [comment]
I"m going to need more details on this:

- does this happen when running a single node?
- are writes happening on your cluster when the error occurs?
- have you added any rows since booting your cluster (presumably that's what you did).
- can I see your schema?

**Comment by otoolep** [comment]
When this happens show me the output of /debug/vars and /status

https://rqlite.io/docs/guides/monitoring-rqlite/

**Comment by otoolep** [comment]
You can also examine the SQLite file underneath rqlite directly in your data directory. Shutdown SQLite graacefully and query the SQLite database directly. Do you see the same issue?

**Comment by softwaremarkdahl** [comment]
I'm trying to boot again from scratch, I thought maybe the imported database was in use... I'll let you know asap. Thanks

**Comment by softwaremarkdahl** [comment]
It's working, the imported db was actually damaged. Sorry for having opened an unneeded issue

**Comment by otoolep** [comment]
It happens, just glad it wasn't a bug in rqlite.
