### ISSUE TITLE
Support for streaming BLOB I/O

### ISSUE THREAD

**Issue by brunovivas** [rqlite/rqlite#1803]
SQLite supports [incremental I/O to BLOBs](https://www.sqlite.org/c3ref/blob_open.html), i.e., the capability to stream reads and writes to blobs without having to load the entire blob into memory first. As far as I could find, rqlite does not currently support this feature out of the box. I think it would be nice if it were possible to do this for projects where images are served directly from rqlite nodes (such as [nordeltaprop-backend](https://github.com/like/nordeltaprop-backend) by @lukks)

**Comment by LuKks** [comment]
We plan to do a `blob` table where we append chunks of files so that we can write/read in chunks manually (with some optimizations on top like prefetching), so fortunately this issue won't stop us to continue using RQLite
