### ISSUE TITLE
Write through rqlite, read through sqlite - issues

### ISSUE THREAD

**Issue by nielspeen** [rqlite/rqlite#1823]
I'm trying to write through rqlite while reading (suitable queries) directly using sqlite. Depending on how I configure this, I encounter one of two issues:

1. If I set the database files to read-only at the file system level (for the reader), 99.999% of my reads are successful. However, I occasionally get a write(!) error. It seems that sqlite requires write access, even in read-only mode: [SQLite Forum Post](https://sqlite.org/forum/forumpost/8784c7deb9847215).
2. If I make the database files writable for the reader, I quickly encounter 'image malformed' issues.

To mitigate these issues, I am currently retrying my reads, as they usually succeed just milliseconds later.

I'm unsure how to proceed from here. I don't know if rqlite can prevent the issue described in the forum post, or why the database becomes deformed when allowing the read-only reader write access.

**Comment by otoolep** [comment]
If you supply more details on your database schema and queries I might be able to help but at the end of the day directly reading the SQLite file is not officially supported. I could well believe you hit occasional errors as rqlite manipulates the SQLite database is ways that other readers may not like. 
So if you can give more details we might be able to make it bette. 


Sent from Yahoo Mail for iPhone


On Friday, June 28, 2024, 1:26 PM, Niels Peen ***@***.***> wrote:




I'm trying to write through rqlite while reading (suitable queries) directly using sqlite. Depending on how I configure this, I encounter one of two issues:
   
   - If I set the database files to read-only at the file system level (for the reader), 99.999% of my reads are successful. However, I occasionally get a write(!) error. It seems that sqlite requires write access, even in read-only mode: SQLite Forum Post.
   - If I make the database files writable for the reader, I quickly encounter 'image malformed' issues.

To mitigate these issues, I am currently retrying my reads, as they usually succeed just milliseconds later.

I'm unsure how to proceed from here. I don't know if rqlite can prevent the issue described in the forum post, or why the database becomes deformed when allowing the read-only reader write access.

**Comment by nielspeen** [comment]
Thanks. I appreciate the offer! However, if it's not a supported use-case I prefer to change my app instead.
