### ISSUE TITLE
Cast bootstrap-expect (and node-id) to string when it's a number to prevent breaking containers created via the docker API

### ISSUE THREAD

**Issue by joostdecock** [rqlite/rqlite#1835]
First up: I am not certain that you _want_ this as a feature request. 
Part of the reason I am creating this is to help others who might run into the same problem. So feel free to close this.

**Is your feature request related to a problem? Please describe.**

When starting an rqlite Docker container via the Docker API (rather than the command line) using a number as either `node-id` or `bootstrap-expect` fails with the following error:

```
json: cannot unmarshal array into Go struct field ContainerConfigWrapper.Cmd of type string
```

The issue is in the `Cmd` section of the container config (only relevant parts shown):

```json
{
  "name":"db",
  "Image":"rqlite/rqlite:8.26.7",
  "Cmd":[
    "rqlite",
    "-node-id",
    1,
    "-http-addr=host1:4001",
    "-raft-addr=host1:4002",
    "-bootstrap-expect",
    3,
    "-join",
    "$HOST1:4002,$HOST2:4002,$HOST3:4002",
    "data"
  ]
}
```
To fix it, all one has to do is replace the numbers with strings:

```diff
 "Cmd":[
    "rqlite",
    "-node-id",
-    1,
+.  "1",
    "-http-addr=host1:4001",
    "-raft-addr=host1:4002",
    "-bootstrap-expect",
-    3,
+.  "3",
```

A careful reading of [the documentation](https://rqlite.io/docs/clustering/general-guidelines/) does indeed state that node-id must be a string:

> *`-node-id` can be any string, as long as it’s unique for the cluster*

But for bootstrap-expect, there's no doubt it's a number:

> *-bootstrap-expect should be set to the number of nodes that must be available before the bootstrapping process will commence, in this case 3.*

The given examples hinge on the shell casting these fields to strings:

```sh
rqlited -node-id 1 -http-addr=$HOST1:4001 -raft-addr=$HOST1:4002 \
-bootstrap-expect 3 -join $HOST1:4002,$HOST2:4002,$HOST3:4002 data
```

That is fine for the majority of cases.
But when not using the Docker CLI but the Docker API, passing a number will cause the error above.

This is a minor footgun in the case of `node-id`, and somewhat counter-intuitive for `bootstrap-expect`.

**Describe the solution you'd like**

Perhaps you could detect that node-id is a number and cast it to a string.

**Describe alternatives you've considered**

Alternatively, update the documentation to make it clear it is a string:

```sh
rqlited -node-id "1" -http-addr=$HOST1:4001 -raft-addr=$HOST1:4002 \
-bootstrap-expect "3" -join $HOST1:4002,$HOST2:4002,$HOST3:4002 data
```

But that feels a bit clunky.

Once again, feel free to close. Just wanted to document this in case others stumble upon the same issue.

**Comment by joostdecock** [comment]
Almost forgot: If you do want to make either change (docs or casting to string) I am happy to submit a pull request for either.

**Comment by joostdecock** [comment]
Update #2: The exact same issue applies to `-bootstrap-expect` which is arguably more problematic as that one is a number. From the docs:

> *-bootstrap-expect should be set to the number of nodes that must be available before the bootstrapping process will commence, in this case 3.*

I will update the issue accordingly.

**Comment by otoolep** [comment]
Thanks for the report. However I don't understand how changing rqlite source code can fix this. Is the error an error from the Docker API?

**Comment by otoolep** [comment]
>Perhaps you could detect that node-id is a number and cast it to a string.

This is the part I don't understand. My mental model of what you are seeing is that all these issues occur *before* anything is passed to `rqlited`. Therefore I don't understand how I can address.

**Comment by joostdecock** [comment]
Please forgive me, I saw the Golang error and presumed it was coming from rqlite, when in fact, it comes from the Docker daemon.

Love rqlite by the way, can't thank you enough for your work on this 🙏   

closing
