### ISSUE TITLE
How to disable TLSV1.0&1.1 and config cipher suite

### ISSUE THREAD

**Issue by MaJiangZh** [rqlite/rqlite#1840]
Hi there,
I am using rqlite-7.21.4 in my project. Vulnerability scanning shows that this current version supports TLSv1.0&1.1 and has problems with SWEET32(SSL Medium Strength Cipher Suite Supported). 
Anyone who know how can I solve these two problems? Is there any configuration item to configured not to support tls1011 and configure different cipher suites? 

Plaease tell me,thanks a lot.

**Comment by otoolep** [comment]
Show me how you detect this, because that version should not support those TLS versions unless you explicitly enable it.

https://github.com/rqlite/rqlite/blob/v7.21.4/cmd/rqlited/flags.go#L448

**Comment by otoolep** [comment]
Any response here? If not I will close the issue.
