### ISSUE TITLE
Timeout Issue with rqlite in Multi-Instance Setup

### ISSUE THREAD

**Issue by rathish1601** [rqlite/rqlite#1886]
**What version are you running?**

 v8.26.6_

**What Operating System are you running?**

Linux_

**Are you using Docker or Kubernetes to run rqlite?**

Docker

**Are you running a single node or a cluster?**

 cluster_

**What did you do?**

  We are facing timeout issues during insert/read operations when rqlite is running in a multi-instance setup. This problem is only occurring in multi-instance environments and is not present in single-instance configurations.

We will need your assistance in resolving this issue. Below are the error logs for reference:

operation: insert | Error=> AxiosError: timeout of 30000ms exceeded
    at ClientRequest.handleRequestTimeout (/usr/src/bot-runner/node_modules/axios/dist/node/axios.cjs:3066:16)
    at Object.onceWrapper (node:events:631:28)
    at ClientRequest.emit (node:events:517:28)
    at Socket.emitRequestTimeout (node:_http_client:847:9)
    at Object.onceWrapper (node:events:631:28)
    at Socket.emit (node:events:529:35)
    at Socket._onTimeout (node:net:598:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

**Comment by otoolep** [comment]
@rathish1601 -- can you provide a bug report with full details? You seem to have simply copied over the template without completing the answers (unless you are running exactly the same system as the suggestions in the template).

Can you answer the following:

- What version are you running?
- What operating system are you using?

A stack trace from your own code is of very little help, as it doesn't tell me anything about the traffic you're sending to the cluster. I need to know much more details about the types of traffic you're sending to the cluster, and what kind of reads you're doing. Can you provide example queries?

I also needs logs from the the node that you're attempting to make the request one. And the output from /debug/vars and /status.

**Comment by otoolep** [comment]
Which endpoint are you using for your writes? And are you using queued writes?

What size are your requests to rqlite?

**Comment by otoolep** [comment]
When I say "logs" I mean the logs from rqlite, not your logs.

**Comment by otoolep** [comment]
If you find that when you take all the load of the system the request still fails to return in 30 seconds, then send `SIGQUIT` to the `rqlited` process. That will generate a stack trace, and might help us figure out where it's stuck (assuming it is).

**Comment by rathish1601** [comment]
We are not using queued writes. As mentioned earlier, we are running rqlite in cluster mode with three instances of our docker containers running rqlite. Incoming requests are distributed across these containers.

Logs: We haven't noticed any suspicious errors in the rqlite logs, but we are monitoring them closely.
Replication Issue: We haven't been able to replicate this issue in our dev environment, but it is occurring in production.

Do you have any additional insights on when these types of timeout errors are most likely to occur?

**Comment by otoolep** [comment]
>Do you have any additional insights on when these types of timeout errors are most likely to occur?

As I mentioned above -- a bug or a load. See https://github.com/rqlite/rqlite/issues/1886#issuecomment-2341253069

We might be able to run out the bug by taking off the load, and then seeing if a write proceeds. 

Are the systems being monitored for load? Maybe the disks are hitting their limits.

**Comment by otoolep** [comment]
>Incoming requests are distributed across these containers.

Remember rqlite is a leader-based system. All writes eventually go through the Leader, so that's the key node to be monitoring. You need to check if there is any sign that the systems experiencing this issue are under load (RAM, CPU, disk).

**Comment by rathish1601** [comment]
Regarding your suggestion:

We haven't yet tried taking all the load off the cluster and issuing a single write request to a follower node. We will try this approach to see if the request succeeds.

**Comment by otoolep** [comment]
OK, you could start just by having your end-user giving you data about any load on the nodes.

**Comment by otoolep** [comment]
You can get a sense of the graphs and performance measurement I with rqlite:

https://www.philipotoole.com/rqlite-5-10-0-released-comparing-its-disk-usage-to-5-6-0/

What I would suggest you (or your end users) should be doing is measuring the request-processing time for their systems. What you're showing me is that a HTTP request is taking longer than 30 seconds to complete, and your client code seems to give up. So an important question is "is the timeout coming out of nowhere, and all requests up to that point completely quickly?" or "is the request response time slowing growing, until it finally hits 30 seconds?". That former might indicate a bug, the latter load.

**Comment by rathish1601** [comment]
I followed your suggestion to take all load off the cluster and generated a single write request to one of the follower nodes using the /db/execute endpoint. The data was inserted without any issues. I was able to verify the inserted data in the table afterward.

**Comment by otoolep** [comment]
But was that cluster failing to insert data before you took the load off? If so, that is a clue that it might be load related.

When you're seeing the issue, check the CPU, RAM, and disk usage of the nodes in your cluster, with particular attention being paid to Leader.

**Comment by rathish1601** [comment]
Currently, we're not observing any timeout issues with the instance, but we do see intermittent occurrences of this problem. We are actively monitoring the logs for any patterns or triggers that might be contributing to the timeout errors. When these errors occur, they result in failed database operations. Our goal is to identify the root cause through continuous monitoring and analysis to address the issue effectively.

**Comment by otoolep** [comment]
The logs are unlikely to show evidence of overloads, possibly snapshot times will go up. You should run with `-raft-log-level=INFO` to get richer logging.

You must monitor your systems, right now there is no evidence of a bug. There is some indication its caused by load. You could also increase your timeouts from 30 seconds to, say, 60 seconds, and see if the issue goes away. That way you know the writes are eventually getting through, and are not not stuck. Of course, if they do get through, 30+ seconds is still a long time to wait for a HTTP request to finish.

I do not know if you requests are large (multiple MBs?) maybe you could make them smaller. You could also try increasing the power of your nodes. Of course, until you tell me if your nodes are overloaded, I'm not sure if that would make a difference.

**Comment by otoolep** [comment]
Also, it's important to note that rqlite also has some internal timeouts and they also default to 30 seconds. So that 30 timeout you are hitting -- is that a timeout in your code, or something you're getting back from rqlite? It's not clear to me.

**Comment by otoolep** [comment]
You can control those timeouts by adding `timeout=60s` as a query parameter when doing your requests, which would make the internal timeouts be 60 seconds. E.g.

```bash
curl -XPOST 'localhost:4001/db/execute?timeout=60s' -H "Content-Type: application/json" -d '[
    "CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT, age INTEGER)"
]'
```

You can make the value any Go duration string you like.

**Comment by otoolep** [comment]
If you can, I would consider upgrading to 8.30.2. I've added some more metrics to that release, which count communication timeouts between nodes.

**Comment by otoolep** [comment]
Any more updates here? Without more information it will not be possible make progress.

**Comment by otoolep** [comment]
No response, closing.
