### ISSUE TITLE
Enhance http address check logic to prevent node join failures due to incorrect Content-Type

### ISSUE THREAD

**Issue by jackblack369** [rqlite/rqlite#1939]
version: v8.31.3

Currently, the logic for checking whether to use the HTTP address or the Raft address relies on the IsServingHTTP function, which executes a request using 
```go
func IsServingHTTP(addr string) bool {
	client := http.Client{
		Timeout: 2 * time.Second,
	}
	resp, err := client.Get("http://" + addr)
	if err == nil {
		resp.Body.Close()
		return true
	}
        ...
```

In some cases, the line `resp, err := client.Get("http://" + addr)` may return nil, even if the address is an raft address, which prevents the node from joining the cluster. 
To address this issue, need to add a check to verify if the response header Content-Type is either text/html or application/json. 
```go
func IsServingHTTP(addr string) bool {
	client := http.Client{
		Timeout: 2 * time.Second,
	}
	resp, err := client.Get("http://" + addr)
	if err == nil {
		defer resp.Body.Close()
		if resp.Header.Get("Content-Type") == "text/html" || resp.Header.Get("Content-Type") == "application/json" {
			return true
		}
	}
        ...
```
If the header does not match these values, we should proceed with the subsequent logic for using the Raft address.

**Comment by otoolep** [comment]
Thanks for the report.

>In some cases, the line resp, err := client.Get("http://" + addr) may return nil, even if the address is an raft address,

Which cases, exactly? Tightening up the test sounds good, but I'd like to understand better why it needs to happen.

**Comment by otoolep** [comment]
Making some improvements to the checker code here: https://github.com/rqlite/rqlite/pull/1940

I would still like to know precisely how `Get` can get back `nil` when not talking to a HTTP server before I make any further changes however.

**Comment by jackblack369** [comment]
Below is a detailed description of the issue:

I started rqlite **Node 1** using the following command on the `172.20.7.232` server:
```
rqlited -node-id 1 -http-addr 172.20.7.232:14001 -raft-addr 172.20.7.232:14002 ~/rqlite/node
```

Next, I tested the Raft address by running:
```
curl -i 172.20.7.232:14002
```
from another server, which returned:
```
HTTP/1.1 503 Service Unavailable
Connection: close
Proxy-Connection: close
Content-Length: 0
```
This indicates the connection was unsuccessful and the server returned an empty response with a `503 Service Unavailable` status.

but this case cannot good deal with using Go's HTTP client:
```go
resp, err := client.Get("http://" + addr)
if err == nil {
		resp.Body.Close()
		return true
}
```
which debug info is:
<img src="https://github.com/user-attachments/assets/0545b538-1553-4bec-8651-6ae0898524df" style="zoom: 50%">

To ensure robust handling of the Raft address, I recommend incorporating validation for the response based on the Content-Type specified in the response header.

**Comment by otoolep** [comment]
I don't entirely follow what you're doing, but I think you are saying that `IsServingHTTP` should return false if the HTTP server running at the address returns 503 (or any 5xx error code). But that is not correct -- there is even a unit test that checks for this:

https://github.com/rqlite/rqlite/blob/v8.31.3/http/preflight_test.go#L70

The point of `IsServingHTTP` is not to check if there is an rqlite HTTP server running at the address. It is to check if there is **any** HTTP server running at the address. AFAIK it's currently implemented correctly.

I'm going to close this issue, but please re-open if you think I'm mistaken. What I would like to see is a demonstration of either of the following:

- A HTTP server is running at a given address but `IsServingHTTP` returns false
- A HTTP server is not running at a given address (there may be nothing running at the address, or some other non-HTTP network service) but `IsServingHTTP` returns true.
