### ISSUE TITLE
Auto-restore from older version fails

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#1960]
A report has come in that the following fails to work:

- auto backup with 8.26.8
- auto restore from those backups with 8.30.5

Errors reported like the following:

```
failed to get current sum from s3://objectstore.nyc1.civo.com/objectstore01/backups/rqlite-nlabsbot.sqlite.gz: failed to get object head for s3://objectstore.nyc1.civo.com/objectstore01/backups/rqlite-nlabsbot.sqlite.gz: operation error S3: HeadObject, resolve auth scheme: resolve endpoint: endpoint rule error, Custom endpoint `nyc1.civo.com` was not a valid URI
```

I wonder if https://github.com/rqlite/rqlite/blob/master/CHANGELOG.md#v8293-august-31st-2024 broke anything, as the AWS SDK was upgraded.

**Comment by NerdyShawn** [comment]
Thanks for opening the issue. Essentially we were working with autorestore/autobackup and using that for the recovery plan if we had to rebuild or migrate k8s clusters or data centers. We downgraded the image tag in the chart to `8.26.8` and backups are resuming again.

**Comment by otoolep** [comment]
Tested this, it works fine.

**Comment by NerdyShawn** [comment]
Just to add to this one, we found that switching to `https` protocol instead of `s3` solved our issue and can construct the URI properly.
