### ISSUE TITLE
rqlite as a library

### ISSUE THREAD

**Issue by antonmedv** [rqlite/rqlite#1978]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to implement a distributed system. 

**Describe the solution you'd like**
I very like rqlite project ❤️. I'm building a simple distributed app. I'd like to make it simpler and only use SQLite. Single binary. But if I want to have a rqlite as a backend DB, distribution becomes much more complicated. Will be cool if it will be easier to just use rqlite as a library. And rqlite is handling raft and API calls. I'd like to "inherit" simplicity of creating a rqlite cluster.   

**Describe alternatives you've considered**
Don't create distributed app at all. 

**Additional context**
-

**Comment by otoolep** [comment]
Hey @antonmedv -- this has been requested a few times (checked _closed_ issues). I understand the motivation, but I've no plans to do it. Of course, others are welcome to do so.

**Comment by otoolep** [comment]
Welcome to do it, via a fork. Or I am open to refactor PRs which make it easier, but I tend to be opinionated about the structure of rqlite code, so a large change should be discussed beforehand.
