### ISSUE TITLE
existing databases?

### ISSUE THREAD

**Issue by jungle-boogie** [rqlite/rqlite#205]
Hello,

WOW! This is one awesome project. I compiled successfully on freebsd with Go 1.7.1

Just beginning to play around with rqlite, but I don't quite understand how to have it open an existing database to make that fault tolerant. Is that possible? If so, it doesn't seem like the sqlite dot commands work. For instance, I can't determine the schema of a database with `.schema`. Is that because that's not the job of rqlite? 

Does this project of a wiki page? I'd love to check it out and contribute when I become more familiar with this project.

thanks!

**Comment by otoolep** [comment]
The "dot" commands are not supported, as per https://github.com/rqlite/rqlite/blob/master/README.md#limitations

It is not possible to open an pre-existing SQLite database, and make it fault tolerant. To bootstrap a system from an existing SQLite database you need to `.dump` the SQLite file and play back the commands into the rqlite. 

See https://github.com/rqlite/rqlite/blob/master/doc/BACKUPS.md for more details

Finally, I don't have a wiki. There is documentation in the `doc` directory however. Improvements are welcome.
