### ISSUE TITLE
better way of extracting results?

### ISSUE THREAD

**Issue by tych0** [rqlite/rqlite#241]
Hi,

I was using some code like this:

```
for _, r := range rows.Values {
    n := make([]byte, len(r[0].([]byte)))
    copy(n, r[0].([]byte))
    real := string(n)
}
```

to extract sql results. 75417f6d1e78dc5e9556b7732fbefbbe1db734cf breaks this, but ends up making it substantially similar (`r[0].(string)` is all that's needed now).

My question is: is there some better way I can extract results with less brittle code so future changes like this work? Maybe that's a pipe dream, but I figured I'd ask :)

**Comment by otoolep** [comment]
This line:
`copy(n, r[0].([]byte))`
of your previous code was already making an assumption that the value was of type `[]byte`. If you were storing integers, for example, in the column, your code would have panicked.

The type for the values in question is `interface{}` which tells you nothing really. It would be nice to tighter, I am open to suggestions.

But the fact that it is `interface{}` already leaves the interface quite loose.

**Comment by tych0** [comment]
Right; the problem is that the commit above changes the return type of strings from []byte to string, so the code does panic. I'm just wondering if there's a cleaner way. I don't have any bright ideas right now, but I'll think about it :)

**Comment by otoolep** [comment]
OK, perhaps the new code should be more explicit about the contract of this function, as put in place by the recent change.

However, my point about your code (correct me if I am missing something) is that if you stored, say, integers in a column and attempted to type-assert them to `[]bytes`, that too would have panicked, even with the previous version of rqlite code.

**Comment by tych0** [comment]
Yes, the cast will fail if I try to cast a column to a type it's not. It's my job to cast it to the right thing. The problem is when the right thing changes underneath me :)

**Comment by otoolep** [comment]
Right, I see. Let me allow you to control this.

**Comment by otoolep** [comment]
OK, now that I look at it, this totally changed the contract. Bad on my part. Let me tweak the store now, so you have control over whether this conversion takes place. I do think the conversion is useful, but perhaps not to people who just care about the store package.

I'l push up a PR, and you can tell me what you think.

**Comment by otoolep** [comment]
Actually @tych0 -- can you tell me something else? Is the conversion to `string` when the underlying type is of TEXT affinity useful? If so, and it was an explicit part of the function's contract, would that be OK? I'm trying to determine if this conversion is actually useful at this layer.

So is the change in contract, or the conversion itself, that is awkward?

**Comment by otoolep** [comment]
Obsolete.
