### ISSUE TITLE
Some ideas for middlewares

### ISSUE THREAD

**Issue by anddimario** [rqlite/rqlite#248]
Hi, what do you think the possibility to add middlewares/plugins? For example, useful middlewares could allow to add a field validation, or an user acl to manage the access on tables/records. Or a plugins that run hooks/trigger functions on event.

**Comment by otoolep** [comment]
It's not a bad idea, though I am hesitant to add more functionality that drifts away from the core of rqlite. Field validation is a grey area, something that might be better in an ORM built on-top of rqlite.

As for the table ACL, I did consider something like that. It would be doable. How important or useful would it be? What is your application @anddimario ?

**Comment by anddimario** [comment]
I've started with go few days ago, and for my early tests i started with rqlite that it seems really interesting. I'm working basically on rest api, and rqlite use http endpoints in some way, so i think that it could be useful extends this functionality with a sort of graphql. A great part of rest endpoint are simply validation+db operations.

Maybe, it could be interesting the possibility to add this middleware/plugin as extentions in a simple way to maintain the idea of a lightweight core.

**Comment by otoolep** [comment]
I somewhat follow you, but I still need a bit more detail on what you would like. An example (fake) API call showing me what you want to do would be helpful.

**Comment by anddimario** [comment]
For example, for a validation middleware, user can define something like:
`VALIDATION table_name field_name regex,.....;`
For insert a new record, it could be used a post request with body:
`{ table: table_name, 
     method: 'insert',
     fields: {
        field_name: field_value'
     }
}`
On rqlite: post request->http server -> validation middleware -> query (if validation has no errors)

For acl, i've read the docs and i saw that users already could have particular permission. Maybe an extension of this method could be the possibility to allow particular permission based on field. For example, user could update only if record has a field called X with his name, a declaration like:
`PERMISSION table_name field_name operation`
`PERMISSION posts owner update`

For hook, maybe after an operation (like insert, or update) could be the possibility to run some code.

**Comment by otoolep** [comment]
I see -- thanks for the extra detail @anddimario 

Right now I don't think validation is a compelling enhancement of rqlite, relative to the other work I want to do with it. Part of the goal of rqlite is simplicitly -- a solid distributed consensus layer on top of SQLite. I'd much rather see stuff like validation in an ORM, for example. I could re-factor the code to allow plugins in general of course, but that would be major work I'm not prepared to do at this moment.

The ACL might be useful, but I'll need to see more requests for that level of control before building it into rqlite.
