### ISSUE TITLE
use rqlite to synchronize an existing db

### ISSUE THREAD

**Issue by fpoltronieri** [rqlite/rqlite#250]
Hi,
I have a question. It is possible to use rqlite to synchronize an existing SQlite database?
I was thinking about using rqlite to sync different servers that must have the same data.
I would not create the distributed database each time I start cluster.

**Comment by otoolep** [comment]
Hi @fpoltronieri -- if you want to modify the SQLite files directly the answer is no. It's definitely not supported:

https://github.com/rqlite/rqlite/blob/master/README.md#limitations

If you want to modify one SQLite database through the HTTP API, and then only *read* the SQLite files under other nodes, that might work but it's not really supported either.

Feel free to ask more questions if you like on this ticket, but I am closing it for now.

**Comment by fpoltronieri** [comment]
Do you think that would be a good feature to implement?

**Comment by otoolep** [comment]
It might be, but I need a bit more detail on what exactly you want to happen. A detailed scenario, explaining what happens at each step would be helpful.
