### ISSUE TITLE
How does SAVEPOINT behaves?

### ISSUE THREAD

**Issue by alanjds** [rqlite/rqlite#252]
In the readme [is said](https://github.com/rqlite/rqlite/blame/master/README.md#L148) that 

> The behaviour of rqlite when using BEGIN, COMMIT, or ROLLBACK to control transactions is not defined.

But what about SAVEPOINT ? It is ok to be used or should be considered undefined?

**Comment by alanjds** [comment]
Disclaimer: I am creating a Django database backend for RQLite, based on SQLite backend code, and disabling code that is not expected to work.

**Comment by otoolep** [comment]
Hello @alanjds -- I just looked up `SAVEPOINT`. Same thing applies, the behaviour is not defined.

I have ideas about allowing it, but haven't tested it. If it's a real problem, I might see what I can do.

**Comment by otoolep** [comment]
I closed the ticket, but feel free to ask more questions here. I'd also be interested in seeing your Django backend, if you open-source it.

**Comment by alanjds** [comment]
It is just the standard sqlite backend with pyrqlite as the connector and transactions disabled ;)

Will upload as soon as the existing sqlite tests passes -- minus the transaction ones --

And thanks anyone for the DB-API driver. I would not start the Django backed if there was not the DB-API done.
