### ISSUE TITLE
No Windows?

### ISSUE THREAD

**Issue by insionng** [rqlite/rqlite#259]

**Comment by otoolep** [comment]
No, I don't provide Windows builds on the release page. However I test the source each commit to make sure it's still buildable on Windows, so you can compile it yourself.

**Comment by insionng** [comment]
Thanks reply~

**Comment by StarpTech** [comment]
@otoolep why you don't provide Windows builds ? If you can't you could setup a routine to upload the asset to the release with https://developer.github.com/v3/repos/releases/#upload-a-release-asset

Script in golang https://github.com/aktau/github-release

**Comment by otoolep** [comment]
I don't have access to a Windows box, and haven't figured out cross-compiling yet. If you can provide me a build line I can run from Linux, I can do it.

I do run all the code through appveyor CI, so it is buildable on Windows at all times.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/blob/master/appveyor.yml

https://ci.appveyor.com/project/otoolep/rqlite
