### ISSUE TITLE
Store SnapShot method does not buffer read the database which could be an issue if database size is large

### ISSUE THREAD

**Issue by JeanGolang** [rqlite/rqlite#273]
Hello Philip!
I think there is an issue with this part of the code of rqlite (store/store.go).

```
func (s *Store) Database(leader bool) ([]byte, error) {
	if leader && s.raft.State() != raft.Leader {
		return nil, ErrNotLeader
	}
	// Ensure only one snapshot can take place at once, and block all queries.
	s.mu.Lock()
	defer s.mu.Unlock()

	f, err := ioutil.TempFile("", "rqlilte-snap-")
	if err != nil {
		return nil, err
	}
	f.Close()
	defer os.Remove(f.Name())

	if err := s.db.Backup(f.Name()); err != nil {
		return nil, err
	}

	return ioutil.ReadFile(f.Name())
}
```
As far as I understood from your code it's a support function for creating a snapshot of the database. However, this implementation reads the whole database into memory, in your particular case in the variable fsm.database, err = s.Database(false), so if the size of your database is larger than RAM available, I guess the program would crash.

I guess it's better to read the database in buffers or send chunks of the database via a channel when writing it to the so called SnapshotSink.

Thanks!

**Comment by otoolep** [comment]
Thanks -- it's a weakness, I can look into addressing.

**Comment by JeanGolang** [comment]
Hi again, Philip!
Do you happen to know how to fix this problem? I guess it's a "bug" in hashicorp/raft implementation.
Because as far as I understood, hashicorp/raft doesn't call Snapshot() and Persist() concurrently, so I don't know of a way to communicate chunks of the database between Snapshot() and Persist() - do you have an idea how to do this?

**Comment by otoolep** [comment]
Is it actually causing you an issue?

**Comment by otoolep** [comment]
I mean, are you actually encountering a problem in practice?

**Comment by JeanGolang** [comment]
otoolep, thanks a lot! I've sorted it out with the raft library authors - [https://github.com/hashicorp/raft/issues/202]()
I guess this could be closed, as if it's more of the raft issue than an issue with your package.

**Comment by otoolep** [comment]
Thank you @JeanGolang -- I will look into using the new interface exposed by the Raft package.

**Comment by otoolep** [comment]
This code has been significantly re-written since this issue was opened.
