### ISSUE TITLE
rqlite CLI: How to List table and execute ".command" like standalone sqlite?

### ISSUE THREAD

**Issue by deadjoe** [rqlite/rqlite#277]
Thanks for this wonderful project. 

After deployed three nodes rqlite cluster, i tried to connect to the cluster via rqlite CLI tool without any problem . But it seems the CLI did not accept the normal standalone sqlite client command as https://www.sqlite.org/cli.html defined. After read the docs still can't find the details of supported command within rqlite CLI command.

Thanks

**Comment by otoolep** [comment]
Thanks for your note.

The commands you reference are not standard SQL, so are not yet supported. Those commands are part of the `sqlite3` command, not SQLite itself.

https://github.com/rqlite/rqlite/blob/master/README.md#limitations

https://github.com/mattn/go-sqlite3/issues/305

**Comment by otoolep** [comment]
I'll leave this issue open for now, because I agree it would be useful to support these commands. It's not trivial to do it the right way.

**Comment by otoolep** [comment]
It was easy enough to add specific support for `.tables` and `.schema` to the rqlite CLI -- try it out. Top of tree supports it now.

**Comment by otoolep** [comment]
Support for `.tables` and `.schema` is now available through the rqlite CLI, version 3.11.0 and later.
