### ISSUE TITLE
Backup & Restore not working

### ISSUE THREAD

**Issue by hmxxyy** [rqlite/rqlite#300]
Trying the backup and restore, always get syntax error.

This is an empty fresh database just created with
./rqlited -http 10.9.211.251:4001 -raft 10.9.211.251:4002 ~/node

curl 10.9.211.251:4001/db/backup -o x1.dmp

curl -XPOST 10.9.211.251:4001/db/load -H "Content-type: text/plain" --data-binary @x1.dmp
{"results":[{"error":"near \"SQLite\": syntax error"}]}

**Comment by otoolep** [comment]
You are missing a key step in the restoration process. You must first convert the dump file to set of SQL commands. In your case do the following:

`echo '.dump' | sqlite3 x1.dmp > restore.dump`

Then load `restore.dump`.

I will make this clearer in the docs.

**Comment by hmxxyy** [comment]
thanks @otoolep for the prompt reply. It works with that step added.
