### ISSUE TITLE
Can data be inserted via a follower node?

### ISSUE THREAD

**Issue by WesleyRen** [rqlite/rqlite#301]
Using "level=none" we can query from a follower node. But I couldn't find an equivalent way of inserting via a follower node. 
Is it supported? Thanks!

**Comment by otoolep** [comment]
@WesleyRen -- the short answer is no.

However if you can send a write request to a follower, the follower will return 301 and include in the response a HTTP header value, which shows the location of the leader.

This allows you to write code that transparently (to a user) sends write requests to any node in the cluster. The rqlite CLI does that, for example: https://github.com/rqlite/rqlite/blob/master/cmd/rqlite/main.go#L107

**Comment by WesleyRen** [comment]
Great!
Thanks for the quick response and the example code.
