### ISSUE TITLE
Can't create a Cluster (connection refused)

### ISSUE THREAD

**Issue by Majonsi** [rqlite/rqlite#303]
Hi !
I'm currently trying to create a cluster of multiple computer (ubuntu or/and Raspberry pi). I have go 1.8.1 on my computer and then I followed [this steps](https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite) on both of my computer. 

for the first one I ran this command:
`$GOPATH/bin/rqlited -http -raft ~/node`
Rqlite is launched normally

On the second one I ran this command (where IP is the IP adress of the computer):
`$GOPATH/bin/rqlited -http localhost:4001 -raft localhost:4002 -join http://IP:4001 ~/node`

Rqlite is trying to connect to the first computer but I get this errors:
```
[rqlited] 2017/04/19 13:02:39 rqlited starting, version 3, commit unknown, branch unknown
[rqlited] 2017/04/19 13:02:39 go1.8.1, target architecture is arm, operating system target is linux
[tcp] 2017/04/19 13:02:39 mux serving on 127.0.0.1:4002, advertising 127.0.0.1:4002
[store] 2017/04/19 13:02:39 SQLite in-memory database opened
[store] 2017/04/19 13:02:39 waiting for up to 2m0s for application of initial logs
2017/04/19 13:02:39 [INFO] raft: Node at 127.0.0.1:4002 [Follower] entering Follower state (Leader: "")
[cluster] 2017/04/19 13:02:39 service listening on 127.0.0.1:4002
[rqlited] 2017/04/19 13:02:39 join addresses are: [http://IP:4001]
[cluster-join] 2017/04/19 13:02:39 failed to join cluster at [http://IP:4001], sleeping 5s before retry
2017/04/19 13:02:41 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
[cluster-join] 2017/04/19 13:02:44 failed to join cluster at [http://IP:4001], sleeping 5s before retry
[cluster-join] 2017/04/19 13:02:49 failed to join cluster at [http://IP:4001], sleeping 5s before retry
[cluster-join] 2017/04/19 13:02:54 failed to join cluster at [http://IP:4001], after 3 attempts
[rqlited] 2017/04/19 13:02:54 failed to join cluster at [http://IP:4001]: Post http://IP:4001/join: dial tcp IP:4001: getsockopt: connection refused
```
I tried:
- Run on different computer (different Raspbian and Ubuntu)
- Change the port number
- tried with:` http://IP:4001` , `https://IP:4001` and all the possible combinations

 Note: 
- Run 2 node on the same computer work
- It's not my network the problem because I can create a go server and connect to it from another computer

Anybody have a suggestion to solve the issue?

Best regards Majonsi

**Comment by otoolep** [comment]
You are not launching the first node correctly. And by default the first node will list on localhost, which is 127.0.0.1. That is not the same as the IP address of your machine (though the interface may be the same). You need to launch the first node as follows:

`$GOPATH/bin/rqlited ~/node1`

and launch the second node as:

 `$GOPATH/bin/rqlited -http localhost:4001 -raft localhost:4002 -join http://localhost:4001 ~/node2`

See https://github.com/rqlite/rqlite/blob/master/doc/CLUSTER_MGMT.md for more details.

**Comment by otoolep** [comment]
Closing, please re-open if you still believe there is a problem.

**Comment by otoolep** [comment]
And take a look at https://github.com/rqlite/rqlite/blob/master/system_test/end_to_end.sh for explicit  commands on running a cluster on the same machine.

**Comment by Majonsi** [comment]
@otoolep 
Thanks for your response. It's now working! But is that normal that I have to type in the command the Ip adress of the machine instead of localhost? So my command become:
`$GOPATH/bin/rqlited -http IPOFTHEHOST:4001 -raft IPOFTHEHOST:4002 -join http://IPOFTHEANOTHERCOMPUTER:4001 ~/node2`
This mean that I can't connect a computer to a node which have been launched with the command : `$GOPATH/bin/rqlited ~/node1` ?

**Comment by otoolep** [comment]
Correct.

**Comment by otoolep** [comment]
To address your issue would require changing the default listening IP addresses to 0.0.0.0. It's easy to do, but it wasn't the choice I went with. Perhaps I should have.
