### ISSUE TITLE
Increamental blob write support (sqlite3_blob_write)?

### ISSUE THREAD

**Issue by lsm** [rqlite/rqlite#313]
Does rqlite support read/write with offset?

**Comment by otoolep** [comment]
If I understand your questions, the answer is no. rqlite doesn't expose the C API directly. It only supports SQLite commands.

Please check out the detailed API docs for more information:

https://github.com/rqlite/rqlite/blob/master/doc/DATA_API.md

**Comment by lsm** [comment]
I see.  Thanks!
