### ISSUE TITLE
2 Node "Cluster"?

### ISSUE THREAD

**Issue by rymoore** [rqlite/rqlite#318]
Is it possible in any way to run rqlite in a 2-node replicated "cluster"?

**Comment by otoolep** [comment]
You mean, can you run a 2-node cluster? Sure. Just run two nodes, the second one joining to the first.

You will have no fault tolerance however, since if either nodes fails, your cluster will be down.

**Comment by otoolep** [comment]
Re-open if I don't understand your question.

**Comment by rymoore** [comment]
Sorry, I guess I'm asking "can the 2nd node become master when the 1st node goes down" - so it's a failover

**Comment by otoolep** [comment]
No, it can't since a 2-node cluster requires a majority of the nodes to be up. 1 out of 2 nodes is not a majority.

**Comment by rymoore** [comment]
is it possible to do a manual election / failover?

**Comment by otoolep** [comment]
Not without killing the leader and restarting it. But that would not be sensible.

rqlite is not a good match for a simple master-slave replicated system.

**Comment by rymoore** [comment]
Thanks!
