### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by SadE54** [rqlite/rqlite#319]
Hi,

Is it possible to compile it/get binaries for windows ?

**Comment by otoolep** [comment]
Yes, it is possible. See https://github.com/rqlite/rqlite/issues/259

**Comment by otoolep** [comment]
You will need to follow the Appveyor build to understand how to build for Windows.

https://github.com/rqlite/rqlite/blob/master/appveyor.yml

**Comment by otoolep** [comment]
https://ci.appveyor.com/project/otoolep/rqlite
