### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by chenziliang** [rqlite/rqlite#325]
Is there a race condition in theory for Mux.m in functions (mux *Mux) handleConn and (mux *Mux) Listen in mux.go since these 2 functions are in different goroutine and read/write access to the same map without sync

**Comment by otoolep** [comment]
Yes, looks like it @chenziliang. It would be an easy fix however.

**Comment by chenziliang** [comment]
Thanks @otoolep . BTW, may i ask what is the performance degradation comparing to single instance sqlite3 ?

**Comment by otoolep** [comment]
The performance degradation is measurable, due to the Raft layer, but probably not huge for a single node. For multi-node clusters it will be quite significant.

https://github.com/rqlite/rqlite/blob/master/README.md#performance

**Comment by otoolep** [comment]
I don't plan to fix this, since it's not really significant.
