### ISSUE TITLE
Logical Decoding as used by bottledwater-pg. Possible?

### ISSUE THREAD

**Issue by raarts** [rqlite/rqlite#326]
As the designer of the package, can you look a little bit into [Bottled Water](https://www.confluent.io/blog/bottled-water-real-time-integration-of-postgresql-and-kafka/), and check if it would be a possibility? 

The SQLite developers mention  [in this thread](http://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg96847.html) that it doesn't support [Logical Decoding](https://www.postgresql.org/docs/9.4/static/logicaldecoding.html), and suggest some way to achieve that. They also point to rqlite (for slightly related reasons).

What I'm looking at, is putting sqlite db changes into kafka, just like [bottledwater-pg](https://github.com/confluentinc/bottledwater-pg) does.

**Comment by otoolep** [comment]
@raarts -- I'm not sure I really follow what you are proposing. I am very familiar with the "Bottled Water" system (and Kafka in general), and have built similar systems.

But it's not clear what kind of possibilities you have in mind. rqlite is built on SQLite. It has no access to its WAL.

**Comment by raarts** [comment]
Alright, well, happy that you already are familiar. What I'd like to accomplish is getting changes to sqlite databases into kafka in a similar way as Bottled Water does.

According to what I read on the SQLite mailing list, it's quite hard get the changes that were done in a transaction from the disk blocks, but an alternative was suggested, saving all queries to a special table, and work from there. 

I got on your site from a link in that same thread, and thought you would have needed access to all queries as well, for syncing. Seemed to point in the same direction.

And if you think it's impossible (or at least impractical), that's an answer too.

**Comment by otoolep** [comment]
OK, right. rqlite processes the changes *before* they go to SQLite:

https://github.com/rqlite/rqlite/blob/master/doc/DESIGN.md

So it sits, logically, on top of SQLite. Sounds like you want something that streams changes out of SQLite after they are have occurred. rqlite is not that thing.

**Comment by otoolep** [comment]
Closing this because I believe I've answered your question, but let me know if not.
