### ISSUE TITLE
I can't running rqlite and rqlited in my docker container from alpine 

### ISSUE THREAD

**Issue by lkxjtu** [rqlite/rqlite#331]
I have copy rqlite and rqlited to my docker container,and running ./rqlite, I got "not found" error.
```
/rqlited-v4.0.0-linux-amd64 # ls -l
total 23520
-rwxr-xr-x    1 root     root       8699768 Jul 26 15:35 rqlite
-rwxr-xr-x    1 root     root      15382256 Jul 26 15:35 rqlited
/rqlited-v4.0.0-linux-amd64 # ./rqlite
sh: ./rqlite: not found
/rqlited-v4.0.0-linux-amd64 # ./rqlited
sh: ./rqlited: not found
```

My docker image is build from alpine. There is no problem in docker container which build from Ubuntu. What libs does rqlite and rqlited depend?

**Comment by lkxjtu** [comment]
This is because of there is no glibc in alpine,after add alpine-pkg-glibc, it works fine.This problem is nothing to do with rqlite.

**Comment by otoolep** [comment]
OK, presumably this is issue should be closed.
