### ISSUE TITLE
Where does rqlite store data

### ISSUE THREAD

**Issue by lkxjtu** [rqlite/rqlite#332]
I start rqlited as "rqlited -http-addr 0.0.0.0:4001 -raft-addr 0.0.0.0:4002 /root/data/rqlite". But after delete all files in /root/data/rqlite/,there are data still. 
```
~/data/rqlite # pwd
/root/data/rqlite
~/data/rqlite # ls
~/data/rqlite # rqlite
127.0.0.1:4001> select * from nodes;
+----+--------------------------------------+------------------------------+-------+---------+----------------------+----------------------+
| id | uuid                                 | ip                           | vars  | roles   | create_at            | updated_at           |
+----+--------------------------------------+------------------------------+-------+---------+----------------------+----------------------+
| 1  | 20cb77ea-0491-4263-8fc2-1cc94d1b95f8 | {"net_mgt": "192.168.2.242"} | <nil> | [u'OP'] | 2017-07-27T19:29:20Z | 2017-07-27T19:29:20Z |
+----+--------------------------------------+------------------------------+-------+---------+----------------------+----------------------+
```
What is the reason for this？

**Comment by otoolep** [comment]
For general questions like this, you can now use the Google Group:

https://groups.google.com/forum/#!forum/rqlite

As for your general question, it stores data right where you requested `/root/data/rqlite`. rqlite uses an in-memory database by default:

https://github.com/rqlite/rqlite/blob/master/README.md#in-memory-databases

Until you restart the system you won't see any changes.
