### ISSUE TITLE
CLI does not support BackSpace and UP button

### ISSUE THREAD

**Issue by lkxjtu** [rqlite/rqlite#339]
My rqlite version is 4.0.0, when I input BackSpace to deleting error characters, CLI output
```
127.0.0.1:4001> select * frooo^H^H
ERR! near "frooo": syntax error
```

And UP button has the same problem
`127.0.0.1:4001> ^[[A`

Is this my environment problem or CLI not support?

My environment infromation as
```
/ # cat /proc/version 
Linux version 3.10.0-514.21.1.el7.x86_64 (root@localhost.localdomain) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Thu Jun 29 01:10:55 CST 2017
```

**Comment by lkxjtu** [comment]
Sorry I can't submit google account, so only in this question. If you think it is not right here, you can turn this topic off,thanks!

**Comment by otoolep** [comment]
It's something specific with your terminal. In any event, the UP button doesn't recall commands.
