### ISSUE TITLE
about HTTP request on Follower node

### ISSUE THREAD

**Issue by wangke1970** [rqlite/rqlite#349]
how to  send a HTTP request to a Follower  node? I do not need redirect
                                                                        Thanks

**Comment by otoolep** [comment]
To answer your question, I need to know what you are trying to do.

**Comment by otoolep** [comment]
I clarified some documentation around this, which may be relevant: https://github.com/rqlite/rqlite/blob/master/doc/DATA_API.md

**Comment by wangke1970** [comment]
Read-write separation ， eg：Read use Follower ，write use leader
Ease leader IO

**Comment by wangke1970** [comment]
Thank you. I didn't read the document carefully

**Comment by otoolep** [comment]
OK.

Just remember @wangke1970 -- by reading directly from a follower, you risk getting stale data back: https://github.com/rqlite/rqlite/blob/master/doc/CONSISTENCY.md

rqlite is not about improving read and write performance. It's about reliability.
