### ISSUE TITLE
Embedding in a Go application

### ISSUE THREAD

**Issue by hartfordfive** [rqlite/rqlite#353]
Is it possible to directly embed rqlite into another Go application?

**Comment by otoolep** [comment]
Would you mind sending this question to the Google Groups mailing list? https://groups.google.com/forum/#!forum/rqlite

I'll be sure to answer there, and others can benefit from the response.

**Comment by otoolep** [comment]
Answered at https://groups.google.com/d/msg/rqlite/6Fv9v2gcCSo/dqt7jyX6AwAJ
