### ISSUE TITLE
how can i make a subscribe for a exist cluster?

### ISSUE THREAD

**Issue by dbskccc** [rqlite/rqlite#358]
suppose i have a cluster with node A,B,C and them can access from internet,  now i have node D live in a lan(behind nat) which can only connect to A.
question:
 1. how can i keep node D  sync with the cluster, suppose node D is read only.
 2. if 1 is possible, can i modify in D and the new data sync to cluster.

thanks.

**Comment by otoolep** [comment]
Please send a question like this to the rqlite Google group at https://groups.google.com/forum/#!forum/rqlite

I will be sure to answer it there.

**Comment by dbskccc** [comment]
have post on google group, sorry for the noise!

**Comment by otoolep** [comment]
https://groups.google.com/d/msg/rqlite/XqoUhScLzhQ/Smy71qKjBgAJ
