### ISSUE TITLE
zeroconf Support

### ISSUE THREAD

**Issue by turbo** [rqlite/rqlite#364]
Hi there,

I'm using rqlite in LAN deployments. It would be nice to have a zeroconf discovery option, and not a central service registry.

Each node would need to [register as a service](https://github.com/grandcat/zeroconf/blob/master/examples/register/server.go) and also [discover (browse) other nodes](https://github.com/grandcat/zeroconf/blob/master/examples/resolv/client.go). 

There would still need to be same shared secret, so not just anyone can join a cluster. 

Would love to hear your thoughts on this.

**Comment by otoolep** [comment]
@turbo -- I am definitely interested in adding options that makes it easier to manage clusters. I had not heard of zeroconf before. Is it widely used? It doesn't seem too difficult to add this functionality to rqlite.

**Comment by turbo** [comment]
Zeroconf is widely adopted. Apple software uses it (Bonjour, and Bonjour Wide). Mist linux distros ship with a browser by default (avahi).

**Comment by turbo** [comment]
Zeroconf is definitely only for local network deployments and should be opt-in. I see two ways this could be implemented in the front end:

**Dedicated Option**

E.g. `-z`. So basically just execute an identical command on all nodes (`rqlite --secret 1234 --zeroconf [options]`) and the cluster auto builds. This would probably prevent any scripts from breaking.

**Modularize Discovery Service**

Use a `--discovery` switch or similar to switch between zeroconf, your service or manual (default).

**Comment by otoolep** [comment]
OK, let me look into it. I'll need to do some study, but a dedicated option seems best.

Can I ask what you are using rqlite for? I am always keen to learn about its applications.

**Comment by turbo** [comment]
As a microservice in a bigger project, on-premise data lake exploration. I can't really say much more than that. I'm battle-testing it right now. My priorities are:

- Lowering latency (hence my question on the RPC issue)
- Enterprise firewall and IPS/DPI friendly protocol (currently testing this in depth)

So far, all looks good. I care about Windows environments most of all, but I love that I could get it to run in no time on a number of different platforms. In my specific use case, I can use rqlite to scale for performance, too.

**Comment by otoolep** [comment]
I can probably add the new gRPC functionality relatively easily, since it's an area I understand pretty well. However it would require that you use purpose-built libraries to access the node. It's easy to generate client libraries in various languages though.

How do you communicate with an rqlite node? Have you written your own code?

**Comment by turbo** [comment]
I currently use the HTTP API from various languages (each service might be another language). Mainly we're looking at dotnet core, PHP, Node.js and Go. Different services request different levels of read consistency. As far as I can tell, all these languages support gRPC clients.

**Comment by otoolep** [comment]
No plans to work on this.
