### ISSUE TITLE
CLI should accept username and password

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#369]
The CLI doesn't current support adding Basic Auth information to the HTTP requests it makes, meaning it can't be used with a secure cluster. Ideally it would take something like the following as an option:

```
-u, --user username:password
```

and then set add Basic Auth credentials when making all requests.

**Comment by wuxiaoxiaoshen** [comment]
How are you getting along with the work?

**Comment by otoolep** [comment]
It hasn't started. It's an easy issue, which I plan to leave to the community.
