### ISSUE TITLE
Support spatial index

### ISSUE THREAD

**Issue by icewukong** [rqlite/rqlite#386]
Hi,
How to support spatial data, like Spatialite?
Support for spatial indexing almost becomes the standard of relational databases.

**Comment by otoolep** [comment]
The underlying SQLite code would need to be recompiled to support Spatialite. It's beyond the scope of rqlite, and is something you should actually discuss on https://github.com/mattn/go-sqlite3. If it can be made to support it, then rqlite could do something.

**Comment by icewukong** [comment]
Hi, @otoolep 
Here's a library that supports spatialite, can U support it?
https://github.com/shaxbee/go-spatialite

**Comment by otoolep** [comment]
To be honest, there are other higher-priority issues I need to deal with first. It's highly unlikely I'll add this to rqlite.
