### ISSUE TITLE
vendor dependencies is incomplete.

### ISSUE THREAD

**Issue by Chyroc** [rqlite/rqlite#390]
I have a question, I use the `dep init` generated  is this, but I see `vendor` below only two libraries, is not where a problem?
If I compile directly, will be wrong to say
```
cannot find package "github.com/armon/go-metrics"
cannot find package "github.com/hashicorp/go-msgpack/codec"
```

Then I try to install these dependencies myself using `dep init` or `dep ensure`, and then I've found some dependencies on your `vendor`, so when I install it, I get a lot of git changes and I'm confused.

Perhaps it should be said that all the dependencies are placed under `vendor` and then uploaded to github, either not uploaded, then `vendor` is set to `git ignore` so that I can install it myself.

Gopkg.toml:
```
[[constraint]]
  branch = "master"
  name = "github.com/Bowery/prompt"

[[constraint]]
  name = "github.com/hashicorp/raft"
  version = "v0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/raft-boltdb"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  name = "github.com/mkideal/cli"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/mkideal/pkg"
```

Gopkg.lock:
```
# This file is autogenerated, do not edit; changes may be undone by the next 'dep ensure'.


[[projects]]
  branch = "master"
  name = "github.com/Bowery/prompt"
  packages = ["."]
  revision = "753711fea478fa77bb2c83f6ec244b814d4a8bad"

[[projects]]
  branch = "master"
  name = "github.com/armon/go-metrics"
  packages = ["."]
  revision = "7aa49fde808223f8dadfdbfd3a20ff6c19e5f9ec"

[[projects]]
  name = "github.com/boltdb/bolt"
  packages = ["."]
  revision = "2f1ce7a837dcb8da3ec595b1dac9d0632f0f99e8"
  version = "v1.3.1"

[[projects]]
  branch = "master"
  name = "github.com/hashicorp/go-immutable-radix"
  packages = ["."]
  revision = "59b67882ec612f43b9d4c4fd97cebd507be4b3ee"

[[projects]]
  branch = "master"
  name = "github.com/hashicorp/go-msgpack"
  packages = ["codec"]
  revision = "fa3f63826f7c23912c15263591e65d54d080b458"

[[projects]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"
  packages = ["simplelru"]
  revision = "0a025b7e63adc15a622f29b0b2c4c3848243bbf6"

[[projects]]
  name = "github.com/hashicorp/raft"
  packages = ["."]
  revision = "6d14f0c70869faabd9e60ba7ed88a6cbbd6a661f"
  version = "v0.1.0"

[[projects]]
  branch = "master"
  name = "github.com/hashicorp/raft-boltdb"
  packages = ["."]
  revision = "6e5ba93211eaf8d9a2ad7e41ffad8c6f160f9fe3"

[[projects]]
  name = "github.com/labstack/gommon"
  packages = ["color"]
  revision = "57409ada9da0f2afad6664c49502f8c50fbd8476"
  version = "0.2.3"

[[projects]]
  name = "github.com/mattn/go-colorable"
  packages = ["."]
  revision = "167de6bfdfba052fa6b2d3664c8f5272e23c9072"
  version = "v0.0.9"

[[projects]]
  name = "github.com/mattn/go-isatty"
  packages = ["."]
  revision = "0360b2af4f38e8d38c7fce2a9f4e702702d73a39"
  version = "v0.0.3"

[[projects]]
  name = "github.com/mattn/go-sqlite3"
  packages = ["."]
  revision = "6c771bb9887719704b210e87e934f08be014bdb1"
  version = "v1.6.0"

[[projects]]
  name = "github.com/mkideal/cli"
  packages = ["."]
  revision = "0bc4738ef26827a45d3b50394d84d283f733ad63"
  version = "v0.0.1"

[[projects]]
  branch = "master"
  name = "github.com/mkideal/pkg"
  packages = ["debug","expr","textutil"]
  revision = "3e188c9e7ecc83d0fe7040a9161ce3c67885470d"

[[projects]]
  branch = "master"
  name = "golang.org/x/sys"
  packages = ["unix"]
  revision = "2c42eef0765b9837fbdab12011af7830f55f88f0"

[solve-meta]
  analyzer-name = "dep"
  analyzer-version = 1
  inputs-digest = "a07ddf2307396778c251ae83dbd67c3389ba6569b73956a9498bcdd6da2c89f4"
  solver-name = "gps-cdcl"
  solver-version = 1

```

**Comment by Chyroc** [comment]
i see this: https://github.com/rqlite/rqlite/pull/354 and https://github.com/rqlite/rqlite/issues/87

For some historical reason, the code that led to `github.com/hashicorp/raft` was submitted to github, and I think it's time to submit all the dependencies! The official tool `dep` by go

**Comment by otoolep** [comment]
Thanks for the report.

I'm not sure I see what the problem is in the short term. I have complete, quite simple, build instructions in [CONTRIBUTING.md](https://github.com/rqlite/rqlite/blob/master/CHANGELOG.md) which works well. I chose only to vendor the Raft module since it changed recently.

rqlite is easily built simply using `go build` -- you don't need to use any dependency tools. I don't have 100% repeatable builds yet, but have decided to focus on other issues for now.

**Comment by otoolep** [comment]
Specifically here:

https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite

This is one builds rqlite at present. I make no promises about this project working with dependency management tools right now.

**Comment by dbabits** [comment]
I also have a problem building, as described in my other thread.
I cannot use go get behind corporate firewall.
 I cannot build outside and get binaries in.
I can download code from github and go build.
However, that fails because of incomplete vendor directory.
I will figure it out(hunting dependencies manually now), but if you could try "download zip file" from github, and try to build on a clean machine, you should  see the issue.
thanks!

**Comment by otoolep** [comment]
go mod now on master.
