### ISSUE TITLE
"Remove node" works only if requested to the leader

### ISSUE THREAD

**Issue by giner** [rqlite/rqlite#391]
It would be convenient to be able to request `/remove` to a random node, not only leader. Would it be feasible to implement?

**Comment by otoolep** [comment]
You don't get HTTP 301 redirect? How are you sending the request?

**Comment by giner** [comment]
I do it the following way:
```
curl -XDELETE "$URI/remove" -d '{"addr": "$INTERNAL_IP:4002"}'
```
Where `$URI` is L7 balancer. If the request goes to a follower I get 500.

**Comment by otoolep** [comment]
Thanks for your report. This issue has been fixed on master, so that the node will return HTTP 301 if the node is not the leader. It's up to your client code to read the location header and re-issue the request.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/releases/tag/v4.2.3 contains the fix. Only the Linux build is available now, but I will post the OSX version soon.
