### ISSUE TITLE
Feature: Hashed password in authFIle

### ISSUE THREAD

**Issue by sum12** [rqlite/rqlite#395]
Currently  `CredentialStore` expects passwords to be stored in cleartext in the `authFile`.

This is not really a problem as the long the access permissions to `authFile` are clean and controlled.

However, hashed password are always a better idea than cleartext. 
If that is acceptable, I would like to submit a patch for the same.

And Thank you for rqlite.

**Comment by otoolep** [comment]
Go for it @sum12  -- patches are welcome.

**Comment by sum12** [comment]
I had this https://github.com/rqlite/rqlite/compare/master...sum12:hashedpass working but turns out `base64` of `bcrypt`ed password generates value that is not accepted in the headers.

That points to having alternate means of authetication apart from basic auth

Not sure how to go proceed, or if this is even feasible.

**Comment by otoolep** [comment]
I'm not sure I follow you. Can you provide a concrete example of what the password would be, and what would be in the header, that wouldn't work?

**Comment by sum12** [comment]
I hope this helps clear my comment above.
Using this go sample, `Password: 111` 
```go
package main

import (
	"fmt"
	"golang.org/x/crypto/bcrypt"
)

func main() {
	password := []byte("111")
	hashedPassword, err := bcrypt.GenerateFromPassword(password, bcrypt.DefaultCost)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(hashedPassword))
}
```
generates a hash 
using the hash 

```python
'Basic ' +  codecs.encode('{}:{}'.format(user, password).encode('utf-8'),'base64').decode('utf-8').rstrip('\n')
```
Generating a header 
```
'Basic MTExOiQyYSQxMCRxVHBOcHl5TlJQOXF6RThWU1FaZ011MHhVUVZZSUNoUWNxa1RiUnVrWDJRNktv\nd0F5TGJrMg=='
```
The pyrqlite client throws error
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    cursor.execute('CREATE TABLE foo (id integer not null primary key, name text)')
  File "build/bdist.linux-x86_64/egg/pyrqlite/cursors.py", line 123, in execute
  File "build/bdist.linux-x86_64/egg/pyrqlite/cursors.py", line 72, in _request
  File "build/bdist.linux-x86_64/egg/pyrqlite/connections.py", line 90, in _fetch_response
  File "build/bdist.linux-x86_64/egg/pyrqlite/connections.py", line 78, in _retry_request
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1096, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib64/python2.7/httplib.py", line 1035, in putheader
    raise ValueError('Invalid header value %r' % (one_value,))
ValueError: Invalid header value 'Basic MTExOiQyYSQxMCRxVHBOcHl5TlJQOXF6RThWU1FaZ011MHhVUVZZSUNoUWNxa1RiUnVrWDJRNktv\nd0F5TGJrMg=='
```

**Comment by sum12** [comment]
oops my bad.

Please ignore the previous comments

turns out I misunderstood my own implementation :smile:
