### ISSUE TITLE
Could you statically compile glibc ?

### ISSUE THREAD

**Issue by dbabits** [rqlite/rqlite#402]
I am behind corporate firewall, and can't go get any dependencies needed to compile myself.
I can only get what's included in this project.
Trying to run the released executable gives me this complaint:
rqlite-v4.3.0-linux-amd64/rqlited: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by rqlite-v4.3.0-linux-amd64/rqlited)

Could you statically link glibc and other dependencies, in true go-style ?
Thank you!

**Comment by otoolep** [comment]
Trivial program built on top of C code, and showing that the default output does not include a statically-linked libc. This is on Linux.

https://play.golang.org/p/5RmU6qLvsbN

```
$ go build main.go 
$ ./main 
42
1804289383
$ ldd main
	linux-vdso.so.1 (0x00007fff009f2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff99d438000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff99d099000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff99d655000)
$ 
```

**Comment by otoolep** [comment]
Don't you have access to a box other than those behind your firewall? What you suggest may work, but unfortunately it's not something I going to look into anytime soon.

**Comment by dbabits** [comment]
sure, I will try some time later.
Thanks.

**Comment by otoolep** [comment]
I'm not planning any work here.
