### ISSUE TITLE
How to enable single mode

### ISSUE THREAD

**Issue by humbled** [rqlite/rqlite#403]
https://github.com/rqlite/rqlite/blob/9ea300e00b7757675c5b724e9d8a944191bb603e/store/store.go#L226

enableSingle is a param. Also seen in logging (somewhere, haven't found again). How can I set this to true?

I am interested in optional enforcement of quorum; partitioning is unlikely; data is short-lived and inconsistency is not catastrophic

Thanks

**Comment by otoolep** [comment]
Thanks for your question.

There is no support for setting that value directly and what you want is not compatible with the underlying Raft consensus mechanism. It will never work with rqlite, so I am closing this issue.
