### ISSUE TITLE
Does the rqlite strong enough to test with jepsen?

### ISSUE THREAD

**Issue by progamer71** [rqlite/rqlite#404]
@otoolep 
This is non issue report.
jepsen is an open source tool to test the correctness of distributed database operations.

For more information:
https://jepsen.io/
https://github.com/jepsen-io/jepsen
https://github.com/jepsen-io/jepsen/blob/master/doc/tutorial

Please share your thoughts
Best regards,
Phanu C.

**Comment by otoolep** [comment]
Short answer is yes, it should be, assuming you use STRONG read consistency. See https://github.com/rqlite/rqlite/issues/94
