### ISSUE TITLE
Add Backup method to the CLI

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#432]
It would be quite useful if the CLI also supported backing up the database. The backup API is outlined here:

https://github.com/rqlite/rqlite/blob/master/DOC/BACKUPS.md

The command should operate like so:
```
$ rqlite
127.0.0.1:4001> .backup <file>
```
When executed the backup API would be called, the data that endpoint returns would be written to `file`. The new command would be hooked in here: https://github.com/rqlite/rqlite/blob/master/cmd/rqlite/main.go#L66

**Comment by eariassoto** [comment]
I can work on this

**Comment by otoolep** [comment]
Thank you @eariassoto
