### ISSUE TITLE
Any plan to support mobile

### ISSUE THREAD

**Issue by damonYuan** [rqlite/rqlite#468]
Go lang is supporting mobile [now](https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-ios) and I think this project will have brighter future if integration into iOS/android is supported.

Do not know if the team has the plan to work on it?

**Comment by otoolep** [comment]
I actually don't see any applications for this on a mobile platform, so am not planning any mobile work, but perhaps I am missing something. What do you have any mind?

**Comment by otoolep** [comment]
Also more general discussions like this are better sent to the Google Group at https://groups.google.com/forum/#!forum/rqlite

**Comment by sum12** [comment]
Actually I see this as I very interesting idea. If we could some how support mobile. 
`rqlite` could become something like  `ContenProvider` (on android) and thus allows other apps to have their `sqlite` dataase automatically "backed-up" or "cloned" to the remote server.


Last time I looked into it. There were issues as the `ContentProvider` api for android was not possible in go-mobile.

**Comment by damonYuan** [comment]
I think sometimes the mobile applications only want some local storage solution especially when offline. For example, restaurant menu application. There might be tens of ipads running the application inside a restaurant, but when a order is placed in one of them, you want all the ipads' data is synchronized.

**Comment by otoolep** [comment]
If I can get around to implementing https://github.com/rqlite/rqlite/issues/470 it might help with this requirement. I am still dubious rqlite is a good match for mobile applications, but interested people can always try. :-)

**Comment by gravypod** [comment]
@otoolep sorry to post on this old issue but it looks like #470 was closed. I found this issue because I have a use case, that I believe is either common or increasing in frequency, that would greatly benefit from this sort of project.

I've worked at a few IOT companies and each one has a very similar subset of problems. They all inevitably need:

1. Light weight storage of data
2. Synchronization (too/from) of state from a company-controlled server
3. Gracefully handling this during intermittent, and sometimes long term, loss of network connectivity

I'm just starting to look at a few databases in this space and rqlite seems very advanced. I was wondering how you felt rqlite might perform in these situations? The features that I've been trying to find in a database are:

1. Read-only completely locally stored tables
2. Write-only eventually synced tables that delete all locally stored data when sent to upstream (drains)
3. Quickly recovering from netsplits

It looks like currently rqlite can be used to accomplish my first goal. I'm assuming with manually written code I can write tools to do my second goal in a slightly hacky way (`select * from drain` then delete the rows after they're persisted in another store) but I'm hoping for a simpler way to do this. 

If you'd like for me to repost this in the google groups page you linked above I'd be more than happy to do that. Thanks very much for your hard work and time!

**Comment by otoolep** [comment]
Could you post to the Google Group? I think this could be an interesting topic, now that rqlite supports non-voter nodes. It may mean it works, but it might not. I would need more info on your setup, which I can learn through a series of questions on a Google Groups thread.

The biggest is question I had is how you expect to do the writes. Even with non-voter nodes, writes still have to go through the leader. Your IoT devices will not be able to write locally, they will still need to write to the leader.

**Comment by gravypod** [comment]
For people trying to follow this discussion I've posted to the google group here: https://groups.google.com/forum/#!topic/rqlite/FPrwjiO9DIE

**Comment by trx222** [comment]
Hi. I also want to ask again for mobile support for following use case: 

We have many apps syncing and displaying data from a server. Like news feed and so things like this. The apps do not change any data so they never sync or send anything back. But if the devices have no or bad network connection the apps still display the last synced data. ( offline first approach )
On server side some scripts fill the databases.

Actually we use couchdb and cloundant sync libraries but they are now deprecaded and will no longer developed. Also this solution hast not the best performance with the sync. So we are looking for an other solution that is faster and stable and offers a way to scale the server side to become high available.

Maybe there is a way to get it working with rqlite?

best regards

**Comment by otoolep** [comment]
If the clients never have to write, perhaps it could be made to work, but there are some practical problems that would need to be overcome. I'm also not sure if rqlite will ever be able to support this use case, I'd need to do more testing to check some things.

Some questions for you:

- presumably the rqlite cluster with read-only nodes is going to be protected somehow, so it's not just exposed to the internet at large. Would you use HTTPS and authorization? If so, what type of authorization would you expect?
- how would new mobile clients learn the address of the rqlite node they could join? Some form of DNS? What authentication and authorization system are you expecting to use, to prevent any random mobile client connecting to your cluster?
- how many mobile clients do you expect to support? rqlite read-only nodes have limits, it's highly unlikely to work for 1000s of nodes at once.

**Comment by otoolep** [comment]
>As so often: it depends. our Apps have a range of 1000 to 1000000 users 

Direct access to the rqlite is never going to work at this scale. rqlite does not have a hard limit, but keeping track of 1000s of nodes, making all changes available that the client has missed, that's beyond its practical capabilities.

**Comment by otoolep** [comment]
You need a layer between rqlite and your edge clients. That layer might able to be stateless, which will make it simpler, but rqlite read-only nodes will not scale to those numbers. The problem of distributing updates to 10,000s+ of edge devices that come and go is a fundamentally different problem that the type of problem rqlite tries to solve. Though using rqlite as your fault-tolerant SQLite-based backend should work quite well. 

At a high-level I would expect an architecture something like the following:
![two-tier](https://user-images.githubusercontent.com/536312/151212105-69644541-0d76-4674-adef-cf0820bcb375.png)

I doubt you would even need that many read-only nodes. If I was building a system such as this, I'd avoid the read-only nodes until I knew I needed them. Doing queries of the rqlite cluster itself from the intermediate layer, with weak consistency, will service 1000s queries per second.

It may be possible to use the underlying Raft streaming-changes system, and repurpose it for this type of application. But it would require significant new programming. Not ruling it out, but it's not coming soon. :-)

**Comment by trx222** [comment]
Yeah I know its not an easy topic, I search a solution for longer time and found today an advice to your lib on my it news pages ;) 
Anyway, I will also check everything, maybe it can help me  in other parts ...

**Comment by otoolep** [comment]
Check out my friend's project, https://github.com/benbjohnson/litestream/issues/8

@benbjohnson is also thinking about read replicas for SQLite databases, but takes a different approach than rqlite with his tool litestream.
