### ISSUE TITLE
Some basic starter questions

### ISSUE THREAD

**Issue by thefonzi** [rqlite/rqlite#495]
Hello, I have had my first look at rqlite and I'm prototyping and testing in Windows/VStudio.
My current projects (.NET) address MySQL/MariaDB or SQLite. And my ORM creates and modifies database, when needed.
Could you give me some help to do the first steps and (if so) tell me, if what I want to do is not possible.
I would like to use rqlite on a few Clients (10 or more) and every Windows Client has his own database that syncs with the other nodes.

I want every client to connect to his local database. Do I need to create a database first in the Shell?

Actually I use these connectionstrings to connect to my databases:
connectionString="XpoProvider=MySql;Server=localhost;User ID=root;Password=pass;Persist Security Info=true;Charset=utf8;Database=myDatabase"/> ;

connectionString="XpoProvider=SQLite;Data Source=myDatabase.db;Journal Mode=WAL;Synchronous=0;Cache=Shared;Temp Store=MEMORY" />

In what manner do I need to modify the CS to connect to rqlite?
Can I connect to rqlite with for example SqliteExpert or MySQL-Workbench? 
Do I need to patch the SQL Statements, if every Client just connects to his local database?

Thanks very much for your help in Advance
Reinhold

**Comment by otoolep** [comment]
I'm happy to help, but would you mind posting your questions to the Google Group? That way everyone can benefit.

https://groups.google.com/forum/#!forum/rqlite

**Comment by otoolep** [comment]
Thanks for posting your question to the Google Group. I answered there.
