### ISSUE TITLE
http/2.0 support

### ISSUE THREAD

**Issue by carr123** [rqlite/rqlite#516]
it seems http2 client is not supported in rqlite. http2 has a considerable performance boost over http1.1,
http.ListenAndServerTLS( )  function in go net/http supports http2 server by default.
so, i recommend you to use  ListenAndServerTLS( ) in rqlited implementation source code.

**Comment by otoolep** [comment]
Thanks for your report.

How do you know rqlite doesn't support HTTP2? Can you be more precise?

**Comment by otoolep** [comment]
From my reading of the docs, by using Go 1.6 or later, you pick up http2 support. This means rqlite supports it.

**Comment by joonas-fi** [comment]
Yes, a recent Go version should bring support for H2 out of the box.

I think @carr123 meant that that there's an issue in how rqlite uses TLS. I don't have actual operational experience with H2 but from the high level details I understand that the only way a HTTP client upgrades to H2 if it's advertised in the TLS stack, specifically the ALPN frame: https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation

> It is needed by secure HTTP/2 connections

If we take a look at rqlite's source code here: https://github.com/rqlite/rqlite/blob/master/http/service.go#L219

We notice that `tls.Listen()` call has no knowledge that what we'll be hosting over the TLS socket is a HTTP application, and therefore the TLS stack wouldn't ever know to advertise for H2 support.

Therefore, I think what we'd need to do is what @carr123 suggested: use `http.ListenAndServeTLS()` to tie TLS and HTTP more tightly to enable H2 support.

I can appreciate the more composable approach that you @otoolep probably strived for in giving either a TCP or TLS listener as an argument to `server.Serve()`, so the server doesn't have to know about the type of the connection it's hosted on. It sounds cleaner and that's probably what I would have done as well - but unfortunately that loses H2 support.

I just now learned this as well myself while studying this ticket, thanks @carr123  :)

**Comment by joonas-fi** [comment]
Another alternative could maybe be to manually configure `NextProtos` member for [tls.Config](https://godoc.org/crypto/tls#Config) to include [h2](https://godoc.org/golang.org/x/net/http2#pkg-constants). This would probably be a simpler code change for rqlite.

**Comment by otoolep** [comment]
Fixed. Better late than never. :-)

Thanks for the suggestion and pointers @joonas-fi @carr123
