### ISSUE TITLE
New Raft consensus system

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#517]
It may be time to change to a different Raft implementation. Instead of the current implementation, the implementation from coreos could be tried. This is available at: https://github.com/coreos/etcd/tree/master/raft

This would take place in a serious of steps:
 - build eraftd, which would be like hraftd, but built on the new implementation. This would be done as a learning exercise. The results would be similar to https://github.com/coreos/etcd/tree/master/contrib/raftexample
 - Profile it for performance. For a fair comparison, hraftd would also need to be profiled.
 - Finally, port rqlite to the coreos system.

**Comment by otoolep** [comment]
Couple of reasons: a) check if performance is any better, and b) as you say, CoreOS' implementation now seems to be more actively maintained and may be better in the longer term.

**Comment by joonas-fi** [comment]
I'm toying around with etcd's Raft, and I found this blog post helpful: http://otm.github.io/2015/05/raft-a-first-implementation/

It's easier to digest than https://github.com/etcd-io/etcd/tree/master/contrib/raftexample which was a bit too much of complicated looking code to start with.

**Comment by otoolep** [comment]
Thanks for that example -- it could be helpful. I agree that the example that comes with etcd's implementation is pretty complicated.

**Comment by joonas-fi** [comment]
Here's another link that I found helpful - a talk about somebody using etcd/raft in their own product: https://www.youtube.com/watch?v=c2RyuTyVHxE&t=798

I found that link from https://www.reddit.com/r/golang/comments/9emakk/should_i_use_etcd_for_this_project_or_write_my/

**Comment by anhldbk** [comment]
@otoolep @joonas-fi forgive about my naive question: 

`rqlite`nodes use `raft` for reaching consensus. So all `rqlite` nodes will contain the same data and no data sharding, right?

**Comment by otoolep** [comment]
>>rqlite nodes use raft for reaching consensus. So all rqlite nodes will contain the same data and no data sharding, right?

Correct.

**Comment by otoolep** [comment]
Not sure why you mentioned hraftd, since you also mention rqlite.

Snapshotting within rqlite depends on two factors:
-- the number of entries outstanding in the Raft log. This is a core part of Raft, and will not go away wit a different implementation. A different implementation may improve this time, but it will never go to zero.
-- the size of the underlying SQLite database. This is specific to rqlite, since rqlite makes a copy of the SQLite database as part of the snapshot operation. It may simply be that rqlite can only practically support databases up to certain size, depending on your hardware. Every database has practical limits, and you may be hitting them. It may also be possible to speed up this phase, but it will require code changes.

**Comment by little-pan** [comment]
@otoolep This means that the SQLite database can't be too big(such as more than 1GB) in rqlite. Is it true?

**Comment by otoolep** [comment]
I don't have absolute numbers, you may be hitting a practical limit for your particular application. 

As for your suggestion, you basically described what a snapshot operation is, as far as the Raft system is. rqlite *already* truncates the log during a snapshot. But a copy of the SQLite database must also be made -- that is where the state represented by the committed log entries is.

**Comment by otoolep** [comment]
Perhaps it's possible to modify the source code, such that the minimal amount of work is done during the snapshot, and more work is done in parallel, unblocking the system. I'd need to check.

**Comment by otoolep** [comment]
Unlikely to happen, too much other work to do instead.
