### ISSUE TITLE
Salute notifications

### ISSUE THREAD

**Issue by gedw99** [rqlite/rqlite#519]
Are these standard sqlite notifications exposed at the golang level.

It's called:

sqlite3_update_hook() interface

I want to build a simple pub sub orchestration layer on top with also a table inside sqlite being my event sourcing table

**Comment by gedw99** [comment]
I should have said choreography layer, not orchestration layer. Friesian slip I guess :(

**Comment by otoolep** [comment]
No, those interfaces are not exposed. Only standard SQLite commands are available.

If this doesn't answer your question, please re-open this issue.
