### ISSUE TITLE
data loss on shutdown?

### ISSUE THREAD

**Issue by donpdonp** [rqlite/rqlite#522]
With rqlite 4.3.0 running in a terminal, I insert 10,000 rows successfully from another terminal, then ctrl-C the rqlited. I start the same rqlited and data folder and the new rows are missing. My guess is that the raft log was not written to before the ctrl-c happened, but im not sure. Is there a 'proper' way to shut down rqlited? Does the rqlited debug log indicate when the raft log has finished replaying on startup?

**Comment by otoolep** [comment]
The Raft system calls fsync() every time it writes to the log (it is built on BoltDB), and before it responds -- what you are experiencing does not sound right. Two things to check:

-- are you sure you're code is waiting for your insertions to return?
-- when you restart the node, are you sure all the logs have been applied the underlying SQLite database? 

I suggest you get familiar with the status API, and examine that at each stage of your test. It will tell you many useful things about how many requests have been received, how many have been committed to the log, applied etc. 

https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by donpdonp** [comment]
startup log: https://gist.github.com/donpdonp/49bffc365e2443eeafaac05a63c65b27

im monitoring raft with `curl --silent http://localhost:4001/status|jq '.store.raft | {state, applied_index, commit_index}`

which starts out with 
```
{
  "state": "Leader",
  "applied_index": "12269",
  "commit_index": "12269"
}
```
I have a node script that does `select count(*) from Location` and it reads `Location 41737 rows`. Then I run the 10,000 insert script. It finishes in about 10 seconds.

At this point the raft index has not moved from 12269. So that seems like a problem?

Once the insert script exits, I re run the node count script and get `Location 51855 rows` so its happy and it seems like the inserts worked.

After a restart of rqlited the logs are https://gist.github.com/donpdonp/b19258f1d89c24618dfffa08a5d63891

raft: Restored from snapshot 1-12240-1530814483047 is the same snapshot as before. applied index is up to 12271, and the select count(*) is back to `Location 41737 rows`.

so im perplexd as to whats going on.

**Comment by donpdonp** [comment]
a little more info from debug/vars shows 
```
{
  "execute_transactions": 0,
  "execution_errors": 5,
  "executions": 5,
  "queries": 10136,
  "query_transactions": 0
}

```

10000 queries but 5 'executions'? perhaps that indicates what you're saying about not waiting for the insert to finish? though if that were the case I would expect count(*) to remain the same.

**Comment by otoolep** [comment]
That is helpful. You are doing 10K *queries*, which implies you're using the wrong endpoint. See https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md

Send your INSERTS to `db/execute`, not `db/query`.

**Comment by donpdonp** [comment]
fantastic. things are working as expected now. thx. makes sense that read-queries are not written to the log.

**Comment by otoolep** [comment]
>>makes sense that read-queries are not written to the log

Not by default, no. But they may be, depending on read consistency levels: https://github.com/rqlite/rqlite/blob/v4.3.0/DOC/CONSISTENCY.md
