### ISSUE TITLE
Could you help understanding the usage of HTTP Port along w/Raft port for joining

### ISSUE THREAD

**Issue by RameshRM** [rqlite/rqlite#525]
I am having hard time following the usage of `http` port and `raft` port, Can u explain and clarify how `http` is used for joining the `ring`

**Comment by RameshRM** [comment]
@otoolep thx, seem like you are pretty active

**Comment by otoolep** [comment]
Can you please send your questions to the rqlite Google Group? https://groups.google.com/forum/#!forum/rqlite
