### ISSUE TITLE
Client Libraries

### ISSUE THREAD

**Issue by RameshRM** [rqlite/rqlite#526]
@otoolep  My runtime is `nodejs` do i need to absolutely use `rqlitejs` client for my communications ? AFAIK , `rqlitejs` abstracts the `http ` calls and returns a `promise`, I am not planning to use `rqlitejs` rather use my own `http client` implementation, Pls advise if thats a right choice

**Comment by otoolep** [comment]
The rqlite API is HTTP-based. You can access that API anyway you want.

https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md

**Comment by otoolep** [comment]
So write your own HTTP client if you want.
