### ISSUE TITLE
Replace use of now() with absolute timestamp

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#536]
Since rqlite performs statement-based replication, time-like function may result in different values on each node. One way to work around this would be for the receiving node (or leader) to resolve the value of the time-like function to an absolute value before broadcasting the command.

https://www.sqlite.org/lang_datefunc.html

This would require rqlite to parse all incoming SQLite statements, which would also be a key part of solving https://github.com/rqlite/rqlite/issues/263

**Comment by otoolep** [comment]
>>nodes 1 and 2 succeed (therefore reaching Raft quorum), but node 3 had temporary I/O error, resulting in a rollback

This would be bad, and rqlite would not deal well with this, because each SQLite database would be in a different state. This is probably another reason to use an in-RAM database, since IO errors are (presumably) much, much less likely -- perhaps practically never going to happen. The good news is that you could recover by removing the node that suffered the IO error, and adding a new node, since the Raft log is the authoritative record.

>>I'm just guessing but I think that Raft semantics mean that the only way for node 3 to recover is to retry the transaction to catch up with official Raft state

Yes, that would be the case, but rqlite does not do that right now. It could be coded to retry if the error is truly temporary, and is returned clearly as this. Do you know if this is the case.

**Comment by joonas-fi** [comment]
Thanks for responding! Oh wow, I didn't even realize that rqlite's SQLite database is in RAM by default (with disk option) :)

Using RAM-only SQLite database probably takes care of the I/O error handling issue.

However I'm interested.. if I were to use disk and encounter write I/O error, what would happen? You said "rqlite would not deal well with this" - does this mean that the node goes offline (maybe it won't accept new Raft requests or simply `panic()`), but the other Raft members will keep on partying as long as the quorum exists (2/3 nodes online)?

The worst case scenario I was fearing of was that when an I/O error occurrs and the transaction is rolled back, but the AUTOINCREMENT counter is not rolled back (this of course would be SQLite's internal design issue), and if the Raft flow simply retries applying the Raft log entry, this could now succeed and result in the nodes disagreeing on what the id of this new row is, even though at Raft level everything is peachy. This would not be good.

However, SQLite seems to maybe work in an optimal way (w.r.t. use case for rqlite): https://stackoverflow.com/questions/27947712/sqlite-repeats-primary-key-autoincrement-value-after-rollback

**Comment by otoolep** [comment]
Depending on whether the command could work on a retry, the node might be OK. But the node doesn't panic, it simply fails to apply the log entry. But it is possible to leave the SQLite database in the state you outline -- where the AUTOINCREMENT is now in a different state on 1 node out of 3, which would not be good. I don't have a good answer for you, but I agree it's an issue -- thanks for pointing out. I'll need to think about this, and see if there is a rock-solid answer.

The behaviour of the underlying SQLite source code might help, as you say, but I'd need to check.

**Comment by dan-blum** [comment]
There seem to be more serious issues with the use of "now" than lack of synchronization between nodes. Steps to reproduce:

1. Start rqlited.
2. Start the rqlite client and issue these statements:
       create table foo(id integer primary key, ts datetime);
        insert into foo(ts) values(datetime('now'));
    (repeat the latter a few times with a few seconds' delay)
       select * from foo;
 3. Stop rqlited and restart it.
 4. In the client do
        select * from foo;
     again - you will see that all the ts values have changed to the time you restarted rqlited.

This appears to happen with the on-disk database as well as the in-memory database, but I haven't spent a lot of time playing around with the on-disk database yet so possibly there is a way to make that work (it seems to be overwriting what's there using the raft log).

**Comment by otoolep** [comment]
What you describe is exactly what I would expect with the current state of rqlite. The statements containing 'now' are stored as-is in the Raft log, so are applied each time the node starts. This will be fixed once I complete the work to address this issue. But, as per the README, use of non-deterministic statements are not currently supported by rqlite.
https://github.com/rqlite/rqlite/blob/master/README.md#limitations


    On Wednesday, June 8, 2022, 03:49:41 PM EDT, dan-blum ***@***.***> wrote:  
 
 


There seem to be more serious issues with the use of "now" than lack of synchronization between nodes. Steps to reproduce:
   
   - Start rqlited.
   - Start the rqlite client and issue these statements:   
create table foo(id integer primary key, ts datetime);   
insert into foo(ts) values(datetime('now'));   
(repeat the latter a few times with a few seconds' delay)   
select * from foo;
   - Stop rqlited and restart it.
   - In the client do   
select * from foo;   
again - you will see that all the ts values have changed to the time you restarted rqlited.

This appears to happen with the on-disk database as well as the in-memory database, but I haven't spent a lot of time playing around with the on-disk database yet so possibly there is a way to make that work (it seems to be overwriting what's there using the raft log).

**Comment by otoolep** [comment]
Might follow the rewrite pattern here: https://github.com/tsuna/gorewrite/blob/master/rewriter.go

**Comment by otoolep** [comment]
Fixed in 8.33.0.

**Comment by otoolep** [comment]
See https://rqlite.io/docs/api/non-deterministic/#date-and-time-functions for full details.
