### ISSUE TITLE
Two questions: multi data center and in-memory only

### ISSUE THREAD

**Issue by didip** [rqlite/rqlite#540]
First of all, thank you for creating rqlite.

1. Has anyone run rqlite across multiple data center?

2. Is it possible to run rqlite in memory only? I saw this ticket: https://github.com/rqlite/rqlite/issues/58. But I have not seen much documentation about it. For example, can I limit how much memory it uses, etc.

The reason I asked is because I have a need to store temporary, small size data, in memory across multiple data center.

**Comment by didip** [comment]
I see that it uses sqlite ":memory:" option. I don't think sqlite has an option to limit maximum ram used. I believe it also does not do periodical persistence to disk.

**Comment by otoolep** [comment]
1: I have -- see http://www.philipotoole.com/rqlite-v3-0-1-globally-replicating-sqlite/
2: rqlite runs by default in RAM, but the log is stored on disk. Check the README for details.

**Comment by otoolep** [comment]
Correction: see https://github.com/rqlite/rqlite/blob/master/DOC/IN_MEMORY_DB.md

**Comment by otoolep** [comment]
Anywhere from 10 to 100 inserts a second. Depends a lot on your network and disks.

I suggest further discussion should take place on the rqlite Google Group.
