### ISSUE TITLE
grpc API

### ISSUE THREAD

**Issue by ghost** [rqlite/rqlite#545]
I saw in v5 the new query and write API.
What about using GRPC ?
Then you get protocols buffers and standard Rest / JSON from the code gen.
It would also give you clients in the various languages GRPC supports.

Maybe this is something for latter too until your API gets more stable...

**Comment by otoolep** [comment]
Yes, this is something I'm considering for v5. v5 development is proceeding slowly though, due to other commitments I have, but I think it's a good idea.

**Comment by little-pan** [comment]
keep it simple! grpc maybe complicated. And I found many bugs in rqlite v5 http api implementation.

**Comment by otoolep** [comment]
>> And I found many bugs in rqlite v5 http api implementation

I commented on the single issue you raised with that code, but don't actually see any issue with it. Perhaps I am missing something.

**Comment by little-pan** [comment]
@otoolep Those problems happend when you connect to any rqlited follower node by using rqlite command then execute any SQL statement.

**Comment by otoolep** [comment]
SEE https://github.com/rqlite/rqlite/issues/350
