### ISSUE TITLE
-raft-timeout not working

### ISSUE THREAD

**Issue by phf** [rqlite/rqlite#549]
Trying to supply, for example, "-raft-timeout 2s" to rqlited results in an error message:

failed to open store: new raft: Election timeout must be equal or greater than Heartbeat Timeout

I believe the simplest fix would be to set config.ElectionTimeout to the same value as config.HeartbeatTimeout in store/store.go#raftConfig() but maybe there's a "guideline" somewhere what the actual relationship between those two values should be for Raft. (In any case, adding that line I was able to use "-raft-timeout 2s" to make things less noisy in my docker-compose test cluster. Your mileage may vary.)

**Comment by otoolep** [comment]
What version are you running?

**Comment by phf** [comment]
I cloned the git repo using go get. Previously I used the docker image for 4.2.2 but that had the same problem. I first tried the git repo because I thought maybe the "bug" had been fixed. In my build script I now have

sed -i '/config.HeartbeatTimeout = s.HeartbeatTimeout/a config.ElectionTimeout = s.HeartbeatTimeout' store/store.go

to add the setting for ElectionTimeout. As I said, I am not sure that's 100% kosher regarding Raft but it fixed my issues.

**Comment by otoolep** [comment]
The issue you referenced was addressed in version 4.4.0, via [a new flag](https://github.com/rqlite/rqlite/commit/2e91858e1ee0feee19f4c20c6f56a21261bcd44a) allowing you to set both flags. You'll need to roll your own Docker image however, for that version.
