### ISSUE TITLE
Initializing schema

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [rqlite/rqlite#552]
I am using this in a Docker project, but I would like to initialize the schema as part of the Docker build steps.

Currently I have a script that launches `rqlited` in the background and then uses `curl` to execute the `CREATE TABLE` commands. I think I am running into persistence problems because the server comes down and then the tables are gone.

Is there a supported way of doing this?

**Comment by otoolep** [comment]
You say the service "comes down" and then tables are gone. Gone from where? I assume you're restarting the node. If so, where is your Raft log being stored? I.e. what is your data path? And is it on file storage that lives beyond the lift of a node's process?

**Comment by aidan-plenert-macdonald** [comment]
I am building [this Dockerfile](https://github.com/rqlite/rqlite-docker/blob/master/4.2.2-alpine/Dockerfile#L53) (just different base image due to my architecture),

```
# https://github.com/rqlite/rqlite-docker/blob/master/4.2.2-alpine/docker-entrypoint.sh
FROM balenalib/raspberry-pi-golang as builder

# Setup the Environment
ENV GOPATH=/root/go \
    PATH=${PATH}:/usr/local/go/bin:/root/go/bin \
    VERSION_TAG=v4.2.2 \
    LANG=C.UTF-8

# Install Build Deps
RUN apt-get update \
    && apt-get install -y \
         build-essential \
         git \
         wget \
    && rm -rf /var/lib/apt/lists/*

# Build the rqlite binary
RUN mkdir -p /root/dist ${GOPATH} \
    && cd ${GOPATH} \
    && mkdir -p src/github.com/rqlite \
    && cd src/github.com/rqlite \
    && git clone https://github.com/rqlite/rqlite \
    && cd rqlite \
    && git checkout -b alpine-${VERSION_TAG} tags/${VERSION_TAG} \
    && branch=`git rev-parse --abbrev-ref HEAD` \
    && commit=`git rev-parse HEAD` \
    && buildtime=`date +%Y-%m-%dT%T%z` \
    && go get -d ./... \
    && go install -ldflags="-X main.version=${VERSION_TAG} -X main.branch=$branch -X main.commit=$commit -X main.buildtime=$buildtime" ./...

FROM builder

# Setup the Environment
ENV GOPATH=/root/go \
    PATH=${PATH}:/usr/local/go/bin:/root/go/bin \
    LANG=C.UTF-8 \
    RQLITE_VERSION=4.2.2

# Copy Assets from Go build
COPY --from=builder /root/go/bin/rqlited /bin/rqlited
COPY --from=builder /root/go/bin/rqlite /bin/rqlite

# Create Volume
RUN mkdir -p /rqlite/file
VOLUME /rqlite/file

# Expose Ports
EXPOSE 4001 4002

COPY schema.sh .
RUN /bin/bash schema.sh

CMD ["rqlited", "-http-addr", "0.0.0.0:4001", "-raft-addr", "0.0.0.0:4002", "/rqlite/file/data"]
```

The schema.sh has the following
```
#!/bin/bash

set -e
set -x

rqlited -http-addr 0.0.0.0:4001 -raft-addr 0.0.0.0:4002 /rqlite/file/data &
RQLITED_PID=$!
sleep 5s

wget -qO- http://localhost:4001/db/execute?pretty \
     --header "Content-Type: application/json" \
     --post-data='[
  "CREATE TABLE runs (tag TEXT, sleep INTEGER)",
  "CREATE TABLE data (tag TEXT, seconds INTEGER, value REAL)"
]'

kill -n 1 $RQLITED_PID
```

That script succeeds in the build process,
```
Step 13/14 : RUN /bin/bash schema.sh
 ---> Running in 74bc1b76d90f
+ RQLITED_PID=7
+ sleep 5s
+ rqlited -http-addr 0.0.0.0:4001 -raft-addr 0.0.0.0:4002 /rqlite/file/data
    ...
2019/05/01 02:58:12 [INFO] raft: Election won. Tally: 1
2019/05/01 02:58:12 [INFO] raft: Node at [::]:4002 [Leader] entering Leader state
2019/05/01 02:58:12 [DEBUG] raft: Node [::]:4002 updated peer set (2): [[::]:4002]
[rqlited] 2019/05/01 02:58:12 set peer for [::]:4002 to 0.0.0.0:4001
[http] 2019/05/01 02:58:12 service listening on 0.0.0.0:4001
+ wget -qO- 'http://localhost:4001/db/execute?pretty' --header 'Content-Type: application/json' '--post-data=[
  "CREATE TABLE runs (tag TEXT, sleep INTEGER)",
  "CREATE TABLE data (tag TEXT, seconds INTEGER, value REAL)"
]'
{
    "results": [
        {},
        {}
    ]
}+ kill -n 1 7
```

With the image launched, querying fails with table not found
```
root@13f8eecd9526:/go# ls -lth /rqlite/file/data/
total 32K
-rw------- 1 root root  32K May  1 02:36 raft.db
-rwxr-xr-x 1 root root   14 May  1 02:36 peers.json
drwxr-xr-x 2 root root 4.0K May  1 02:36 snapshots
root@13f8eecd9526:/go# wget -qO- "http://localhost:4001/db/query?q=SELECT * FROM runs"
{"results":[{"error":"no such table: runs"}]}
```

**Comment by otoolep** [comment]
I am far from a Docker expert, but it's pretty clear what is happening. The changes you make to the Raft log (stored in raft.db) during the build process is not getting packaged as you think. Clearly the file you create at `/rqlite/file/data/raft.db` is not the same file as when you launch the image and query the node.

**Comment by otoolep** [comment]
The key thing is that schema changes to the rqlite node are be stored in raft.db. If you are not packaging your image such that the modified raft.db as part of your image, your rqlite node will come up empty.

**Comment by aidan-plenert-macdonald** [comment]
@otoolep My concern was that perhaps the way I am bringing the `rqlited` process down is not permitting the data to get committed to disk. Is there any guidance on the exit signal I should pass to rqlited? Like SIGHUP, SIGKILL, SIGSTOP, etc.

**Comment by otoolep** [comment]
That is not possible. The response from the HTTP API does not come back until your request has been committed to the Raft log. 

If in doubt, simply query the node until you see the table in the database and then kill the node. There may be a few milliseconds (no more than 20 or 30) before changes that have been committed to the Raft log are reflected in the SQLite database. But the Raft log will have the changes and that's what matters. What's probably going on is that what you think is persistent disk is not.
