### ISSUE TITLE
Cluster discovery using DNS

### ISSUE THREAD

**Issue by gregorybrzeski** [rqlite/rqlite#554]
Would you consider cluster discovery using DNS and SRV records ?

Etcd is doing this for a while: 
https://coreos.com/etcd/docs/latest/op-guide/clustering.html#dns-discovery

**Comment by otoolep** [comment]
Yes, I would, but it's matter of finding the time. PRs welcome!

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite-disco-clients/pull/9

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/pull/979

**Comment by otoolep** [comment]
Will be available in 7.20.
