### ISSUE TITLE
User config permissions not honored on windows

### ISSUE THREAD

**Issue by wakwanza** [rqlite/rqlite#555]
Security  settings on the auth config fails to enforce the permissions for the users set in the auth list for their respective levels.

rqlite version                           : Tested 5.0 
OsName                                   : Microsoft Windows Server 2016 Standard
OsVersion                                 : 10.0.14393

**config.json**
[
{"username": "admin","password":"1234567","perms":["all"]},
{"username": "join","password":"1234567","perms":["join","status"]}
]

**startup string**
 .\rqlited.exe -http-addr localhost:4001 -raft-addr 0.0.0.0:4011 -auth config.json nnode.1

**Result**
Users do not get the permissions level specified in the config.
expectation is for admin with 'all' to be able to run all comands , and user join with 'join,status' to be able to run those two commands.

PS C:\> .\rqlite.exe -u join:1234567
127.0.0.1:4001>
127.0.0.1:4001> .schema
ERR! unauthorized
127.0.0.1:4001> .status
ERR! unauthorized
127.0.0.1:4001> exıt
bye~
PS C:\> .\rqlite.exe -u admin:1234567
127.0.0.1:4001>
127.0.0.1:4001> .schema
+-----+
| sql |
+-----+
127.0.0.1:4001> .status
ERR! unauthorized

127.0.0.1:4001> exit

Without the auth status can be queried by logging into the cli with no passwords/username.
([status.txt](https://github.com/rqlite/rqlite/files/3157013/status.txt))

**Comment by otoolep** [comment]
Could you try building the code on this branch: https://github.com/rqlite/rqlite/tree/4.3.0-patch

**Comment by wakwanza** [comment]
Sure currently wrestling with go-sqlite3 build errors will try and sort them out, continue build and report back with findings,

**Comment by otoolep** [comment]
Actually, you could just download the 4.5.0 build from here: https://ci.appveyor.com/project/otoolep/rqlite/build/artifacts

**Comment by otoolep** [comment]
I'm going to assume this is not an issue on 4.5.0.
