### ISSUE TITLE
multiple database support

### ISSUE THREAD

**Issue by fengzhenqiong** [rqlite/rqlite#557]
is there any plan to add multiple database support?

in a real project there is little chance for only a single database so maybe this will be something useful i think, after all, RQLite is a distributed relational databse.

you can connect to an RQLite cluster, get cluster information (databases, nodes, etc). you can also specify the database you want to connect to when establish connection.

database creation/deletion/selection.

**Comment by otoolep** [comment]
It's not a bad idea, but SQLite doesn't natively support multiple databases, and I am reluctant to build such a layer into rqlite. This is not something I plan to add.
