### ISSUE TITLE
Why not the snapshot is the sqlite database itself?

### ISSUE THREAD

**Issue by little-pan** [rqlite/rqlite#560]
In current rqlite version, the snapshot and SQLite database separated on disk mode. But actually, they are the same thing! 
When they are separated, it's very bad. 1) When switch memory to disk mode, it must restore snapshot to memory and then dump whole database into disk.  2) And in disk mode, really the SQLite database is a snapshot already, but rqlite still takes snapshot periodically and occupies abundant memory and makes disk access flood, then the whole rqlite cluster becomes unavailable.
It's possibly that implementing a FSM, which merges the SQLite database and snapshot into one.

**Comment by otoolep** [comment]
I don't completely follow you. Are you talking about on-disk mode or not?

When running in default mode, the SQLite database is in-RAM, it never consumes any disk. The Raft log is on disk of course. When a snapshot is taken, the in-memory database is written to disk and becomes the snapshot. What is the problem with that?

**Comment by otoolep** [comment]
If we move the system to on-disk mode, then yes, it seems possible we could use the SQLite database as the snapshot with some careful programming. However, this would mean a few things:

-- twice the disk IO, relative to RAM. My testing shows that disk IO is the single biggest performance bottleneck so we want to minimize that.
-- the SQLite database itself would become a key part of the system, and could never be deleted. This could make the system more difficult to understand, perhaps more difficult to reason about, not sure.

In-RAM mode could never be used again, in this case.

**Comment by little-pan** [comment]
Yes, only in disk mode. No twice disk IO, no any IO operation when taking snapshot, because of the snapshot really is the SQLite database and vice versa.
And in memory mode, we can take the snapshot as an actual SQLite database.

**Comment by otoolep** [comment]
In disk mode there is twice the IO, because each SQLite change needs to be made in the Raft log *and* the SQLite database. That's what I mean.

Is taking the snapshot that big an issue for you? What are you seeing?

**Comment by little-pan** [comment]
When database reaches 1g, 2g, ..., taking snapshot is very long and http api service unavailable, the whole rqlite cluster becomes unstable, and restoring from snapshot also takes long time on bootstrap in my test.

**Comment by otoolep** [comment]
OK, perhaps some changes can be made that will improve this.

However, every software system has its limitations. rqlite was not explicitly designed to store large amounts of data. It's a somewhat simple, but very reliable, system for a specific range of applications. Loading 1GB+ into may pushing it beyond its capabilities. I can't guarantee what you are experiencing will be fixed.

**Comment by little-pan** [comment]
@otoolep  Replicating snapshot between peers is a problem if the snapshot is the sqlite database itself. So I close this issue. But the methods such Snapshot()/Persist()/Restore() in store package should be optimized by using io.ReadCloser  instead of large []byte.

**Comment by otoolep** [comment]
>>@otoolep Replicating snapshot between peers is a problem if the snapshot is the sqlite database itself. 

This happens only if a node joins the cluster, which should not happen that often. rqlite is not targeted at applications which need to support a high rate of node changes.
