### ISSUE TITLE
OS X release v4.5.0 rqlited binary is missing

### ISSUE THREAD

**Issue by mgmm13** [rqlite/rqlite#562]
Hi, I tried downloading the v4.5.0 release for OS X. 
Upon downloading and running the tar command, I only get the rqlite file. 

See logs below:
``` bash
$ curl -L https://github.com/rqlite/rqlite/releases/download/v4.5.0/rqlite-v4.5.0-darwin-amd64.tar.gz -o rqlite-v4.5.0-darwin-amd64.tar.gz
$ ls -l rqlite-v4.5.0-darwin-amd64.tar.gz
-rw-r--r--  1 user  group  3348806 Jun 19 13:38 rqlite-v4.5.0-darwin-amd64.tar.gz
$ tar xvfz rqlite-v4.5.0-darwin-amd64.tar.gz
x rqlite-v4.5.0-darwin-amd64/
x rqlite-v4.5.0-darwin-amd64/rqlite
$ cd rqlite-v4.5.0-darwin-amd64
$ ./rqlited ~/node.1
-bash: ./rqlited: No such file or directory
```

**Comment by otoolep** [comment]
Yes, you are right, the image is bad. Sorry about that.

I suggest you download https://github.com/rqlite/rqlite/releases/tag/v4.3.1, it's very close in functionality and OSX is available.

**Comment by little-pan** [comment]
@mgmm13 You can build rqlited or rqlite from rqlite src by executing "go build github.com/rqlite/rqlite/cmd/rqlited"

**Comment by mgmm13** [comment]
@otoolep that is noted. I did try v4.3.1 and got it working. Thanks!
I do have a follow-up question: Is there any chance that rqlite supports sqlite extensions? i.e. I tried restoring a dump from an existing sqlite database with virtual tables enabled for FTS5 (extension for full text search). Upon loading it, the virtual tables are in the schema, but when I tried querying from the virtual tables, rqlite says that the said virtual tables do not exist. 

@little-pan noted on that, thanks!

**Comment by otoolep** [comment]
@mgmm13 -- are you talking about this feature: https://www.sqlite.org/loadext.html ?

**Comment by little-pan** [comment]
@mgmm13 go-sqlite3 supports this fts5 extension. We can implements your demand by compiling rqlite with fts5 sqlite3 extension.

**Comment by otoolep** [comment]
Thanks @little-pan -- if you can share the command line to do this, I'll add it to the official rqlite documentation.

**Comment by little-pan** [comment]
@otoolep I had compiled rqlited with sqlite3 fts5 extension by executing the command:
``shell
go build --tags "fts5" github.com/rqlite/rqlite/cmd/rqlited
``
# A simple example
``SQL
127.0.0.1:4001>create virtual table repo using fts5(id, full_name, description, html_url)
127.0.0.1:4001> .tables
+--------------+
| name         |
+--------------+
| repo         |
+--------------+
| repo_data    |
+--------------+
| repo_idx     |
+--------------+
| repo_content |
+--------------+
| repo_docsize |
+--------------+
| repo_config  |
+--------------+
127.0.0.1:4001> insert into repo(id, full_name)values(1, 'rqlite');
127.0.0.1:4001> insert into repo(id, full_name)values(1, 'github.com rqlite');
127.0.0.1:4001> select *from repo where full_name match 'rqlite';
+----+-------------------+-------------+----------+
| id | full_name         | description | html_url |
+----+-------------------+-------------+----------+
| 1  | rqlite               | <nil>           | <nil>    |
+----+-------------------+-------------+----------+
| 1  | github.com rqlite | <nil>       | <nil>    |
+----+-------------------+-------------+----------+
``

**Comment by mgmm13** [comment]
@little-pan Yes that's correct. I've tried mattn go-sqlite3 for the fts5 and it works by specifying the tags during go build / install. I'll try that command and give you feedback if it works on my end. Thank you so much.

**Comment by little-pan** [comment]
@mgmm13 OK

**Comment by mgmm13** [comment]
@otoolep @little-pan I've tried recompiling with the tags in rqlited and it works when you create the virtual table upon running rqlite. Although it still does not recognise restored virtual tables from a prior existing sqlite dump.
Thank you so much for your help!

**Comment by little-pan** [comment]
@mgmm13 What happens in rqlite when you restore your sqlite dump? version issue? Is here any rqlite error info or log?
