### ISSUE TITLE
Listen on unix socket, and/or integrate directly as a Go module

### ISSUE THREAD

**Issue by teran-mckinney** [rqlite/rqlite#568]
Hi,

Two different questions. I may want to have multiple rqlite databases per server. It would be nice to not have to manage users and ports for them so much.

Is there a way to have it listen on a unix socket for local API access?

Secondly, is there a straightforward way to import rqlite and write to a database directly like that? That way the database could be integrated into the web application and all of the servers hosting a particular site could have both together in one binary and your own configuration file for additional nodes, etc.

Thank you!

-Teran

**Comment by otoolep** [comment]
There is no unix socket support. How is managing ports "not nice"? It's not that inconvenient, right?

Importing rqlite? If you mean can the core code of rqlite be stripped out, independent from the HTTP API? Yes, that could be done, if you're an experienced Go programmer. It wouldn't be super-difficult, but it's not trivial. I would do it to the v4 branch, not v5, which is heavily WIP.

**Comment by teran-mckinney** [comment]
Ok, thank you! I appreciate you getting back to me.

Unix socket model:

rqlited runs under systemd as an @ service, with sockets under /run/rqlite-thing. Now I don't need to handle arbitrary port numbers or authentication, I just pair my service using rqlited with that account. Just have to deal with filesystem permissions which can be solved on the fly.

Current model:

Arbitrary port numbers per rqlited, arbitrary authentication per rqlited.

Just seems like a simpler model to me that would be fairly simple to integrate. I can try to patch this in if you are open to it. I'm not a very experienced go programmer, so doing the import rqlite solo seems a bit much for me.

**Comment by otoolep** [comment]
Yeah, I plan to keep the API strictly over HTTP, so you'll have to fork if you want to add it.

**Comment by teran-mckinney** [comment]
Pretty sure you can talk HTTP over a unix socket but I understand if it's not something you want to add. I think it'd be tens of lines.

**Comment by zmedico** [comment]
Apparently some things express this as a `http+unix://` URL scheme. I found some examples here:

https://stackoverflow.com/questions/26964595/whats-the-correct-way-to-use-a-unix-domain-socket-in-requests-framework

**Comment by zmedico** [comment]
It's possible to implement this by running rqlited/rqlite in private network namespaces created by the `unshare --net` command, and then using `socat` instances to proxy between private network namespaces and a unix socket.

**Comment by teran-mckinney** [comment]
I was more thinking about that for local communications (application to rqlited) than rqlited to rqlited, but that is certainly another option. Thanks for sharing that.

**Comment by james-lawrence** [comment]
i'd be very interested in this as an importable module, have any points where to start looking to do the work?

**Comment by teran-mckinney** [comment]
@james-lawrence since this issue was posted, dqlite went to 1.0.0. It might be more what you're looking for.

rqlite seems to be more of a traditional database whereas dqlite is something you integrate.

https://github.com/canonical/go-dqlite/

**Comment by otoolep** [comment]
No plans to work on this.

**Comment by zmedico** [comment]
Maybe I'll pick this up at some point. I've found a nice example in frp, which explicitly supports TCP only at its core. Instead of polluting the core, plugins make it possible to substitute alternative implementations for listeners and handers. For example, this unix_domain_socket plugin currently implements a handler, but not a listener:

https://github.com/fatedier/frp/blob/master/pkg/plugin/client/unix_domain_socket.go

I'm working on adding the missing listener support for this plugin now. In frp there are three different protocols, and I'm updating each one so that the unix_domain_socket plugin can be used as a substitute for a TCP listener.
