### ISSUE TITLE
No issues tracker for gorqlite

### ISSUE THREAD

**Issue by teran-mckinney** [rqlite/rqlite#569]
I'd like to open an issue for [gorqlite](https://github.com/rqlite/gorqlite) but it's a fork and there's no issues tracker there.

Would it be possible for you to enable that?

Thank you!

**Comment by teran-mckinney** [comment]
So I don't forget what I wanted to open an issue about, it's about :memory: support just like how it's in [pyrqlite](https://github.com/rqlite/pyrqlite/blob/9da1eb12c66e73b425b70523984517ec744d3a5a/src/pyrqlite/connections.py#L62).

**Comment by otoolep** [comment]
No plans to fix this right now.
