### ISSUE TITLE
Document about how to compile rqlite

### ISSUE THREAD

**Issue by weenxin** [rqlite/rqlite#594]
## Context

```
go mod vendor

go build ./cmd/rqlitd/...
```

will output errors :

```
store/store.go:210:16: undefined: raft.PeerStore
```

## Document

We need a document about how to compile rqlite

**Comment by otoolep** [comment]
It already exists.

https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite

**Comment by weenxin** [comment]
@otoolep  Thanks

**Comment by otoolep** [comment]
If there is someway the build process should be improved, I'm open to it, but one of the secondary goals for rqlite is a super-easy build process. That may change in the future, if the system becomes more complex.  Dependencies are not really handled either, except for the Hashicorp Raft system.
