### ISSUE TITLE
The minimum version of Windows that AppVeyor builds are compatible with 

### ISSUE THREAD

**Issue by mamift** [rqlite/rqlite#622]
Hi,

What minimum version of Windows are the AppVeyor builds compatible with ([https://ci.appveyor.com/project/otoolep/rqlite/history](https://ci.appveyor.com/project/otoolep/rqlite/history))? I couldn't find anything on AppVeyor or inside this git repo about it.

I downloaded + extracted the .zip file from AppVeyor and I'm trying to run it on Windows 10 x64 1607 and nothing seems to work. After trying to launch rqlited.exe it actually seems to delete itself (the .exe file just disappears).

Edit: I'm referring to the 5.* series of releases.

**Comment by otoolep** [comment]
I don't have much practical experience with the Windows version -- I leave that up to appveyor. I find it strange that it "deleted itself", that doesn't make any sense.

If you want to be sure it'll work for you, I suggest you just build it yourself on Windows. It should be quite easy. Just download Go for Windows (from the official Go site), clone the repo, and follow the [build instructions](https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite).

**Comment by otoolep** [comment]
The appveyor config files is here: https://github.com/rqlite/rqlite/blob/master/appveyor.yml
