### ISSUE TITLE
what would happen when data grows and someday exceeds memory size?

### ISSUE THREAD

**Issue by liufanghua2012** [rqlite/rqlite#626]
need i do anything for data migration in this case?

**Comment by otoolep** [comment]
Depending on your data set, it would need to grow very large. The OS on Linux, for example, will page to disk.

Just add nodes with more memory, and then remove the nodes with less memory. See https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md

Anyway, it doesn't really matter. What's in memory is not important to data persistence.
