### ISSUE TITLE
is Bulk API support atomic operations?

### ISSUE THREAD

**Issue by liufanghua2012** [rqlite/rqlite#630]
Can all SQL commands contained in one http bulk API request be executed in an atomic way?
For example, in the following case: 
curl -XPOST 'localhost:4001/db/query?pretty' -H "Content-Type: application/json" -d '[
    "SELECT * FROM foo",
    "SELECT * FROM bar"
]'

when "SELECT * FROM foo" is executing, someone else try to access rqlite database at the same time, with the following command:
curl -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d "[
    \"INSERT INTO bar(name) VALUES('fiona')\",
    \"INSERT INTO bar(name) VALUES('sinead')\"
]"

Is it possible that rqlite executes "INSERT INTO bar(name) VALUES('fiona')" instead of "SELECT * FROM bar"?

**Comment by otoolep** [comment]
If wish the bulk transaction to be atomic, simply set the transaction flag as per the docs.

https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md#transactions

**Comment by otoolep** [comment]
However, there is no real need to set the transaction flag, because a bulk operation is processed as a single change in the Raft log, meaning no other request will be interleaved with it.

So the short answer to your question is "no, it's not possible".

**Comment by otoolep** [comment]
I have added more details to the bulk operation documentation.

https://github.com/rqlite/rqlite/blob/master/DOC/BULK.md
