### ISSUE TITLE
The documentation does not explain how to create node.crt pair

### ISSUE THREAD

**Issue by warwickchapman** [rqlite/rqlite#632]
The documentation only explains how to create the X509 HTTP certificate but not the node to node SSL certificate.  The documentation refers to `node.crt` and `node-key.pem` as the "node-to-node certificate and key" but does not explain how to create them.

**Comment by otoolep** [comment]
Actually it does: https://github.com/rqlite/rqlite/blob/master/DOC/SECURITY.md#https-api

I'll make it clearer.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/commit/afbf7d4477d923345aa6ed3d32e485aa7618bcc3
