### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by mysticaltech** [rqlite/rqlite#638]
Does rqlite support Kubernetes? I'm not seeing any mention of it. It would seem obvious that such a project should have a way to run on the world's top distributed computing platform.

**Comment by otoolep** [comment]
Can you define "support Kubernetes"? rqlite is available as a containerized application, which Kubernetes is built to manage.

https://github.com/rqlite/rqlite-docker

You can also find some in-development k8s operators here: https://github.com/jmccormick2001/rqlite-operator

**Comment by mysticaltech** [comment]
Ah perfect, thanks!
