### ISSUE TITLE
Remove all cluster aspect from rqlite for single instance purpose

### ISSUE THREAD

**Issue by al-sabr** [rqlite/rqlite#642]
Greetings everybody!

I realized that I didn't need any of the distributed aspect of rqlite so I decided to try to remove/implement the features that I talked about with @otoolep.

You can follow the latest exchanges about our discussion : https://github.com/rqlite/rqlite/pull/493

I will need some more guidance from other people who know the code better than me.

I hope we could modularize rqlite so that both can be provided as solution.

Cheers

**Comment by otoolep** [comment]
Thanks for opening this issue, but this is not something I'm going to do in this repo, so don't want this issue open here. The best thing to do is to fork this repo into your own GitHub account, and start development there.

You may also wish to mail the rqlite Google Group, and see if anyone else wants to help.

**Comment by otoolep** [comment]
https://groups.google.com/forum/#!forum/rqlite

**Comment by gdeverlant** [comment]
I think that discussing this here is appropriate because the question that I have concerns how is the functioning of the queries and executions.

With links and references it makes more sense to reopen this thread.

I don't know now what to do because I am lost and don't no where the hell are transactions created in the RAFT.

https://github.com/gdeverlant/rqlite/blob/a2f5259836b9f7ef189a69f2568343ef2c137b6b/store/store.go#L567

**Comment by otoolep** [comment]
OK, opened.

**Comment by gdeverlant** [comment]
Thank you really kind for your support.

**Comment by gdeverlant** [comment]
I am trying to compile my implementation but getting this error:

```
PS G:\programming\go\rqlite\cmd\rqlited> go run .\main.go
# github.com/rqlite/rqlite/http
..\..\http\service.go:466:81: too few values in store.ExecuteRequest literal
..\..\http\service.go:694:74: too few values in store.ExecuteRequest literal
```

Having any advice?

**Comment by gdeverlant** [comment]
Having the same problem when I try to debug the main.go file for rqlited.

```
# github.com/rqlite/rqlite/http
..\..\http\service.go:466:81: too few values in store.ExecuteRequest literal
..\..\http\service.go:694:74: too few values in store.ExecuteRequest literal
exit status 2
Process exiting with code: 1
```

**Comment by gdeverlant** [comment]
Never mind I was able to fix the issue after some meditation.

**Comment by gdeverlant** [comment]
I am having a problem here with a specific **SELECT** query via REST.

```
SELECT * FROM sqlite_master WHERE type='table'
```

Whene I execute this statement inside of DB Browser with the **db.sqlite** file from rqlite opened I get this result:

![image](https://user-images.githubusercontent.com/26530975/80863090-0cfc9500-8c7a-11ea-8e3c-555b4a940ea4.png)

But when the ORM sends the same request via REST it doesn't return anything. What could be the reason for this? Do you have any idea?

**Comment by gdeverlant** [comment]
It is working good so far the BEGIN and other operations are executed well only few blockages.

**Comment by gdeverlant** [comment]
How is the correct way to insert a **BLOB** via the REST API?

There is nothing shown concerning that data type.

**Comment by otoolep** [comment]
How would insert a BLOB via the SQLite CLI? Forget rqlite, show what you want to do via a SQLite example.

**Comment by gdeverlant** [comment]
> How would insert a BLOB via the SQLite CLI? Forget rqlite, show what you want to do via a SQLite example.

No not the CLI, I'm using REST API with my ORM as interface.

**Comment by otoolep** [comment]
I know, but I want to see what you are trying to do, expressed as a SQLite command first. Then I can see if it can be mapped to rqlite.

**Comment by gdeverlant** [comment]
Well this is the request I send right now but I don't know how to map the ByteArrays.

![image](https://user-images.githubusercontent.com/26530975/80897519-d5cdc880-8cf9-11ea-8e88-965afb4ed525.png)

**Comment by al-sabr** [comment]
Wow amazing in 3 days now the basic functions are working pretty well with the ORM.

Transactions

1. BEGIN
2. COMMIT
3. ROLLBACK(todo)

CRUD:

1. SELECT
2. CREATE
3. INSERT
4. UPDATE
5. DELETE(todo)

**Comment by al-sabr** [comment]
How can I get rid of this initialisation phase for all the RAFT related initialisations?

```
2020-05-04T17:12:32.828+0200 [WARN]  raft: Heartbeat timeout from "" reached, starting election
2020-05-04T17:12:32.828+0200 [INFO]  raft: Node at 127.0.0.1:4002 [Candidate] entering Candidate state in term 42
2020-05-04T17:12:32.834+0200 [INFO]  raft: Election won. Tally: 1
2020-05-04T17:12:32.834+0200 [INFO]  raft: Node at 127.0.0.1:4002 [Leader] entering Leader state
```

**Comment by otoolep** [comment]
No more updates, I'm closing this.

**Comment by al-sabr** [comment]
Please reopen this issue I am working on it.

**Comment by al-sabr** [comment]
What makes you think that no body will want a non-clustered version of rqlite?

**Comment by otoolep** [comment]
They may very well want it -- I know of one person who uses it in single-node mode.  But this repo is not the place for that work, as I do not want the functionality in rqlite.

However the great thing about open-source is that you can always offer it in your fork.

**Comment by virtadpt** [comment]
Hi - I use rqlite in non-clustered mode, also.  I really don't see a problem with standing up a single node and never joining any other instances to it.  Requiring it, on the other hand, would be a huge problem.

Just my $0.08us (adjusted for inflation).

**Comment by otoolep** [comment]
Just to be clear, I'm not saying single-node rqlite shouldn't be supported -- it works very well, I even have [a FAQ entry about it](https://github.com/rqlite/rqlite/blob/master/DOC/FAQ.md#can-i-run-a-single-node). It's a perfectly good use of the system. rqlite does not require more than 1 node to run (though you don't get any of the redundacy benefits, which is fine for many folks).

What I am saying is that I am not interested in accepting a patch that rips out the Raft layer, removes the Distributed Consensus layer etc. That would completely miss the point of rqlite, and would lower the quality of the codebase.

Building a system that offers just a HTTP API on top of SQLite is a fine idea, and you will get system that supports reads and writes much, much faster, but that's not what rqlite is about. That type of database is not the point of rqlite.

**Comment by otoolep** [comment]
And yeah, definitely no plans to require more than 1 node. Single node will always work -- it's useful as is, and is really important for test purposes.
