### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/rqlite/rqlite/v5

### ISSUE THREAD

**Issue by KateGo520** [rqlite/rqlite#644]
## Background
The `github.com/rqlite/rqlite` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v5`. And it’s module path is `"github.com/rqlite/rqlite"`, instead of `"github.com/rqlite/rqlite/v5"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version >= v5.0.0 of the `rqlite/rqlite`:
```
$ go get github.com/rqlite/rqlite@v5.2.0
go: finding github.com/rqlite/rqlite v5.2.0
go: finding github.com/rqlite/rqlite v5.2.0
go get github.com/rqlite/rqlite@v5.2.0: github.com/rqlite/rqlite@v5.2.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5
```
run `go get github.com/rqlite/rqlite`, the version will stuck in v4.6.0:
```
$go get github.com/rqlite/rqlite
go: downloading github.com/rqlite/rqlite v4.6.0+incompatible
go: github.com/rqlite/rqlite upgrade => v4.6.0+incompatible 
```
SO anyone using Go modules will not be able to easily use any newer version of `rqlite/rqlite`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/rqlite/rqlite/v5` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v5 `subdirectory` (github.com/rqlite/rqlite/v5) and place a new go.mod file in that subdirectory. The `module path` must end with `/v5`. Copy or move the code into the v5 subdirectory. Update `import statements` within the module to also use `/v5` (import "github.com/rqlite/rqlite/v5/…"). Tag the release with `v5.x.y`.

### 3.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/rqlite/rqlite@version-tag`, module users need to use this following way to get the `rqlite/rqlite`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/rqlite/rqlite@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `rqlite/rqlite`.

**[*]** You can see who will be affected here: [3 module users, e.g., flowerinthenight/testqrm, paulstuart/rqlobj, elliotcourant/noahdb]
https://github.com/search?q=%22github.com%2Frqlite%2Frqlite%22+filename%3Ago.mod&type=Code

## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by otoolep** [comment]
Thanks for your report, I'll consider addressing this when I move to v6.0.

**Comment by KateGo520** [comment]
Thank you for your contribution! ^_^

**Comment by NHAS** [comment]
I was just hit by this as Im trying to add rqlite directly into one of my projects. I've had to go and use the commit hash methods listed above.
