### ISSUE TITLE
Valid SELECT query  sent invalid result returned as an error although there is no error.

### ISSUE THREAD

**Issue by al-sabr** [rqlite/rqlite#648]
While I was implementing the unit testing with the ORM after connecting to RQLite a simple SELECT request is sent to the server and the returned result is wrong.

```
select t0.name as name,t0.id as id from main.Company t0 where ifnull(t0.marked_for_deletion,false)<>true

{
    "results": [
        {
            "error": "no such table: main.Company"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/26530975/81462943-47a08900-91b6-11ea-99e8-62f821993f40.png)

RQLite should return normal results (with warning) without any error with empty array instead of getting this error. The ORM should not be forced to handle this case because it is just sending request and handling results.

**Comment by otoolep** [comment]
Does the table `main.Company` exist?

**Comment by otoolep** [comment]
>>RQLite should return normal results (with warning) without any error with empty array instead of getting this error.

If your statement is that when a table doesn't exist but you query it away, that rqlite should return an empty array instead of telling you that the table doesn't exist, well that's not the way rqlite works. SQLite doesn't work that way either. No database works that way.

**Comment by otoolep** [comment]
You may be misinterpreting the API, which is fully documented here:

https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md

For every response you get, your code must first check if the `error` key is present. If present, you must handle that condition (usually by just signaling to the caller of your own software). If it's not present you can then process the results.

**Comment by al-sabr** [comment]
What I was suggesting is a consolidated result when there is an error still an empty result is sent with an extra field with the error all together so that there is greater possibility for the end user to adapt.

**Comment by otoolep** [comment]
I don't see any advantage to that. Can you show me an example response of what you mean? It makes sense, I can consider it for the next major version.

**Comment by al-sabr** [comment]
Ok I can be more precise with a new case I found with the ORM I am working on.
It seems to be that when I send CREATE statement on the server for a new table the returned result is total emptiness. Let me give you an example:

**Statement**
```
create table if not exists main.Company(id integer primary key autoincrement,marked_for_deletion boolean,name text,created_at date,updated_at date);
```

Will return this neither confirmation or negation:

![image](https://user-images.githubusercontent.com/26530975/81692215-590bbe80-945e-11ea-8989-834553cee581.png)

That **SQLError** you see was created by my code for this case but there is nothing coming out from RQLite.

**Comment by al-sabr** [comment]
Here is another case with a **SELECT** statement not saying how many rows are affected, etc...

**Statement**
```
select t0.name as name,t0.id as id from main.Company t0 where ifnull(t0.marked_for_deletion,false)<>true
```

![image](https://user-images.githubusercontent.com/26530975/81692620-f7981f80-945e-11ea-81dd-5ea642a20d2b.png)

**Comment by al-sabr** [comment]
For **INSERT** RQLite is returning an explicit result:

![image](https://user-images.githubusercontent.com/26530975/81692818-41810580-945f-11ea-8d14-e66c2945d5c9.png)

**Comment by otoolep** [comment]
To be honest, these reports are somewhat akward to follow, and are too specific to your environment. The most effective way to report questions, concerns, or issues, with the API are via demonstrations with `curl`.  See [the DATA API docs](https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md) for examples of what I mean.

Screenshots of your IDE are not super clear. Demonstrating issues with `curl` is a language-agnostic, IDE-agnostic way so please show me what you mean that way. Otherwise it's too difficult to know if it's something specific to your environment. I

**Comment by al-sabr** [comment]
What is akward to follow when I give you the SQL query I send on the server like :
```
create table if not exists main.Company(id integer primary key autoincrement,marked_for_deletion boolean,name text,created_at date,updated_at date);
```

and the result which is received without any further information just empty array?

![image](https://user-images.githubusercontent.com/26530975/81698652-970ce080-9466-11ea-81c1-153312170657.png)

I am trying to show you the inconsistency in the results returned by RQLite. For instance:

- When there is no such table I receive an error

- When I sent a request to create a table nothing is returned confirming/infirming what just happened.

This is pretty basic explanation and I am trying to help you out with visuals but you are not focusing on the valuable information.

**Comment by otoolep** [comment]
>>When I sent a request to create a table nothing is returned confirming/infirming that the table was either created or return an error if there is.

So this is not correct. Let's see what happens when you successfully create a table.
```
$ curl -v -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
    "create table if not exists main.Company(id integer primary key autoincrement,marked_for_deletion boolean,name text,created_at date,updated_at date);"
]'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 4001 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4001 (#0)
> POST /db/execute?pretty&timings HTTP/1.1
> Host: localhost:4001
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 158
> 
* upload completely sent off: 158 out of 158 bytes* 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< X-Rqlite-Version: 5
< Date: Tue, 12 May 2020 14:31:08 GMT
< Content-Length: 102
< 
{
    "results": [
        {
            "time": 0.00017906                                                                                                                                                               
        }                                                                                                                                                                                    
    ],                                                                                                                                                                                       
    "time": 0.010636042                                                                                                                                                                      
* Connection #0 to host localhost left intact 
```
Let's take a look at what you get back.
* HTTP 200 indicating successful request at the HTTP layer.
* No `error` key in the results, indicating there was no error from SQLite. The table was created successfully.

All this means your table-creation operation was successful. It is [clearly spelled](https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md#handling-errors) out in the DATA API docs.

Let's look at what happens if you try to create the table again without an `IF EXISTS` clause:
```
$ curl -v -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
    "create table main.Company(id integer primary key autoincrement,marked_for_deletion boolean,name text,created_at date,updated_at date);"
]'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 4001 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4001 (#0)
> POST /db/execute?pretty&timings HTTP/1.1
> Host: localhost:4001
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 144
> 
* upload completely sent off: 144 out of 144 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< X-Rqlite-Version: 5
< Date: Tue, 12 May 2020 14:34:51 GMT
< Content-Length: 123
< 
{
    "results": [
        {
            "error": "table Company already exists"
        }
    ],
    "time": 0.029681197
* Connection #0 to host localhost left intact
```
* HTTP 200 indicating successful request at the HTTP layer.
* This time there is an `error` key in the results, indicating there was an error from SQLite

Finally when you insert or select data, the API will respond in consistent fashion, or indicate an error as usual. All this is fully explained in the DATA API documentation. You may also wish to look at the [Python or Go client libraries](https://github.com/rqlite) to see how they work.

**Comment by otoolep** [comment]
Can you let me know if there any other concerns with the API? I believe the API has everything you need.

**Comment by otoolep** [comment]
Please re-open if you believe there are further issues. I don't see anything right now.
