### ISSUE TITLE
Adding rqlite to brew?

### ISSUE THREAD

**Issue by Takashiidobe** [rqlite/rqlite#649]
Hi, thank you for the neat project, I really love sqlite, and I found this project to be great and hassle free for making replicated databases.

I was wondering if there were any plans of adding this project to homebrew for Mac OS X, and if so, whether or not I could help out with that.

If not, feel free to close this issue.

**Comment by otoolep** [comment]
Yes, I would be interested. I know very little about homebrew, so any help appreciated. What would the next steps be?

**Comment by Takashiidobe** [comment]
From what I can tell, reading this:
https://docs.brew.sh/Formula-Cookbook

You write a new `formula.rb` in the `Formula/` dir of the `homebrew-core` repository.
This has some metadata about the project, the dependencies it has, and test(s) that the dependency has been installed correctly.  Then you make a PR to homebrew-core and wait for it to be accepted.

Most formula owners these days also use github actions, listening on new release to create a PR to homebrew core when the formula has been updated as well, which is something that can be setup afterwards.

**Comment by otoolep** [comment]
You want to try code it up? :-)

**Comment by Takashiidobe** [comment]
Sounds good to me.
Never done it before so it sounds like fun.
Go statically links by default so I don't need to specify any other dependencies, correct?

**Comment by otoolep** [comment]
Correct, rqlite has no other dependencies.

**Comment by Takashiidobe** [comment]
So i've found out that homebrew doesn't allow for binaries in homebrew-core, so I need to build the project and submit a recipe of that to homebrew.

I've tried to build this on my Mac OS X computer (10.15.4 Catalina, the newest available version), with the directions in contributing.md

```bash
mkdir rqlite # Or any directory of your choice.
cd rqlite/
export GOPATH=$PWD
go get -u -t github.com/rqlite/rqlite/...
$GOPATH/bin/rqlited ~/node.1
```

running `go version` outputs:
`go version go1.14.2 darwin/amd64`, which should be new enough.

I've cloned and forked the repo, and am on branch v5.2.0. I run the command in the root of the project directory.

My output looks like this:

```
go: downloading golang.org/x/crypto v0.0.0-20191219195013-becbf705a915
go: downloading github.com/mkideal/cli v0.0.3
go: downloading github.com/mattn/go-sqlite3 v2.0.2+incompatible
go: downloading github.com/hashicorp/raft-boltdb v0.0.0-20191021154308-4207f1bf0617
go: downloading github.com/mkideal/pkg v0.0.0-20170503154153-3e188c9e7ecc
go: downloading github.com/Bowery/prompt v0.0.0-20190916142128-fa8279994f75
go: downloading github.com/hashicorp/raft v1.1.1
go: downloading github.com/hashicorp/go-msgpack v0.5.5
go: downloading github.com/boltdb/bolt v1.3.1
go: downloading github.com/labstack/gommon v0.3.0
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/mattn/go-isatty v0.0.11
go: downloading golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
go: downloading github.com/hashicorp/go-hclog v0.9.1
go: downloading github.com/armon/go-metrics v0.0.0-20190430140413-ec5e00d3c878
go: downloading github.com/hashicorp/go-immutable-radix v1.0.0
go: downloading github.com/hashicorp/golang-lru v0.5.0
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
go get github.com/rqlite/rqlite/...: cannot find package
```

Unfortunately, since I can't build the project on mac os x, I can't make the PR to homebrew :(.
If you could help me out with that I could submit the formula.

**Comment by otoolep** [comment]
Can you try it on your master branch?

**Comment by Takashiidobe** [comment]
My master has the same result. it can't seem to find its own dependencies. I'm not much of a go user so maybe i'm forgetting to do something outside of following the directions in Contributing.md?

**Comment by otoolep** [comment]
Just to see something, can you just follow the instructions in CONTRIBUTING.md exactly? Check out rqlite/rqlite and build that? Don't build your fork at all.

**Comment by Takashiidobe** [comment]
Still the same error on my Mac.

**Comment by otoolep** [comment]
OK, I can only assume it's something special to your environment. What version of go are you using, `go version`?

The instructions I use to build on Mac are [here](https://github.com/rqlite/rqlite/blob/master/package.sh). No problems when I run this script, and run it each time when I release a build for OSX.

**Comment by Takashiidobe** [comment]
> running go version outputs:
go version go1.14.2 darwin/amd64, which should be new enough.

I still have the same issue with compilation ripping out the directions for release from the shell file.

It might be better to have someone who has a mac who is more knowlegable about go compile and take this issue.

**Comment by otoolep** [comment]
Not sure what to say at this point :-( I build on a Mac every few weeks, never had a single problem.

**Comment by otoolep** [comment]
I think someone did it: https://formulae.brew.sh/formula/rqlite
