### ISSUE TITLE
Custom Discovery service

### ISSUE THREAD

**Issue by jper80** [rqlite/rqlite#650]
Hi,

Is it possible to define customer discovery service instead of relying on http://discovery.rqlite.com. If yes how can i get the details of API contract?

Thanks,
Jerry

**Comment by otoolep** [comment]
Why, yes it is. :-)

There are three ways to learn:
- check out the [source code](https://github.com/rqlite/rqlite-disco) for the disco service.
- look at the rqlite [source](https://github.com/rqlite/rqlite/tree/master/disco) to see what rqlite sends and receives.
- check out the disco service implemented in Javascript by someone, for their own use.

Be sure to pass your disco URL to rqlite on startup. Check [out the command line params](https://github.com/rqlite/rqlite/blob/master/cmd/rqlited/main.go#L103).

**Comment by otoolep** [comment]
I believe this answers your question.

**Comment by otoolep** [comment]
Forgot a ref: https://gitlab.com/jdesodt/rqlite-disco-express

**Comment by jper80** [comment]
Thanks for the pointers.
