### ISSUE TITLE
For a noob like me, the documentation has everything except how to install this?

### ISSUE THREAD

**Issue by dcurbanman** [rqlite/rqlite#651]
I think my title is my question :)

sudo apt install rqlite doesn't quite work.

**Comment by otoolep** [comment]
The quickest way to get running on OSX and Linux is to download a pre-built release binary. You can find these binaries on the Github releases page. 

https://github.com/rqlite/rqlite/releases

**Comment by dcurbanman** [comment]
Thank you.
Somehow, I never saw those. My apologies.
Appreciate your quick help.
