### ISSUE TITLE
What is the maximum number of nodes can I have?

### ISSUE THREAD

**Issue by didip** [rqlite/rqlite#655]
Let's say, can I deploy each rqlited on 10,000 hosts?

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/blob/master/DOC/FAQ.md#what-is-the-maximum-size-of-a-cluster

https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md

https://github.com/rqlite/rqlite/blob/master/DOC/READ_ONLY_NODES.md
