### ISSUE TITLE
Configuration file in rqlite

### ISSUE THREAD

**Issue by geosoft1** [rqlite/rqlite#656]
I can't figure out how can I send the configuration file to rqlite. I found in the documentation an example of configuration file but nothing about importing into rqlite. Thanks.

**Comment by otoolep** [comment]
Which config file are you talking about? rqlite doesn't support a config file (except for security params). Everything must be set at the command line.

**Comment by geosoft1** [comment]
I'm talking about the configuration file for security parameters.

**Comment by otoolep** [comment]
Check out the help message when you run `rqlited -h`.

Pass `rqlited` the path via `-auth`.
