### ISSUE TITLE
Add a comparison to BedrockDB

### ISSUE THREAD

**Issue by bens** [rqlite/rqlite#657]
[BedrockDB](https://bedrockdb.com/) is something like a distributed sqlite as well which has been around for quite a long while. It would be helpful to explain what rqlite does differently and how someone might choose between them, I couldn't find any reference to it in this project.

**Comment by otoolep** [comment]
Thanks for request.

I've heard of it, but don't know much, if anything, about it. So I'm not in position to create a comparison. You could try the rqlite Google group.

https://groups.google.com/forum/#!forum/rqlite

**Comment by otoolep** [comment]
I.e. post a message there, seeing if anyone has performed any comparisons.

**Comment by bens** [comment]
Ah, fair enough. Thanks, @otoolep.
