### ISSUE TITLE
Can rqlite be configured to be 100% in memory?

### ISSUE THREAD

**Issue by didip** [rqlite/rqlite#665]
It seems like it can, but I am unable to find the config to do so.

**Comment by otoolep** [comment]
Only the database can be stored in memory, the log is always written to disk.

See:  https://github.com/rqlite/rqlite/blob/master/README.md#in-memory-databases

**Comment by otoolep** [comment]
So interpreting your question literally, the answer is no. However there is nothing stopping you passing a RAM-based file system to rqlite as its "data" directory.
