### ISSUE TITLE
Is RQLITE Safe Against SQL Injection Attacks?

### ISSUE THREAD

**Issue by bonedaddy** [rqlite/rqlite#667]
When using various databases in golang, you SQLi attacks are typically mitigated as `database/sql` uses prepared statements which solves SQLi attacks.

Given that using rqlite is not possible from `database/sql` I dont think it has the same prepared satements protection? If so, I'm guessing we need to manually filter requests and protect against SQLi ourselves?

**Comment by otoolep** [comment]
Yes, you currently have to do it yourself.

**Comment by otoolep** [comment]
I'm fixing this issue in https://github.com/rqlite/rqlite/pull/673

**Comment by otoolep** [comment]
rqlite now supports parameterized queries, which protects against SQL injection.
