### ISSUE TITLE
rqlite for already sqlite file

### ISSUE THREAD

**Issue by khanzadev** [rqlite/rqlite#669]
hello.

i already have 100 sqlite file db, can i connect rqlite to use 100 sqlite file without memory.

maybe `curl -G 'localhost:4001/user1234db/query?pretty&timings' --data-urlencode 'q=SELECT options FROM foo'`

user1234db is my sqlite filename and location in /var/www/sqlitedb

I don't need a good performance. but I only need a concurrent read operation from one opening a sqlite connection.

because right now I have a problem when many scripts connect to the sqlite file simultaneously and get an error ( `SQLite3 :: exec (): database is locked` ).

and i am trying to look through (fuser user1234db), it gives info:

`/var/www/user1234db 23116 23123 23134 24069 24078 24088 24093 so many PID`

sorry if my question is difficult to understand, I'm not used to using English

**Comment by otoolep** [comment]
You cannot directly use an existing SQLite file. You can load the `.dump` output from your SQLite database into rqlite however. 

https://github.com/rqlite/rqlite/blob/master/DOC/RESTORE_FROM_SQLITE.md

rqlite will not solve your locking issue, however. rqlite cannot do anything that SQLite cannot do.
