### ISSUE TITLE
Authentication issues in rqlite

### ISSUE THREAD

**Issue by geosoft1** [rqlite/rqlite#678]
I have a small cluster with three virtual machines running rqlited v5.5.0 secured with different self signed certificates and basic auth started by hand as following:

```
$HOME/bin/rqlited -auth auth.json -http-addr 10.10.180.61:4001 -raft-addr 10.10.180.61:4002 -http-cert server.crt -http-key server.key -node-encrypt -node-cert server.crt -node-key server.key -http-no-verify ~/node.1

$HOME/bin/rqlited -auth auth.json -http-addr 10.10.180.62:4001 -raft-addr 10.10.180.62:4002  -http-cert server.crt -http-key server.key -node-encrypt -node-cert server.crt -node-key server.key -http-no-verify -join https://root:12...@10.10.180.61:4001 ~/node.2

$HOME/bin/rqlited -auth auth.json -http-addr 10.10.180.63:4001 -raft-addr 10.10.180.63:4002  -http-cert server.crt -http-key server.key -node-encrypt -node-cert server.crt -node-key server.key -http-no-verify -join https://root:12...@10.10.180.61:4001 ~/node.3

```

Here is `auth.json` file:

```
[
  {
    "username": "root",
    "password": "1234",
    "perms": ["all"]
  }
]

```
Command to generate the ceritificates:

`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
`

I observed some authentication issues in rqlite console, only on some commands like in the following example. Look like some commands works and some commands get the authentication error, but in the same session under the same authentication credentials. I've tested on these three nodes which are accessible and responds to queries.

```
rqlite -i -s https -H 10.10.180.31 -u root:1234
Welcome to the rqlite CLI. Enter ".help" for usage hints.
10.10.180.31:4001> create table foo (id int)
0 row affected
10.10.180.31:4001> insert into foo values (1)
1 row affected
10.10.180.31:4001> .tables
+------+
| name |
+------+
| foo  |
+------+
10.10.180.31:4001> select * from foo
+----+
| id |
+----+
| 1  |
+----+
10.10.180.31:4001> .status
ERR! unauthorized
10.10.180.31:4001> .dump foo.dump
SQL text file written successfully
10.10.180.31:4001> .backup foo.backup
backup file written successfully
10.10.180.31:4001> .restore foo.backup
ERR! unauthorized
10.10.180.31:4001> .restore foo.dump
ERR! unauthorized

```
On non-leader nodes I have the following result:

```
10.10.180.32:4001> .backup foo.backup
ERR! server responded with: 500 Internal Server Error

```
Another behavior that I observed is starting virtual machines in the same time and rqlite with above commands, from crontab on @reboot works only if on the node two and three I put a long delay (eg 60sec), even that the machines have almost the same load time. Starting cluster by hand on each node in order, with the same commands, works. I can't figured out if this is a issue of authentication from the error messages but I can post here some if is needed..

**Comment by otoolep** [comment]
The first two issues are due to bugs in the CLI. The third issue is a bug in the server itself. I don't really follow the fourth issue -- perhaps you can open a new issue for that, with more details.

@geosoft1 -- I believe the first three issues are fixed, if you build top-of-master. Can you do that, and confirm it all looks better? If looks good to you, I can make a new release.

**Comment by geosoft1** [comment]
I tested in the following conditions:

- three nodes (like in the first post) with an empty database
- create table foo (id int);insert into foo values (1)
- tried commands .status, .tables, select * from foo, .backup file, .dump file, .restore file, on each node
- restarts the nodes in various orders to change the leader and repet above commands

Things looks good with two observations:

```
rqlite -i -s https -H 10.10.180.62 -u root:1234
Welcome to the rqlite CLI. Enter ".help" for usage hints.
10.10.180.62:4001> .restore dump_chain_01.db
ERR! unexpected results length: 0
```

- .status command reports auth: enabled only on the first declared node (where the others join, in my case host 61, even is the leader or not, even is first started or not), eg:

```
http:
  addr: 10.10.180.61:4001
  auth: enabled
  redirect: 10.10.180.61:4001

http:
  addr: 10.10.180.62:4001
  auth: disabled
  redirect: 10.10.180.61:4001
```

**Comment by otoolep** [comment]
I'll look into the `restore` issue, though you should check you're only trying to restore a text dump.

That issue with the "auth" flag -- I'll fix that too now.

**Comment by otoolep** [comment]
Actually, the auth flag is fine. All it means is that the node is using a credentials file. It is short for "authorization".

**Comment by otoolep** [comment]
Yeah, restore still doesn't seem happy with attempted on a follower. Technically that's not supported, and the CLI is trying to process a redirect. It's probably not doing it correctly. The docs doc say that you should do the restore talking to the leader, but I did want to make it work anyway.

**Comment by otoolep** [comment]
Fixed the restore issue.

https://github.com/rqlite/rqlite/pull/683

**Comment by geosoft1** [comment]
Yay, looks good now. Many thanks.
