### ISSUE TITLE
How difficult is to create an offline-first app?

### ISSUE THREAD

**Issue by frederikhors** [rqlite/rqlite#684]
I only discovered this project today.

**Congratulations for this great job!**

In your opinion, how difficult is it to create an offline-first Web/Desktop/Native application with this project?

Anything that respects [these rules](https://jaredforsyth.com/posts/in-search-of-a-local-first-database/)?

**Comment by otoolep** [comment]
Assuming I understand the question, rqlite is not a good match for that. You cannot write to a node that is disconnected from the cluster ("offline").

**Comment by otoolep** [comment]
See https://github.com/rqlite/rqlite/blob/master/DOC/FAQ.md#can-any-node-execute-a-write-request-and-have-the-system-synchronize-it-all

You can read from a node that is not connected to the cluster, if you specify "none" as read consistency.

https://github.com/rqlite/rqlite/blob/master/DOC/CONSISTENCY.md

I'm going to assume this answers your question.

**Comment by frederikhors** [comment]
What a pity!

It would have been great because it would have been possible to use this system for every Web / Desktop / Wasm / Native app in the world.

Is there really no way to keep the data in that local node and leave it to him to write it to the master?

Can you think of any other way to go?

**Comment by otoolep** [comment]
There is no way, I'm afraid, it's just not that type of database.

You might to post your question to Hackernews (Ask HN) or Reddit databases).....
