### ISSUE TITLE
Port 4001 not started after cluster building commands execution

### ISSUE THREAD

**Issue by liufanghua2012** [rqlite/rqlite#688]
I tried to build a cluster, but I don't know what happened to my Rqlite db after my operations. Now, port 4001 of the database is not started and the database can't work at all. Port 4002 is OK. What should I do to fix the data? i saw a raft.db file in the folder, can i do anything with it?

**Comment by liufanghua2012** [comment]
Commands used in Host A: rqlited -http-addr 0.0.0.0:4001 -raft-addr 0.0.0.0:4002 /rqlite/file/data
Commands used in Host B: rqlited -http-addr 0.0.0.0:4101 -raft-addr 0.0.0.0:4102 -join http://172.16.0.17:4001 /rqlite/file/data2

172.16.0.17 is the ip address of Host A

**Comment by otoolep** [comment]
This is not enough to help you debug the issue. Please show us the logs from each node, when this problem happens.

**Comment by otoolep** [comment]
No more updates.
