### ISSUE TITLE
Create CLI for rqlite

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#7]
A simple command-line tool should be written. This doesn't have to be written in Go, it could be written in, say, Python.

**Comment by nodtem66** [comment]
Why it shouldn't be written in Go? 
Is the reason that Python is commonly installed on OS?

**Comment by otoolep** [comment]
Yes, Go would be my first choice.

**Comment by fern4lvarez** [comment]
Isn't `rqlite` a command line tool itself? What should I expect from this tool you propose and what's the difference with the current one?

**Comment by otoolep** [comment]
`rqlite` just launches the server. What I had in mind is something like this:

```
$ rqlite-cli
rqlite> SELECT * from foo
.
.
```
which would take the input from the prompt, send to the API, read the results back, and render them nicely.

**Comment by otoolep** [comment]
It would need to be launched something like so:

`rqlite-cli -h 127.0.0.1:8086`

**Comment by otoolep** [comment]
This is the difference between `mysqld` and `mysql`.

**Comment by otoolep** [comment]
Closed in error.

**Comment by otoolep** [comment]
See this commit: https://github.com/otoolep/rqlite/commit/649cef2adb4bc36585e3f798ee51bc697f9a7e1d

This would be the right place to add the CLI program. Once built, it would then appear in `$GOPATH/bin`.

**Comment by otoolep** [comment]
And this: https://github.com/otoolep/rqlite/commit/0b528659494bcbd85baf3d0dbdb7f47276cf132e

This would be the program to work on.

**Comment by fern4lvarez** [comment]
:+1:

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/pull/118
