### ISSUE TITLE
Can rqlite be used to sync instances of newsboat sqlite cache.db sqlite databases?

### ISSUE THREAD

**Issue by ZaxonXP** [rqlite/rqlite#706]
I have the following scenario:

On the server I have newsboat which pulls new RSS data into cache.db every 30 min.

On the client machine I want to have a newsboat with cache.db instance which will be two way synced with the server instance. Client can go offline, get new db records, delete some records, change the attributes to some existing records.

In meantime the server will get the new records.

When client go online it sould:
1) get the new records from the server db.
2) update server db (delete/modify the records which were deleted/modified on the client db).

Can this scenario be possible to implement with using `rqlite`? How to approach this?

Regards,
Piotr

**Comment by otoolep** [comment]
rqlite is not such a system, and not what you're looking for.

See https://github.com/rqlite/rqlite/blob/master/DOC/FAQ.md#can-any-node-execute-a-write-request-and-have-the-system-synchronize-it-all
