### ISSUE TITLE
Can't join cluster with ipv6 address

### ISSUE THREAD

**Issue by mrkurt** [rqlite/rqlite#709]
We're using rqlite with IPv6 and the join argument doesn't seem to like ipv6 addresses.  When I run this command:

```
rqlited -join http://[fdaa:0:1:a7b:7b:0:617:2]:4001 -http-addr [::]:4001 -http-adv-addr fdaa:0:1:a7b:7f:0:61f:2:4001 -raft-addr [::]:4002 -raft-adv-addr fdaa:0:1:a7b:7f:0:61f:2:4002 -raft-timeout 5s -raft-election-timeout 10s -on-disk /data/db
```

It won't join, it just logs this:

```
[cluster-join] 2020/12/24 17:57:33 failed to join cluster at [http://[fdaa:0:1:a7b:7b:0:617:2]:4001]: address fdaa:0:1:a7b:7f:0:61f:2:4002: too many colons in address, sleeping 5s before retry
```

I looked through the code and can't quite figure out where this is happening. [`net.ResolveTCPAddr`](https://github.com/rqlite/rqlite/blob/7f494019c78425ed5fe724803f7c4f37eee10985/cluster/join.go#L59) parses this fine: https://play.golang.org/p/Mf5l0ORBKup

**Comment by mrkurt** [comment]
Wait I might be an idiot, I just noticed the bad address format in `-http-adv-addr` 🤦

**Comment by otoolep** [comment]
Yeah, it looks bad. See :https://play.golang.org/p/-69HlvHj3z0
