### ISSUE TITLE
Leader dies, tries to join itself on restart?

### ISSUE THREAD

**Issue by mrkurt** [rqlite/rqlite#710]
I have a three node rqlite running, if I kill the followers they come back fine. If I kill the leader, it won't come back.

This is using the `-join` flag, not service discovery. After it dies, what was the leader is restarted with this command (`-join` comes from our DNS and includes the healthy replicas):

```
rqlited -join http://[fdaa:0:1:a7b:7f:0:636:2]:4001,http://[fdaa:0:1:a7b:81:0:637:2]:4001 \
    -node-id 7b06352 \
    -http-addr :4001 \
    -http-adv-addr [fdaa:0:1:a7b:7b:0:635:2]:4001 \
    -raft-addr :4002 \
    -raft-adv-addr [fdaa:0:1:a7b:7b:0:635:2]:4002 \
    -raft-timeout 5s \
    -raft-election-timeout 60s \
    -join-attempts 100 \
    /data/db
```

It starts to boot then gives `failed to join cluster` errors repeatedly until it gives up:

```    [store] 2020/12/24 22:22:30 ensuring directory at /data/db exists
    [store] 2020/12/24 22:22:30 opening store with node ID 7b06352
    [store] 2020/12/24 22:22:30 SQLite in-memory database opened
    2020-12-24T22:22:30.133Z [INFO] raft: initial configuration: index=6 servers="[{Suffrage:Voter ID:7b06352 Address:[::]:4002} {Suffrage:Voter ID:7f06362 Address:[fdaa:0:1:a7b:7f:0:636:2]:4002} {Suffrage:Voter ID:8106372 Address:[fdaa:0:1:a7b:81:0:637:2]:4002}]"
    [store] 2020/12/24 22:22:30 no bootstrap needed
    [rqlited] 2020/12/24 22:22:30 join addresses are: [http://[fdaa:0:1:a7b:7f:0:636:2]:4001 http://[fdaa:0:1:a7b:81:0:637:2]:4001]
    2020-12-24T22:22:30.141Z [INFO] raft: entering follower state: follower="Node at [::]:4002 [Follower]" leader=
    [cluster-join] 2020/12/24 22:22:30 failed to join cluster at [http://[fdaa:0:1:a7b:7f:0:636:2]:4001 http://[fdaa:0:1:a7b:81:0:637:2]:4001]: Post "http://[fdaa:0:1:a7b:7b:0:635:2]:4001/join": dial tcp [fdaa:0:1:a7b:7b:0:635:2]:4001: connect: connection refused, sleeping 5s before retry
    [cluster-join] 2020/12/24 22:22:35 failed to join cluster at [http://[fdaa:0:1:a7b:7f:0:636:2]:4001 http://[fdaa:0:1:a7b:81:0:637:2]:4001]: failed to join, node returned: 503 Service Unavailable: (not leader
    ), sleeping 5s before retry
    2020-12-24T22:22:36.522Z [WARN] raft: heartbeat timeout reached, starting election: last-leader=
    2020-12-24T22:22:36.526Z [INFO] raft: entering candidate state: node="Node at [::]:4002 [Candidate]" term=4
    2020-12-24T22:22:36.542Z [INFO] raft: election won: tally=2
    2020-12-24T22:22:36.544Z [INFO] raft: entering leader state: leader="Node at [::]:4002 [Leader]"
    2020-12-24T22:22:36.546Z [INFO] raft: added peer, starting replication: peer=7f06362
    2020-12-24T22:22:36.548Z [INFO] raft: added peer, starting replication: peer=8106372
    2020-12-24T22:22:36.555Z [INFO] raft: pipelining replication: peer="{Voter 7f06362 [fdaa:0:1:a7b:7f:0:636:2]:4002}"
    2020-12-24T22:22:36.684Z [INFO] raft: pipelining replication: peer="{Voter 8106372 [fdaa:0:1:a7b:81:0:637:2]:4002}"
    [cluster-join] 2020/12/24 22:22:40 failed to join cluster at [http://[fdaa:0:1:a7b:7f:0:636:2]:4001 http://[fdaa:0:1:a7b:81:0:637:2]:4001]: Post "http://[fdaa:0:1:a7b:7b:0:635:2]:4001/join": dial tcp [fdaa:0:1:a7b:7b:0:635:2]:4001: connect: connection refused, sleeping 5s before retry
```

What's weird is that dial. That is its own address.

Both replicas still think this node is primary. But it isn't responding to HTTP requests (even from curl).

**Comment by otoolep** [comment]
Does it work if you do not pass `-join`? It shouldn't matter last time I checked the code, but you should check that. Once a node has been part of a cluster, "joining" makes no longer makes sense and is unnecessary, so don't tell it to join anything.

**Comment by otoolep** [comment]
Also, it would be helpful if you included full details of the software you are running -- host OS, rqlite version, etc.

**Comment by otoolep** [comment]
From the logs, what seems to be happening is that you tell the node to join the cluster, but that node responds that "it's not leader".  The node then seems to use the cluster configuration it does know about to start an election, which it wins. Looks like it's actually part of the cluster fine at the end, and the log is confusing.

Anyway, don't tell it to join after restart, as there should be no need as the node has a list of all nodes that were in the cluster when it died, and will use that list when it comes back up. However I might need to more testing to see what is the best thing to do if the cluster has completely changed (regarding nodes) when the node is restarted.

**Comment by otoolep** [comment]
You should show me the status output from each node in your cluster after the node "gives up". I expect it's part of the cluster and the leader.

https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by mrkurt** [comment]
Removing the `-join` arg did fix it!

Prior to that, it was stopping the process after the `join-attempts` were exhausted. The other nodes did see it as leader but it seemed to never start listening on http.

**Comment by mrkurt** [comment]
For posterity, here's what we're running:

```Dockerfile
FROM debian:buster

RUN apt-get update && apt-get install --no-install-recommends -y \
    ca-certificates curl bash dnsutils \
    && apt autoremove -y

WORKDIR /opt

ARG RQLITE_VERSION=5.7.0

RUN curl -L https://github.com/rqlite/rqlite/releases/download/v$RQLITE_VERSION/rqlite-v$RQLITE_VERSION-linux-amd64.tar.gz \
    -o rqlite-linux-amd64.tar.gz \
    && tar xvfz rqlite-linux-amd64.tar.gz \
    && mv rqlite-v$RQLITE_VERSION-linux-amd64/* /usr/local/bin/

COPY entrypoint /entrypoint

ENTRYPOINT ["/entrypoint"]
CMD ["rqlited"]
```

The entrypoint is a shell script that builds the args for `rqlited`, it's running on Fly.io in a Firecracker VM, Linux kernel 5.9.11.

**Comment by otoolep** [comment]
OK, definitely some rough edges there in the code -- I'll look into fixing that.

**Comment by mrkurt** [comment]
It's working well now! The whole example project is here: https://github.com/fly-examples/rqlite/

**Comment by otoolep** [comment]
404 on that link.

**Comment by mrkurt** [comment]
Whoops, it was private. It should work now.

**Comment by otoolep** [comment]
I took a look at the code, to refresh my memory -- and the docs too. The [docs state that `-join` should be idempotent](https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#creating-a-cluster) -- that one can leave the `-join` option in place between restarts.

Well this is true, but **only** if the `join` addresses are still contactable, which didn't seem to be case in your setup. If the `join` addresses don't respond, the system will exit due to [this code](https://github.com/rqlite/rqlite/blob/v5.7.0/cmd/rqlited/main.go#L282). But in your case, in parallel with the `join` attempts, the Raft subsystem was consulting its internal config and doing a join with other nodes -- which was successful since those nodes were contactable (but then the node exited).

I'm not sure what is the clearest way for the system to work in this situation. In earlier versions of rqlite, if a node was already a member of a cluster (as this node was) any `-join` option was simply ignored. Maybe we should return to that behavior. Any opinoin @mrkurt ?

**Comment by mrkurt** [comment]
Ignoring `-join` when clustering is already configured makes sense to me. That's what Consul does, at least.

In my particular world, it would also be nice if the process ignored `-join` self references. But it's working fine now! This would just simplify the wrapper scripting.

**Comment by otoolep** [comment]
There was actually a regression in the code, probably for a long time. `-join` requests should have been ignored, if the node has preexisting state.

**Comment by otoolep** [comment]
This should fix the initially reported issues.

Your suggestion about ignoring any join address if it includes the node itself is an interesting one. However I think it might also make sense to exit on that. I'm not sure, so not going to make any changes in that area yet. I'll open a bug to track the suggestion.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/issues/713
