### ISSUE TITLE
./rqlited ~/node.1 -on-disk silently fails to take effect

### ISSUE THREAD

**Issue by simonw** [rqlite/rqlite#718]
Starting `rqlited` like this:

    ./rqlited -on-disk ~/node.1

Starts up in on-disk mode and creates a `~/node.1/db.sqlite` file.

Starting it like this:

    ./rqlited ~/node.1 -on-disk

Ignores the `-on-disk` flag and starts up normally without creating that file.

The second example should either work or it should fail with an error - failing silently left me scratching my head until I figured out what had gone wrong.

**Comment by otoolep** [comment]
Thanks for the report, I agree it's confusing. It's due to the way Go's flag parsing works. I'll change the code so the program exits if there are any flags after the data directory path.
