### ISSUE TITLE
TLSv1.0 still Supported

### ISSUE THREAD

**Issue by Ne00n** [rqlite/rqlite#743]
Hey,

I just ran a cipher test on a rqlite node with lets encrypt, seems like it still supporting TLSv1.0.
Could we get that disabled? or is there any other way to specify the ciphers?

**Comment by otoolep** [comment]
Seems reasonable, as efforts are underway to deprecate it.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/pull/745

**Comment by otoolep** [comment]
Will be fixed in next release.

**Comment by otoolep** [comment]
I mean, it is fixed, but will be available in next release (5.10).
