### ISSUE TITLE
Status Service: Raft LatestConfiguration not in Json Format

### ISSUE THREAD

**Issue by sjefvanleeuwen** [rqlite/rqlite#748]
The raft -> latest_configuration can not be deserialized using Json standard.

[{Suffrage:Voter ID:1 Address:127.0.0.1:4002} {Suffrage:Voter ID:2 Address:127.0.0.1:4004} {Suffrage:Voter ID:3 Address:127.0.0.1:4006}]

**Comment by otoolep** [comment]
Thanks for your report.

That config is generated by the Hashicorp code, not rqlite code. It's an implementation detail of their software, and its particular structure is not something rqlite relies on. If you think there is something up you should file an issue in that repo:

https://github.com/hashicorp/raft

**Comment by otoolep** [comment]
The status endpoint just treats the diagnostic output from the Hashicorp code as a black box, and just displays it as a string. That's why rqlite doesn't care.

**Comment by sjefvanleeuwen** [comment]
Thanks, how about adding at least a type indicator in the RqLite diagnostic json payload, so diagnostics clients know how to treat it during deserialization? Such as:

"latest_configuration": {"provider" : "<provider-indication>"}

**Comment by otoolep** [comment]
No plans to change the provider soon. It's a 6.0+ or later thing.
