### ISSUE TITLE
Detailed Cluster status

### ISSUE THREAD

**Issue by Ne00n** [rqlite/rqlite#768]
Hey,

Is there any way to show the detailed cluster status, like the nodes and their current status if they are online or offline?
Currently .status does not give me that information but it seems like rqlite is aware of it.

So could you add it? Or is there already a way to get that info?

Thanks.

**Comment by otoolep** [comment]
The Hashicorp raft system doesn't provide such functionality, so it's now shown right. It just shows the current cluster membership, but that doesn't mean any particular node is running.

Of course, rqlite could have this functionality added. However, we need to define specifically want we mean:

- what online actually mean? Responding to simple HTTP GET call? Last heard from leader?
- online from which node's point of view? The node that you make the request at? The leader?
- 
WDYT?

**Comment by Ne00n** [comment]
By Online I would mean reachable, rqlite/raft has a consistent heartbeat so It does notice if a specific node is not longer reachable.
I don't know precisely how raft/rqlite does determine, if a node goes offline, but it seems to be able to detect it if I watch the leaders output.


So somehow, this should be possible, to provide this information to the cluster under .status?
As far as I know the Leader does that.

**Comment by otoolep** [comment]
That is true, those network error messages are logged by Raft when a node goes away. Let me look into the Raft code, maybe there is someway to expose those error conditions in the status output.

**Comment by otoolep** [comment]
Looks like I can't get it from the Raft code without changes, and I don't want to fork it. I have other ideas however, that may be easy enough to implement.

@Ne00n -- can you build rqlite yourself? I don't want to release a version with this functionality until I'm sure it's the right design and implementation. I could create a new branch, which you could build yourself and try out.

What use case are you trying to solve? How quickly do you need to know that a node is not reachable?

**Comment by Ne00n** [comment]
No problem, I certainly won't compile it myself for now.
Basically I was trying to abuse rqlite as datastore + monitoring.

I thought it would be easy to get that data from raft but if is that complicated, its not worth it then.

I am currently building a cdn with python3 + rqlite as datastore, so if a node dies, traffic needs to be rerouted.
https://github.com/Ne00n/woodCDN

I ended up creating a entry for each node with a timestamp and if the node is unable to report to the leader/cluster to update, its considered ded if the timestamp is older than 60s.

Shall work for now, thanks for your time.

**Comment by otoolep** [comment]
Fixed in https://github.com/rqlite/rqlite/pull/796

**Comment by Ne00n** [comment]
If you have non voters, they are not displayed on nodes, why is that?
Can you change that?

**Comment by otoolep** [comment]
https://rqlite.io/docs/guides/monitoring-rqlite/#nodes-api

Is this what you want?

```bash
curl localhost:4001/nodes?pretty

# Also check non-voting nodes.
curl localhost:4001/nodes?nonvoters&pretty

# Give up if all nodes don't respond within 5 seconds. Default is 30 seconds.
curl localhost:4001/nodes?timeout=5s
```
