### ISSUE TITLE
Viruses found in binary

### ISSUE THREAD

**Issue by yoonghm** [rqlite/rqlite#770]
I uploaded rqlite.exe and rqbench.exe onto https://www.virustotal.com/. The website shows that these two files are infected.

**Comment by otoolep** [comment]
I do not build any rqlite.exe or rqbench.exe files. They are available from appveyor however, and I don't know much about that service. I only *personally* build the macOS and Linux version.

Please show me a screenshot of what that website showing you.

**Comment by otoolep** [comment]
I uploaded the binaries from the latest Windows build on AppVeyor to the website you mentioned. It does flag some issues, but I do not have any idea if the findings are valid. However I have added a disclaimer to the GitHub releases page about the AppVeyor builds.

**Comment by otoolep** [comment]
Releases page now reads as follows:

rqlite can be built for Windows, and compatibility is ensured at all times via AppVeyor. However you may need to build a specific release yourself, though the top-of-tree build is available for download from AppVeyor. Check out the CI build for Windows for more details. **I do not control the build process in AppVeyor and you download and use those binaries at your own risk.**

**Comment by yoonghm** [comment]
Thanks. I will build my own release
