### ISSUE TITLE
Follow the leader?

### ISSUE THREAD

**Issue by NuSkooler** [rqlite/rqlite#773]
I'm currently evaluating the use of rqlite for a project that wants to build a set of distributed workers. rqlite looks to be perfect for distributed/shared state in this respect.

Question: Is it possible to "follow" the leader? A worker in this context also needs the concept of a floating leader and it seems counterintuitive to use a separate implementation for some things while another for the DB itself.

#127 seems like a way this could be achieved, but I'm curious on thoughts.

Thanks!

**Comment by otoolep** [comment]
I'm not quite sure I follow you, no pun intended. What do you mean "follow" the leader? That issue, #127, is about notifying other nodes of changes, but I wouldn't classify that as "following the leader". Following changes, perhaps. I don't have any plans to implement it at the moment, it remains speculative. Read-only nodes (see the docs directory) are not far off though.

To be clear, while rqlite is a distributed system -- it uses many computers to achieve a particular goal (reliability and fault tolerance) -- I would not describe the state machine i.e. the SQLite database as distributed. The entire state of the database is under *every* node.

Can you provide more details on what you're trying to do?

**Comment by NuSkooler** [comment]
@otoolep Thanks for the quick response.

What I mean is that rqlite determines a leader node and can elect a new leader when needed. I have worker nodes that provide a service that also want to share state. If a worker dies or goes away, that is OK, another worker can take over (and another would be made leader).

If I could "piggy back" or "follow" the rqlite leader this would mean the DB leader and the worker itself (the service) would be the same vs a separate implementation that would result in ie: DB leader A and worker leader B (maybe this isn't actually a problem).

I mention #127 as I can query the current leader as-is, but a notification of a leader change would tell me the answer in semi realtime. Though perhaps #127 isn't exactly that as it's talking about the DB vs the Raft layer.

**Comment by otoolep** [comment]
>What I mean is that rqlite determines a leader node and can elect a new leader when needed.

What does "when needed" mean? rqlite, the system, elects a new leader when the current leader becomes unavailable. What you are describing sounds like what rqlite already does.

I'm still not following what you want. You've introduced terms like "DB leader" and "worker" that don't obviously map to any concept in rqlite. rqlite is a Raft-based system and had 3 distinct concepts for the nodes in the cluster -- leader, follower, and candidates. The last only happens during elections. 

If "DB Leader" means "rqlite leader", then any concept of "worker" is outside of of rqlite's conceptual psace. What does a "worker" do, in your system?

If worker is some node that shares state, then what is rqlite for in your system?

**Comment by otoolep** [comment]
I'm trying hard to understand, but am having a hard time seeing how it maps to rqlite, or where rqlite fits it. Perhaps you could explain what application you're trying to build?

**Comment by otoolep** [comment]
BTW client nodes don't need to know what the rqlite leader is at anytime. As long as a client can find some node in the cluster, that node will know the leader, and tell the client to redirects its requests to the leader, if necessary. So in that sense clients don't need to "follow the leader" -- the just need to contact some node in the cluster. Any node.

**Comment by otoolep** [comment]
See What I mean is that rqlite determines a leader node and can elect a new leader when needed.

**Comment by NuSkooler** [comment]
> rqlite, the system, elects a new leader when the current leader becomes unavailable. What you are describing sounds like what rqlite already does.

Yes, exactly. rqlite already does this. rqlite is the database, so I'm calling this the "DB leader".

The software I'm writing has a concept of a worker. This worker wants to ensure that it's database (state) entries are the same as other workers in the cluster. rqlite can give me this. However, this cluster of workers also needs a leader to be elected -- and automatic election of a new leader if a worker becomes unavailable.

Each worker node would have have rqlite running next to it. It would be ideal if the worker leader were always the same as the rqlite leader. So I would like to "follow" or "piggy back" rqlite's leader election in a sense.

**Comment by otoolep** [comment]
OK, I see now what you're trying to do. I haven't considered such an application for rqlite, so not sure how it would map short of deliberately killing a leader associated with your worker. You're trying to build distributed systems capability into your own system by following another.

TBH it sounds like you're trying to ensure one node in your worker fleet is more important than all the others, and that there is never a conflict i.e. that two workers believe each are the most important at a given time. I'm not sure rqlite can help you, but something like Zookeeper might be what you're looking for. You should look into that. Many systems use it in that manner. Earlier versions of Apache Kafka did.

**Comment by otoolep** [comment]
Apache Kakfa (back in the 0.7 days) used Zookeeper to pick a leader node amongst its fleet of "worker" nodes. You might like to read up about that.

**Comment by NuSkooler** [comment]
@otoolep It looks like we're on the same page now, apologies for the bad explanations.

Ideally I can avoid any "leader" (or as you say: more important) nodes in the fleet, but this may not be possible. I will look into ZooKeeper. Are you suggestion that I might use this in conjunction with rqlite?

**Comment by otoolep** [comment]
No, Apache Zookeeper might solve your problems completely. rqlite wouldn't feature in it, unless you also want a fault-tolerant SQL store such as rqlite.

**Comment by otoolep** [comment]
I think we're done here, good luck with your development.
