### ISSUE TITLE
Decrease number of Nodes in Cluster

### ISSUE THREAD

**Issue by AlexanderNitsch** [rqlite/rqlite#778]
According to the docs (CLUSTER_MGMT.md) a node that is removed must be replaced by a new one:

> Removing a node does not change the number of nodes required to reach quorum, so you must add a new node to cluster as a replacement. To do so, simply follow the instructions for Growing a cluster.

Is there any way to shrink a cluster, preferrably without it having to go offline?

Doesn't adding a new node after removing one increase the necessary quorum size?

Thank you very much.

**Comment by otoolep** [comment]
Thanks for your ticket. I actually think the docs are incorrect, and removing a node *does* reduce quorum. Let me run some tests and correct the docs as needed.

**Comment by otoolep** [comment]
The docs were not right -- they were right in some situations, but it wasn't clear. I've updated them. See 

https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#removing-or-replacing-a-node
