### ISSUE TITLE
Bump SQLite to 3.35.0

### ISSUE THREAD

**Issue by moderation** [rqlite/rqlite#779]
SQLite 3.35.0 just came out - https://sqlite.org/releaselog/3_35_0.html

Now `rqlite` uses a fork of https://github.com/mattn/go-sqlite3, what is the plan for maintaining the SQLite version? Will this repo wait for the upstream to upgrade or will https://github.com/rqlite/go-sqlite3 now accept PR's to bump the SQLite version independent of the upstream?

**Comment by otoolep** [comment]
I plan to merge upstream into my fork every so often. I won't let this folk every get too far behind upstream, as I watch that repo.
