### ISSUE TITLE
Support for diesel-rs

### ISSUE THREAD

**Issue by phi0x** [rqlite/rqlite#780]
I'm trying to setup bitwarden_rs password manager in a clustered state on low IoT hardware. rqlite is awesome and I'd like to use it for my bitwarden implementation. I've asked the bitwarden_rs community if they can use a driver but it sounds like they wont be implementing a driver for it due to the fact that maintaining it would potentially stretch them too thin. They currently support sqlite, postgres, mariadb as DB options. I suspect if I use the rqlite database_url, it bitwarden_rs wont know how to use the api calls? 

With that being said, does rqlite support diesel-rs and or can it be added as a feature request if it does not already support it?

https://diesel.rs/

bitwarden_rs forum post: https://bitwardenrs.discourse.group/t/rqlite-database-support/786

Any info would be great and or consideration of supporting it thanks!

**Comment by otoolep** [comment]
I do not have any plans to work on this, but I could create a repo under the rqlite organisation, and see if anyone contributes. Would that be reasonable? What are the naming conventions for this type of ORM?

**Comment by phi0x** [comment]
hey anything is reasonable! I'm not really a programmer, more of a sys admin/devOps type so i'm not to sure how this all would come together to work. I just love the idea of being able to have a self hosted password manager that is highly available/redundant via rqlite. postgres/maria db which they support, is too beefy for IoT devices or small cloud servers. rqlite is a perfect use case for such a self hosted service.

**Comment by phi0x** [comment]
also I posted on diesel-rs github page to see if they can do anything.
https://github.com/diesel-rs/diesel/discussions/2698

**Comment by chermehdi** [comment]
@phi0x help me out here, diesel-rs supports sqlite, and I believe you can connect to the the master in an rqlite cluster using diesel-rs without needing any extra support? So what are you suggesting exactly?

**Comment by jtackaberry** [comment]
@chermehdi basically diesel-rs supporting rqlite's HTTP API is what would be needed to implement this properly.

(I had the exact same idea for Vaultwarden (nee bitwarden_rs) which led me here.)

**Comment by otoolep** [comment]
This is not the right repo for this issue, work would need to take place in the diesel-rs codebase.
