### ISSUE TITLE
leader does not exist in metadata of cluster

### ISSUE THREAD

**Issue by momoadc** [rqlite/rqlite#787]
```
"metadata": {
            "rqlite-0": {
                "api_addr": "rqlite-0.rqlite:4001",
                "api_proto": "http"
            },
            "rqlite-1": {
                "api_addr": "rqlite-1.rqlite:4001",
                "api_proto": "http"
            },
            "rqlite-2": {
                "api_addr": "rqlite-2.rqlite:4001",
                "api_proto": "http"
            },
            "rqlite-4": {
                "api_addr": "rqlite-4.rqlite:4001",
                "api_proto": "http"
            }
        },
        "node_id": "rqlite-1",
        "nodes": [
            {
                "id": "rqlite-0",
                "addr": "10.233.88.18:4002"
            },
            {
                "id": "rqlite-1",
                "addr": "10.233.101.80:4002"
            },
            {
                "id": "rqlite-2",
                "addr": "10.233.109.248:4002"
            },
            {
                "id": "rqlite-3",
                "addr": "10.233.118.211:4002"
            },
            {
                "id": "rqlite-4",
                "addr": "10.233.92.70:4002"
            }
```

This causes the clients to not be able to communicate with any node other than the leader for queries.

rqlite version: 5.5.1
Environment: 5 nodes cluster over kubernetes

this situation happened on a single environment of ours there is not failure in the nodes and election seem to be working fine.
in addition queries to the leader are working ok.

after killing the leader (rqlite-3) the cluster lost sync and the members restarted.

Can you please assist?

**Comment by otoolep** [comment]
Anything in the logs? I agree this doesn't look right, but it's difficult to know what would have caused it without more information. 

Did you perform any remove operations on this cluster before it got into this state?

https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#removing-or-replacing-a-node

Also, can you upgrade to the latest release, 5.11.1? 5.5.1 is a fairly different code base, and I really only have time to debug issues on newer releases.

https://github.com/rqlite/rqlite/releases/tag/v5.11.1

**Comment by Theog75** [comment]
Hey @otoolep I am running 5.11.1 now on several of our environments for some time now (~2h) and it looks really good! 
I will continue testing for a while and will give you feedback if I find any edge cases, In the meantime - I think we can close this issue as it does not happen anymore.

Thanks a bunch!

**Comment by otoolep** [comment]
OK, thanks.
