### ISSUE TITLE
cannot run quries to cluster members - only the leader responds

### ISSUE THREAD

**Issue by Theog75** [rqlite/rqlite#789]
after a while  (a couple of hours/days) our rqlite clusters (V5.11.1) reach a point where we can only query the leader:

for example running the query using any member other than the leader returns:
```
bash-4.4$ /rqlite -H rqlite-0.rqlite
Welcome to the rqlite CLI. Enter ".help" for usage hints.
Connected to version v5.11.1
rqlite-0.rqlite:4001> select * from rules
ERR! server responded with 503 Service Unavailable: not leader

rqlite-0.rqlite:4001> select * from  issues
ERR! server responded with 503 Service Unavailable: not leader

```

 the status response from one of the followers is :
```

curl http://rqlite-0.rqlite:4001/status?pretty


{
    "build": {
        "branch": "master",
        "build_time": "2021-04-13T10:24:42-0400",
        "commit": "927611c82c72056a99e20cde3279fac7fdf51484",
        "version": "v5.11.1"
    },
    "http": {
        "addr": "10.233.122.246:4001",
        "auth": "disabled",
        "redirect": ""
    },
    "node": {
        "start_time": "2021-04-22T19:32:14.932309505Z",
        "uptime": "16h38m28.56345708s"
    },
    "runtime": {
        "GOARCH": "amd64",
        "GOMAXPROCS": 8,
        "GOOS": "linux",
        "num_cpu": 8,
        "num_goroutine": 17,
        "version": "go1.15.7"
    },
    "store": {
        "addr": "10.233.122.246:4002",
        "apply_timeout": "10s",
        "db_conf": {
            "DSN": "",
            "Memory": true
        },
        "dir": "/node",
        "dir_size": 14560570,
        "election_timeout": "5s",
        "heartbeat_timeout": "4s",
        "leader": {
            "addr": "10.233.92.133:4002",
            "node_id": "rqlite-4"
        },
        "metadata": {
            "rqlite-0": {
                "api_addr": "rqlite-0.rqlite:4001",
                "api_proto": "http"
            },
            "rqlite-1": {
                "api_addr": "rqlite-1.rqlite:4001",
                "api_proto": "http"
            },
            "rqlite-2": {
                "api_addr": "rqlite-2.rqlite:4001",
                "api_proto": "http"
            }
        },
        "node_id": "rqlite-0",
        "nodes": [
            {
                "id": "rqlite-0",
                "addr": "10.233.122.246:4002"
            },
            {
                "id": "rqlite-1",
                "addr": "10.233.89.103:4002"
            },
            {
                "id": "rqlite-2",
                "addr": "10.233.67.182:4002"
            },
            {
                "id": "rqlite-3",
                "addr": "10.233.100.143:4002"
            },
            {
                "id": "rqlite-4",
                "addr": "10.233.92.133:4002"
            }
        ],
        "raft": {
            "applied_index": 496115,
            "commit_index": 496115,
            "fsm_pending": 0,
            "last_contact": "21.858677ms",
            "last_log_index": 496115,
            "last_log_term": 28,
            "last_snapshot_index": 494286,
            "last_snapshot_term": 22,
            "latest_configuration": "[{Suffrage:Voter ID:rqlite-3 Address:10.233.100.143:4002} {Suffrage:Voter ID:rqlite-4 Address:10.233.92.133:4002} {Suffrage:Voter ID:rqlite-0 Address:10.233.122.246:4002} {Suffrage:Voter ID:rqlite-2 Address:10.233.67.182:4002} {Suffrage:Voter ID:rqlite-1 Address:10.233.89.103:4002}]",
            "latest_configuration_index": 0,
            "log_size": 8388608,
            "num_peers": 4,
            "protocol_version": 3,
            "protocol_version_max": 3,
            "protocol_version_min": 0,
            "snapshot_version_max": 1,
            "snapshot_version_min": 0,
            "state": "Follower",
            "term": 28
        },
        "request_marshaler": {
            "compression_batch": 5,
            "compression_size": 150,
            "force_compression": false
        },
        "snapshot_interval": 30000000000,
        "snapshot_threshold": 4096,
        "sqlite3": {
            "db_size": 22736896,
            "dsn": "",
            "fk_constraints": "disabled",
            "path": ":memory:",
            "version": "3.34.0"
        },
        "trailing_logs": 5120
    }
} 

```

please notice that in the status metadata there are only 3 nodes and not all 5 members appear under:
```
.store.metadata
```

they do however appear under:
```
.store.nodes
```

the leader actually does not appear in .store.metadata.

Can yo please assist?

Thanks in advance,
L

**Comment by otoolep** [comment]
Thanks for the report. Can you also show me what the leader status is, when this happens?

Can you give me an idea of the lifecycle of the nodes in this cluster? Do you ever explicitly remove nodes?

In the meantime I'll think about this.

**Comment by otoolep** [comment]
Do nodes fail or get deprovisioned which you don't replace?

**Comment by Theog75** [comment]
the nodes are running and sunching the raft , they can however restart (due to mem limit - OOM or timeouts) but there are 5 of them and should 1 restart ) and they do from time to time) it restarts and resyncs with the others.

the nodes do not have a PV instead they keep the data in memory so that if one of them restarts it's data is lost and it resyncs with the others

**Comment by otoolep** [comment]
OK, thanks. I have some ideas, but this could take a few days to complete. Basically I don't think the system needs the "metadata" concept and can just do without it. It's only need to help follower nodes redirect queries to the leader, but I believe there is a more robust way. 

But right now the discrepancy between "metadata" and "nodes" (for whatever reason) is causing your cluster to break.

**Comment by Dorsosiv** [comment]
@otoolep great. we wait for your update :)

**Comment by Theog75** [comment]
Thanks @otoolep !

**Comment by otoolep** [comment]
@Theog75 @Dorsosiv -- are you folks prepared to build top of tree if I make changes? And do your own packaging? Or do you need a release? I would rather have you confirm that what I am doing works and is stable before releasing, if possible.

**Comment by Theog75** [comment]
hi @otoolep we would rather (for our versioning) use a release - with that said - we would love to build and test top of tree and run tests making rqlite even better than it already is, I would however appreciate some readme (if necessary) or do we just build in the project's root?

Thanks again!
L

**Comment by otoolep** [comment]
Is this sufficient direction?

https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite

**Comment by Theog75** [comment]
yup RTFM right you are!  just deployed top of tree version in one of our environments , rolling deployment went perfect, we'll leave it running while testing it (it is under constant stress) for a while and report back I guess in a couple of hours with an update.

Thanks again

**Comment by otoolep** [comment]
I wouldn't expect any improvements yet, watch https://github.com/rqlite/rqlite/pull/792 for now. If that merges into master, then we've got something to try out.

**Comment by otoolep** [comment]
This will take 3-4 days to complete, I'm proposing a change to how the system works (somewhat reverting to a previous design). Basically nodes in the cluster are (somehow) losing information about the HTTP addresses of other nodes (that's all that the metadata tracks), so can't redirect your clients to the leader's HTTP API address. Instead of debugging the issue, I'm just going to move to a more robust design (at the cost of a bit more -- but not a huge amount -- of network traffic between nodes) where followers interrogate the leader for HTTP API addresses on demand.

In the meantime, your cluster should be fully functional, it's only querying followers that need to re-route to the leader that is the issue. You can always work around this problem by inspecting the node status output directly, looking for the leader yourself, and just reconnecting to that node directly. Or just set your read consistency level to none (perhaps combine with freshness -- see the docs on read consistency).

**Comment by otoolep** [comment]
I'm about 33% the way through this, few more days to go. Hopefully you can work around the issues in the meantime.

These changes will probably warrant the start of the 6.0 series. It'll be straightforward to upgrade however, from 5.0.

**Comment by otoolep** [comment]
6.0 would have the same API, so no client code would need to change. This is about some changes to the design, but not the API.

**Comment by Theog75** [comment]
for the time being , the top-of-tree build we deployed is working ok , no leader lose was detected as of yet, when the next version is ready - please let us know and we will happily assist in testing and verifying!.

from our prespective (running on k8s with no storage - i.e. in mem) there is no real impact with a bit more network traffice as it occurs over the SDN in which latency is very low, I would rathar have more traffice than any other resource increase to be fair - so I think it is a good course to follow.

**Comment by otoolep** [comment]
@Theog75 @Dorsosiv -- I have a change ready for you to go. You need to build master to pick it up. Please note that you need to explicitly upgrade your clusters from 5.x to 6.0. Full directions in the CHANGELOG. It's not difficult.

This release completely removes concept of `Metadata` -- the 6.0 design no longer needs it. So the issue you are seeing simply cannot happen anymore. This is a significant change to rqlite, so I would really appreciate it you could run this, and see if it works for you. If it looks good to you, I'll officially release 6.0. All my testing passes.

Thanks for you help.

**Comment by otoolep** [comment]
See https://github.com/rqlite/rqlite/blob/master/CHANGELOG.md#600-unreleased for more information, plus upgrade instructions.

**Comment by Dorsosiv** [comment]
Hey @otoolep , I wondered about the cluster feature you have added in the new release (6.0) I wanted to know how it is working and if it might affect the way we have used rqlite. because now the instances are starting in a flash but their applied_index is not changed at all (tested it for ~ 20 minutes )

**Comment by otoolep** [comment]
Hmm, that is strange. My testing does check for "applied" moving, perhaps you've hit some issue. It's possible, that's why I haven't made a release yet.

How easily can you repro this? Does it happen everytime? I presume you're checking the status API to see that "applied" is not changing? Can you how me the "status" output from each node when this happens?

I will also try to repro.

**Comment by Dorsosiv** [comment]
I can repro it easily. I have tried it several times and it is keep happening. in a few minutes Ill upload some logs

**Comment by Dorsosiv** [comment]
@otoolep do you prefer the logs in a file or to write them here ?

**Comment by otoolep** [comment]
If you can upload, that would be better. Post a link.

**Comment by Dorsosiv** [comment]
These are the .status output of our rqlites

[rqlite-6-logs.txt](https://github.com/rqlite/rqlite/files/6411379/rqlite-6-logs.txt)

**Comment by Dorsosiv** [comment]
@otoolep when we run the rqlite as containers we run them with a bash script that is creating or connecting the instances to a cluster. 
would you like me to share it ? I think that it can help understanding more of the way that the new cluster package might inflict on the script that we are using.

**Comment by otoolep** [comment]
Sure, please post the script. Can you also include the output of the `.expvar` command too, next time you post an update?

I don't see anything wrong with any of the status output you posted. There is a leader, all follower nodes are in contact with the leader, and those followers have received all changes from the leader (`commit_index` == `applied_index` == 6 on all nodes, including the leader).

I want to be sure I understand what you're saying. Is it the following:

- You are making WRITES to the database (sending INSERTs for example)
- You get HTTP OK (200) from the API when you make these requests.
- You never see `applied_index` changing, is that it?

You must make changes to the database for `applied_index` to change. Also, if you join nodes to a cluster `applied_index` will also increment.

If `applied_index` is not changing, even though you are making changes to the database or node are being added, it would mean your cluster is in bad shape. But are you actually seeing problems with your system? If so, what? Maybe you aren't actually making any changes that require `applied_index` to increment?

Please note that this version of rqlite may make fewer changes to `applied_index` than 5.x. There is no guarantee `applied_index` behavior will be same as what you saw before. Not that we shouldn't pay attention to it, but I do want to understand if you're actually seeing problems with your "6.0" cluster.

**Comment by Dorsosiv** [comment]
Ok, so first Im adding here the script and the values of .expvar for each rqlite instance (note that since the .status I have redeployed the rqlite in a different namespace so the IPs will be different).


[expvar-rqlite.txt](https://github.com/rqlite/rqlite/files/6415003/expvar-rqlite.txt)
[rqlite-script.txt](https://github.com/rqlite/rqlite/files/6415010/rqlite-script.txt)

**Comment by otoolep** [comment]
Thanks for the files. I'll see if anything looks suspicious.

So the question I now have (as mentioned before) is what problems, if any, are you actually having with your cluster? You are concerned that `applied_index` is not changing enough, but the behaviour of `applied_index` is different now, relative to 5.0. It may not be an issue.

**Comment by Dorsosiv** [comment]
responding to this: 
```
I want to be sure I understand what you're saying. Is it the following:

You are making WRITES to the database (sending INSERTs for example)
You get HTTP OK (200) from the API when you make these requests.
You never see applied_index changing, is that it?
```
I tested again and the microservice that is connecting and sending data in the tables and creates them does not do that. because the rqlite go package that we use is telling that it has not found a leader :

```
time="2021-05-03T13:17:03" level=error msg="Error in Inserting <function> list: Error connect to database: could not determine leader from API status call"
```
perhaps we should update the client rqlite as well ...

And to answer this question:
```
You never see applied_index changing, is that it
```
At the time I did not see any change for a long time. Now in the latest deployment , which I did less than an hour ago, I do see that the applied_index is increasing but in a very slow pace unlike before (with version 5.X).

**Comment by otoolep** [comment]
Yes, I think the problem now lies in the Go client you are using, and not rqlite. I took a look at the client code, and it's using the API in a way I did not expect.

Are you using https://github.com/rqlite/gorqlite? I can update it.

**Comment by otoolep** [comment]
>>At the time I did not see any change for a long time. Now in the latest deployment , which I did less than an hour ago, I do see that the applied_index is increasing but in a very slow pace unlike before (with version 5.X).

That's because, I would guess, your updates are not actually working due to errors in the client.

**Comment by Dorsosiv** [comment]
> Yes, I think the problem now lies in the Go client you are using, and not rqlite. I took a look at the client code, and it's using the API in a way I did not expect.
> 
> Are you using https://github.com/rqlite/gorqlite? I can update it.

yeah we are using this go client . please update it , waiting for you :)

**Comment by Dorsosiv** [comment]
@otoolep I wanted to ask you if you think that we should use the bash script in the containers to create clusters or to add to an existing cluster of rqlite ?

**Comment by otoolep** [comment]
Yes, I believe continuing to use the script is OK, and should remain so. Basically you are trying to learn the leader of the cluster? Maybe I should add a dedicated endpoint for that, to make it easier.

**Comment by Theog75** [comment]
@otoolep I would love to setup a session if you wish to go through the challanges we encountered wen deploying our rqlite setup, in addition - I think it may benfit other if we could add our experience in prod envs with rqlite and have those added as an rqlite feature?

If it makes sense  drop me an email and I would love to setup a session.
L

**Comment by otoolep** [comment]
Yes, I'd definitely be up for a realtime session -- my email address is in my GitHub profile.

**Comment by otoolep** [comment]
@Theog75 @Dorsosiv -- now that you guys are up and running "6.0" again, let me know if you see any issues. Presumably after 2-3 days of problem-free work, you'll consider this issue closed? You can close it then, or I can.

**Comment by Theog75** [comment]
we are still testing 6.0.0 if we want to follow for a couple of days for more conclusive results, but until now its been running ok so maybe you want to close it

**Comment by otoolep** [comment]
OK, I'm pretty sure this is closed because the Metadata can no longer get out of sync with the Raft cluster state, since Metadata no longer exists. Metadata was only present in the system to allow Follower nodes learn the HTTP address of leader nodes. So signs that we haven't completely solved the issue would be Follower nodes not redirecting to Leaders.

I plan to do more work on the 6.0 code before releasing it. You might like to keep an eye on master every week or so, and rebuild with the latest functionality.

Thanks for all your help.
