### ISSUE TITLE
rqlite 5 crashes right after it starts

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#803]
**What version are you running?**
rqlite 5 (rqlited 5 linux amd64 go1.16.2 (commit unknown, branch unknown))
**What did you do?**
I started a single instance of rqlite
**What did you expect to happen?**
I expected it to run .
**What happened instead?**
it crashed with the error below
Running a single node

            _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |               www.rqlite.com
         |_|

[rqlited] 2021/05/05 13:24:43 rqlited starting, version 5, commit unknown, branch unknown
[rqlited] 2021/05/05 13:24:43 go1.16.2, target architecture is amd64, operating system target is linux
[rqlited] 2021/05/05 13:24:43 launch command: /rqlited -node-id rqlite-0 -http-addr rqlite-0.rqlite:4001 /node
[rqlited] 2021/05/05 13:24:43 no preexisting node state detected in /node, node may be bootstrapping
[rqlited] 2021/05/05 13:24:43 no join addresses set
[store] 2021/05/05 13:24:43 opening store with node ID rqlite-0
[store] 2021/05/05 13:24:43 ensuring directory at /node exists
[store] 2021/05/05 13:24:43 0 preexisting snapshots present
[store] 2021/05/05 13:24:43 first log index: 0, last log index: 0, last command log index: 0:
2021-05-05T13:24:43.676Z [INFO]  raft: initial configuration: index=0 servers=[]
[store] 2021/05/05 13:24:43 executing new cluster bootstrap
2021-05-05T13:24:43.676Z [INFO]  raft: entering follower state: follower="Node at 127.0.0.1:4002 [Follower]" leader=
2021-05-05T13:24:45.563Z [WARN]  raft: heartbeat timeout reached, starting election: last-leader=
2021-05-05T13:24:45.564Z [INFO]  raft: entering candidate state: node="Node at 127.0.0.1:4002 [Candidate]" term=2
2021-05-05T13:24:45.574Z [INFO]  raft: election won: tally=1
2021-05-05T13:24:45.574Z [INFO]  raft: entering leader state: leader="Node at 127.0.0.1:4002 [Leader]"
[store] 2021/05/05 13:24:45 waiting for up to 2m0s for application of initial logs
[http] 2021/05/05 13:24:45 service listening on 10.131.0.174:4001
[rqlited] 2021/05/05 13:24:45 node is ready
[rqlited] 2021/05/05 13:24:46 http: panic serving 10.131.3.44:38582: interface conversion: driver.Stmt is nil, not *sqlite3.SQLiteStmt
goroutine 15 [running]:
net/http.(*conn).serve.func1(0xc00014a820)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0xbb6de0, 0xc00058a000)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/rqlite/go-sqlite3.(*SQLiteConn).query(0xc0000212c0, 0xd6d270, 0xc0000300a8, 0xc0005cc030, 0x23, 0x115f7f8, 0x0, 0x0, 0xc00035f688, 0x47781b, ...)
	/home/theog/go/src/rqlitesource/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:864 +0x766
github.com/rqlite/go-sqlite3.(*SQLiteConn).Query(0xc0000212c0, 0xc0005cc030, 0x23, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000091e38, 0x28dfe31223e2ff01)
	/home/theog/go/src/rqlitesource/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:853 +0x138
github.com/rqlite/rqlite/db.(*DB).Query.func1(0xc00013f8f0, 0xc96e00, 0xc0005a20f0, 0xc00035f870, 0x1, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:428 +0x2d6
github.com/rqlite/rqlite/db.(*DB).Query(0xc00013f8f0, 0xc0005a20f0, 0xc1bd01, 0x1, 0xc0005a20a0, 0xc00035f9e0, 0xa4ec85, 0xc1bd40)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:459 +0xa5
github.com/rqlite/rqlite/store.(*Store).Query(0xc000093ba0, 0xc0005a00c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/store/store.go:675 +0x125
github.com/rqlite/rqlite/http.(*Service).handleQuery(0xc00034c0e0, 0xd6bd80, 0xc00053a0e0, 0xc0005ca000)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/http/service.go:721 +0x3f5
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc00034c0e0, 0xd6bd80, 0xc00053a0e0, 0xc0005ca000)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/http/service.go:253 +0x551
net/http.serverHandler.ServeHTTP(0xc00034c1c0, 0xd6bd80, 0xc00053a0e0, 0xc0005ca000)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00014a820, 0xd6d2e0, 0xc000155500)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
rqlite-0.rqlite:4001> .status
store:
  node_id: rqlite-0
  raft:
    applied_index: 1455
    last_contact: 0
    last_snapshot_index: 0
    num_peers: 0
    protocol_version_max: 3
    snapshot_version_min: 0
    fsm_pending: 0
    protocol_version: 3
    commit_index: 1455
    last_log_index: 1455
    snapshot_version_max: 1
    term: 2
    last_log_term: 2
    last_snapshot_term: 0
    latest_configuration: [{Suffrage:Voter ID:rqlite-0 Address:127.0.0.1:4002}]
    latest_configuration_index: 0
    log_size: 4.194304e+06
    protocol_version_min: 0
    state: Leader
  snapshot_threshold: 8192
  addr: 127.0.0.1:4002
  db_conf:
    DSN: 
    Memory: true
  metadata:
    rqlite-0:
      api_addr: rqlite-0.rqlite:4001
      api_proto: http
  snapshot_interval: 3e+10
  dir: /node
  dir_size: 4.194304e+06
  sqlite3:
    db_size: 1.826816e+06
    dsn: 
    fk_constraints: disabled
    path: :memory:
    version: 3.35.4
  trailing_logs: 10240
  request_marshaler:
    compression_batch: 5
    compression_size: 150
    force_compression: false
  apply_timeout: 10s
  election_timeout: 1s
  heartbeat_timeout: 1s
  leader:
    addr: 127.0.0.1:4002
    node_id: rqlite-0
  nodes: [map[addr:127.0.0.1:4002 id:rqlite-0]]
build:
  build_time: unknown
  commit: unknown
  version: 5
  branch: unknown
http:
  addr: 10.131.0.182:4001
  auth: disabled
  redirect: rqlite-0.rqlite:4001
node:
  start_time: 2021-05-05T13:32:57.489471828Z
  uptime: 5m29.367501829s
runtime:
  GOMAXPROCS: 8
  GOOS: linux
  num_cpu: 8
  num_goroutine: 21
  version: go1.16.2
  GOARCH: amd64

rqlite-0.rqlite:4001> .expvar
memstats:
  Sys: 7.5842568e+07
  Mallocs: 4.917605e+06
  MSpanInuse: 150688
  BuckHashSys: 1.553272e+06
  NumForcedGC: 0
  HeapReleased: 5.3346304e+07
  MCacheInuse: 9600
  OtherSys: 1.631392e+06
  NextGC: 1.0121216e+07
  PauseTotalNs: 9.70492472e+08
  HeapSys: 6.602752e+07
  HeapIdle: 5.5853056e+07
  StackInuse: 1.081344e+06
  Alloc: 7.623488e+06
  MCacheSys: 16384
  PauseEnd: [1.6202218789489846e+18 1.620221879345734e+18 1.620221879739074e+18 1.6202218798741258e+18 1.6202218799580902e+18 1.620221880061197e+18 1.6202218802763384e+18 1.620221880745002e+18 1.6202218818835039e+18 1.6202218827809226e+18 1.6202218831044273e+18 1.6202218832419692e+18 1.620221883823055e+18 1.6202218842436992e+18 1.6202218845516424e+18 1.6202218847596321e+18 1.6202218848395346e+18 1.6202218851689185e+18 1.6202218854427195e+18 1.6202218857438456e+18 1.6202218862767094e+18 1.6202218867327452e+18 1.620221887928141e+18 1.6202218886000924e+18 1.6202218887861368e+18 1.6202218888168292e+18 1.620221888848772e+18 1.6202218896564001e+18 1.6202218903219174e+18 1.620221890538191e+18 1.6202218905641874e+18 1.6202218906399798e+18 1.6202218912274117e+18 1.620221891334042e+18 1.6202218924286346e+18 1.620221892551672e+18 1.6202218929306148e+18 1.620221893414535e+18 1.6202218943357197e+18 1.6202218949647076e+18 1.620221895561351e+18 1.620221895784057e+18 1.6202218959158323e+18 1.620221896140512e+18 1.620221896156949e+18 1.6202218962762048e+18 1.6202218969556695e+18 1.620221897620041e+18 1.6202218980668995e+18 1.6202218986271741e+18 1.6202218989120768e+18 1.6202218992235154e+18 1.6202218995583572e+18 1.6202218999278083e+18 1.620221900744946e+18 1.6202219008323103e+18 1.620221901930196e+18 1.62022190233113e+18 1.6202219024821102e+18 1.6202219026575762e+18 1.620221902732654e+18 1.6202219037210952e+18 1.620221903833088e+18 1.6202219050247544e+18 1.620221905568049e+18 1.6202219056406113e+18 1.6202219060427105e+18 1.620221906150067e+18 1.6202219062195348e+18 1.6202219067488174e+18 1.6202219071353244e+18 1.620221907349761e+18 1.620221907378833e+18 1.620221908159639e+18 1.6202219086479693e+18 1.6202219092334067e+18 1.6202219101761746e+18 1.6202219105186831e+18 1.6202219108403528e+18 1.6202219110583137e+18 1.620221911139384e+18 1.6202219113653647e+18 1.6202219118298967e+18 1.620221912442973e+18 1.6202219125070252e+18 1.6202219125950682e+18 1.620221912817721e+18 1.6202219136139443e+18 1.6202219146427525e+18 1.6202219152566966e+18 1.6202219160590147e+18 1.620221916944837e+18 1.6202219177509934e+18 1.620221918173166e+18 1.6202219182590807e+18 1.6202219185161175e+18 1.6202219189241372e+18 1.620221919627248e+18 1.6202219198468175e+18 1.6202219203417288e+18 1.6202219207792835e+18 1.620221921652589e+18 1.620221922289064e+18 1.620221922856023e+18 1.6202219233920522e+18 1.6202219236473649e+18 1.620221924133016e+18 1.6202219252782392e+18 1.62022192543712e+18 1.6202219256509501e+18 1.6202219257150966e+18 1.6202219260252849e+18 1.620221926530995e+18 1.6202219271363177e+18 1.620221928050766e+18 1.6202219283403264e+18 1.6202219284592922e+18 1.620221928562268e+18 1.620221928924156e+18 1.6202219303161513e+18 1.6202219306175416e+18 1.6202219308718113e+18 1.6202219311657352e+18 1.620221931301332e+18 1.6202219313751895e+18 1.6202219323198853e+18 1.6202219328462228e+18 1.6202219331131192e+18 1.6202219350513838e+18 1.6202219356622825e+18 1.620221936190938e+18 1.6202219364299999e+18 1.6202219378642929e+18 1.6202219386359475e+18 1.6202219392245432e+18 1.620221939532299e+18 1.6202219397029181e+18 1.6202219409392906e+18 1.6202219416482437e+18 1.6202219418305587e+18 1.6202219425580352e+18 1.620221942716566e+18 1.6202219432767662e+18 1.6202219438199508e+18 1.6202219440531423e+18 1.6202219445492035e+18 1.620221835195474e+18 1.6202218353588104e+18 1.620221835547726e+18 1.620221835759085e+18 1.620221836052692e+18 1.620221836152294e+18 1.620221836247388e+18 1.6202218368895314e+18 1.620221837637197e+18 1.6202218380369126e+18 1.6202218385502124e+18 1.620221839274021e+18 1.6202218399323556e+18 1.6202218404482066e+18 1.620221841262591e+18 1.620221841328601e+18 1.620221841537542e+18 1.6202218421513684e+18 1.6202218427510902e+18 1.6202218431308234e+18 1.6202218433509786e+18 1.6202218434332552e+18 1.620221843462582e+18 1.6202218435041958e+18 1.6202218438660795e+18 1.6202218439515436e+18 1.620221844030033e+18 1.62022184413034e+18 1.6202218442635459e+18 1.6202218443241395e+18 1.620221844356208e+18 1.6202218445436178e+18 1.6202218447649828e+18 1.6202218449668145e+18 1.6202218455409807e+18 1.620221846228881e+18 1.620221846466263e+18 1.620221847590311e+18 1.6202218476326812e+18 1.6202218485397166e+18 1.6202218486491694e+18 1.620221848842574e+18 1.6202218495423224e+18 1.6202218497058132e+18 1.6202218502577608e+18 1.6202218506814351e+18 1.6202218509442432e+18 1.6202218524469258e+18 1.6202218528203776e+18 1.6202218533330668e+18 1.6202218536335058e+18 1.620221853758107e+18 1.6202218545228424e+18 1.620221854726524e+18 1.6202218552600689e+18 1.6202218554641626e+18 1.6202218554879736e+18 1.620221855641752e+18 1.6202218558389522e+18 1.620221855869009e+18 1.6202218559234542e+18 1.6202218566272832e+18 1.62022185774975e+18 1.620221859152376e+18 1.6202218592444104e+18 1.6202218595310994e+18 1.620221860023935e+18 1.6202218607321393e+18 1.6202218617753705e+18 1.6202218618338463e+18 1.6202218619265649e+18 1.6202218620406013e+18 1.6202218621329308e+18 1.6202218622412321e+18 1.6202218626479657e+18 1.620221863144076e+18 1.620221863324242e+18 1.6202218636263816e+18 1.6202218649146737e+18 1.620221865264601e+18 1.6202218656544748e+18 1.6202218657712796e+18 1.6202218662803e+18 1.6202218663556106e+18 1.62022186643036e+18 1.620221866921367e+18 1.6202218671722568e+18 1.6202218686379192e+18 1.6202218691477294e+18 1.6202218698268995e+18 1.620221870041918e+18 1.6202218702279875e+18 1.6202218705376632e+18 1.6202218714357978e+18 1.6202218720439462e+18 1.6202218721199316e+18 1.6202218721650127e+18 1.620221872234194e+18 1.6202218723098744e+18 1.620221872637113e+18 1.6202218734607992e+18 1.6202218749218542e+18 1.620221875638483e+18 1.6202218757502351e+18 1.620221875756317e+18 1.620221875844607e+18 1.6202218761614976e+18 1.6202218765501448e+18 1.6202218776464105e+18 1.6202218782503683e+18]
  NumGC: 914
  Lookups: 0
  HeapAlloc: 7.623488e+06
  HeapObjects: 20351
  LastGC: 1.6202219445492035e+18
  GCCPUFraction: 0.0039556125176450005
  StackSys: 1.081344e+06
  BySize: [map[Frees:0 Mallocs:0 Size:0] map[Frees:59858 Mallocs:60355 Size:8] map[Frees:2.220785e+06 Mallocs:2.222784e+06 Size:16] map[Frees:176474 Mallocs:176749 Size:24] map[Frees:85637 Mallocs:85884 Size:32] map[Frees:331636 Mallocs:345210 Size:48] map[Frees:121366 Mallocs:121709 Size:64] map[Frees:163314 Mallocs:163431 Size:80] map[Frees:89015 Mallocs:89997 Size:96] map[Frees:32848 Mallocs:32968 Size:112] map[Frees:85915 Mallocs:86152 Size:128] map[Frees:20797 Mallocs:20848 Size:144] map[Frees:10726 Mallocs:10792 Size:160] map[Frees:37272 Mallocs:37836 Size:176] map[Frees:8198 Mallocs:8366 Size:192] map[Frees:23719 Mallocs:23783 Size:208] map[Frees:10599 Mallocs:10610 Size:224] map[Frees:5531 Mallocs:5547 Size:240] map[Frees:9737 Mallocs:9770 Size:256] map[Frees:35838 Mallocs:35880 Size:288] map[Frees:4119 Mallocs:4129 Size:320] map[Frees:24089 Mallocs:24138 Size:352] map[Frees:3070 Mallocs:3315 Size:384] map[Frees:4187 Mallocs:4201 Size:416] map[Frees:1132 Mallocs:1157 Size:448] map[Frees:5630 Mallocs:5660 Size:480] map[Frees:7115 Mallocs:7135 Size:512] map[Frees:10904 Mallocs:10945 Size:576] map[Frees:5002 Mallocs:5040 Size:640] map[Frees:17876 Mallocs:17942 Size:704] map[Frees:6680 Mallocs:6699 Size:768] map[Frees:5785 Mallocs:5864 Size:896] map[Frees:17158 Mallocs:17206 Size:1024] map[Frees:16197 Mallocs:16212 Size:1152] map[Frees:5024 Mallocs:5034 Size:1280] map[Frees:1466 Mallocs:1472 Size:1408] map[Frees:4329 Mallocs:4332 Size:1536] map[Frees:2967 Mallocs:2979 Size:1792] map[Frees:1917 Mallocs:1925 Size:2048] map[Frees:7726 Mallocs:7740 Size:2304] map[Frees:2072 Mallocs:2081 Size:2688] map[Frees:1576 Mallocs:1579 Size:3072] map[Frees:20 Mallocs:21 Size:3200] map[Frees:385 Mallocs:388 Size:3456] map[Frees:4905 Mallocs:4974 Size:4096] map[Frees:2328 Mallocs:2332 Size:4864] map[Frees:1015 Mallocs:1021 Size:5376] map[Frees:464 Mallocs:466 Size:6144] map[Frees:126 Mallocs:126 Size:6528] map[Frees:706 Mallocs:708 Size:6784] map[Frees:38 Mallocs:38 Size:6912] map[Frees:6326 Mallocs:6334 Size:8192] map[Frees:963 Mallocs:968 Size:9472] map[Frees:152 Mallocs:153 Size:9728] map[Frees:178 Mallocs:186 Size:10240] map[Frees:151 Mallocs:151 Size:10880] map[Frees:444 Mallocs:445 Size:12288] map[Frees:57 Mallocs:57 Size:13568] map[Frees:61 Mallocs:71 Size:14336] map[Frees:348 Mallocs:352 Size:16384] map[Frees:185 Mallocs:186 Size:18432]]
  TotalAlloc: 2.03245072e+09
  MSpanSys: 180224
  EnableGC: true
  Frees: 4.897254e+06
  HeapInuse: 1.0174464e+07
  GCSys: 5.352432e+06
  PauseNs: [3.59074e+06 168269 114236 6.009011e+06 118941 143680 143010 266672 227126 196334 240849 158521 370965 5.909397e+06 568635 95418 4.339163e+06 117072 206501 188151 279147 207990 1.1127581e+07 215217 255112 194695 542268 137602 1.453058e+06 153569 302438 455847 5.82728e+06 134152 100314 89990 7.559462e+06 75160 128159 212556 261803 106574 169080 87005 193356 1.604868e+06 178965 626804 187724 184780 165527 2.30742e+06 1.7739519e+07 150654 287435 9.397487e+06 213040 207290 2.530901e+06 165200 131476 144673 97219 285855 147303 154726 1.5913737e+07 152098 613039 729447 116086 208747 76427 184556 562620 203680 209624 973042 1.493548e+06 134526 135033 157459 3.929322e+06 155427 119874 109692 96376 835683 329446 79529 191668 233878 236734 142857 112594 855032 558942 159513 110952 1.929241e+06 175941 351025 767331 160054 253745 115540 219163 365909 6.482034e+06 980736 103577 786436 144087 535613 135166 87757 99088 149812 177640 128313 505425 1.059332e+06 113253 91045 130220 210854 167519 133793 388996 118034 233416 1.253841e+06 311562 1.158132e+06 296614 145426 311793 239928 211409 154165 108379 344182 80671 2.680897e+06 448030 239396 175272 2.0662234e+07 1.954686e+06 2.3165646e+07 245310 345526 118629 108317 165791 5.652195e+06 109750 149953 602402 175215 196575 294755 832819 132932 1.233696e+06 158396 177220 4.317534e+06 81514 67937 160262 158944 130747 2.283367e+06 93844 119074 108211 180041 172544 506964 1.510599e+06 9.574692e+06 146965 134825 161111 5.54699e+06 3.452065e+06 1.255331e+06 184109 101250 134953 866325 139622 163727 148899 125652 109702 112109 980145 560209 2.883551e+06 1.418137e+06 142222 128488 319636 93777 123971 256681 216791 230688 113801 896667 1.949953e+06 275794 173884 105398 179480 1.853228e+06 3.957001e+06 600195 174495 204569 249316 126691 290195 559555 1.374788e+06 119184 178119 6.495103e+06 8.923234e+06 137368 286593 233421 130573 106818 3.400691e+06 131469 185332 4.51929e+06 4.744362e+06 8.166285e+06 2.947047e+06 136459 120592 171305 108049 136650 191853 7.732978e+06 128663 1.1469743e+07 523642 161553 140348 202704]
  DebugGC: false
proto:
  num_uncompressed_requests: 74
  num_compressed_bytes: 3.002483e+06
  num_compressed_requests: 1503
  num_compression_misses: 35
  num_precompressed_bytes: 2.2399635e+07
  num_requests: 0
  num_uncompressed_bytes: 8328
store:
  num_compressed_commands: 1503
  num_legacy_commands: 0
  num_restores: 0
  num_snapshots: 0
  num_uncompressed_commands: 109
  num_backups: 0
cmdline: [/rqlited -node-id rqlite-0 -http-addr rqlite-0.rqlite:4001 /node]
db:
  execute_transactions: 0
  execution_errors: 16
  executions: 21917
  queries: 4083
  query_transactions: 0
http:
  authOK: 5696
  backups: 0
  executions: 1612
  joins: 0
  loads: 0
  queries: 1247
  authFail: 0

See https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by otoolep** [comment]
What commit did you build? Why are you building 5? If you want to run 5.x, can you run an official 5.12.1 build? 

https://github.com/rqlite/rqlite/releases/tag/v5.12.1

Or can you just build top-of-tree? I'm unlikely to have the time to debug issues in builds you make yourself, unless you're building from master.

**Comment by otoolep** [comment]
I actually think this issue was fixed via https://github.com/rqlite/rqlite/pull/783 but you need to tell me the commit you're building.

**Comment by Dorsosiv** [comment]
yeah , Ill close it.
