### ISSUE TITLE
rqlite 6 is failing to communicate with go rqlite .

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#804]
**What version are you running?**
/rqlited --version (rqlite 6)

**What did you do?**
we tested rqlite with a single instance deployed. and we tried to communicate to it with the new gorqlite for version 6. it does not find the leader.

**What did you expect to happen?**
we expected it to find the leader (if it is one instance or many)

**What happened instead?**
the gorqlite is not communicating to the rqlite 

error log is :
"could not determine leader from API nodes call"

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
bash-4.4$ /rqlite -H rqlite-0.rqlite
Welcome to the rqlite CLI. Enter ".help" for usage hints.
Connected to version 6
rqlite-0.rqlite:4001> .tables

rqlite-0.rqlite:4001> .status
runtime:
  num_cpu: 8
  num_goroutine: 19
  version: go1.15.6
  GOARCH: amd64
  GOMAXPROCS: 8
  GOOS: linux
store:
  dir_size: 65536
  trailing_logs: 10240
  addr: 127.0.0.1:4002
  apply_timeout: 10s
  dir: /node
  db_conf:
    DSN: 
    Memory: true
  leader:
    addr: 127.0.0.1:4002
    node_id: rqlite-0
  sqlite3:
    dsn: 
    fk_constraints: disabled
    path: :memory:
    version: 3.35.4
    db_size: 0
  nodes: [map[addr:127.0.0.1:4002 id:rqlite-0]]
  raft:
    fsm_pending: 0
    last_snapshot_term: 0
    latest_configuration: [{Suffrage:Voter ID:rqlite-0 Address:127.0.0.1:4002}]
    protocol_version_min: 0
    state: Leader
    applied_index: 9
    last_contact: 0
    last_snapshot_index: 0
    snapshot_version_min: 0
    last_log_term: 2
    protocol_version: 3
    protocol_version_max: 3
    term: 2
    commit_index: 9
    last_log_index: 9
    latest_configuration_index: 0
    log_size: 65536
    num_peers: 0
    snapshot_version_max: 1
  snapshot_interval: 3e+10
  snapshot_threshold: 8192
  election_timeout: 1s
  heartbeat_timeout: 1s
  node_id: rqlite-0
  request_marshaler:
    compression_batch: 5
    compression_size: 150
    force_compression: false
build:
  build_time: unknown
  commit: unknown
  version: 6
  branch: unknown
cluster:
  addr: 127.0.0.1:4002
  api_addr: rqlite-0.rqlite:4001
  https: false
  timeout: 10s
http:
  addr: 10.131.3.47:4001
  auth: disabled
  redirect: http://rqlite-0.rqlite:4001
node:
  uptime: 59.699570285s
  start_time: 2021-05-05T13:46:59.765620122Z

rqlite-0.rqlite:4001> .nodes
Error: near ".": syntax error

rqlite-0.rqlite:4001> .expvar
db:
  queries: 1853
  query_transactions: 0
  execute_transactions: 27
  execution_errors: 29
  executions: 29
http:
  authFail: 0
  authOK: 1883
  backups: 0
  executions: 29
  joins: 0
  loads: 0
  queries: 1
memstats:
  NumGC: 51
  EnableGC: true
  DebugGC: false
  OtherSys: 1.93025e+06
  PauseNs: [202713 706240 396694 289249 877297 1.068086e+06 901175 625602 199921 348718 877275 412814 3.147832e+06 303951 1.0395329e+07 770717 394686 134200 858252 385318 2.106981e+06 2.51719e+06 1.401081e+06 778537 488629 109962 762027 868354 473998 135059 7.948371e+06 491285 865764 385896 536566 606354 428153 268086 436344 9.966083e+06 892215 312478 323244 2.170548e+06 640025 291163 466359 581310 403093 240869 931548 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  PauseTotalNs: 6.2123641e+07
  MSpanInuse: 134776
  MSpanSys: 163840
  HeapReleased: 6.0547072e+07
  NumForcedGC: 0
  Alloc: 2.995128e+06
  Lookups: 0
  StackSys: 1.14688e+06
  MCacheSys: 16384
  BySize: [map[Frees:0 Mallocs:0 Size:0] map[Frees:15367 Mallocs:15996 Size:8] map[Frees:416163 Mallocs:426841 Size:16] map[Frees:60177 Mallocs:61902 Size:32] map[Frees:109757 Mallocs:112978 Size:48] map[Frees:13993 Mallocs:14571 Size:64] map[Frees:13369 Mallocs:13728 Size:80] map[Frees:46516 Mallocs:47913 Size:96] map[Frees:9070 Mallocs:9374 Size:112] map[Frees:12139 Mallocs:12492 Size:128] map[Frees:7605 Mallocs:7817 Size:144] map[Frees:4055 Mallocs:4204 Size:160] map[Frees:140 Mallocs:211 Size:176] map[Frees:73 Mallocs:92 Size:192] map[Frees:9223 Mallocs:9483 Size:208] map[Frees:3458 Mallocs:3540 Size:224] map[Frees:3676 Mallocs:3766 Size:240] map[Frees:3507 Mallocs:3642 Size:256] map[Frees:21825 Mallocs:22341 Size:288] map[Frees:161 Mallocs:166 Size:320] map[Frees:10085 Mallocs:10329 Size:352] map[Frees:1815 Mallocs:2150 Size:384] map[Frees:14 Mallocs:21 Size:416] map[Frees:3 Mallocs:6 Size:448] map[Frees:1837 Mallocs:1884 Size:480] map[Frees:1876 Mallocs:1921 Size:512] map[Frees:5505 Mallocs:5639 Size:576] map[Frees:1910 Mallocs:1960 Size:640] map[Frees:7 Mallocs:16 Size:704] map[Frees:1814 Mallocs:1858 Size:768] map[Frees:26 Mallocs:30 Size:896] map[Frees:479 Mallocs:513 Size:1024] map[Frees:5552 Mallocs:5684 Size:1152] map[Frees:94 Mallocs:102 Size:1280] map[Frees:4 Mallocs:8 Size:1408] map[Frees:3624 Mallocs:3709 Size:1536] map[Frees:3631 Mallocs:3721 Size:1792] map[Frees:113 Mallocs:123 Size:2048] map[Frees:139 Mallocs:146 Size:2304] map[Frees:79 Mallocs:93 Size:2688] map[Frees:1 Mallocs:1 Size:3072] map[Frees:0 Mallocs:1 Size:3200] map[Frees:0 Mallocs:2 Size:3456] map[Frees:301 Mallocs:334 Size:4096] map[Frees:59 Mallocs:61 Size:4864] map[Frees:0 Mallocs:3 Size:5376] map[Frees:0 Mallocs:2 Size:6144] map[Frees:0 Mallocs:0 Size:6528] map[Frees:0 Mallocs:0 Size:6784] map[Frees:0 Mallocs:0 Size:6912] map[Frees:3625 Mallocs:3710 Size:8192] map[Frees:0 Mallocs:2 Size:9472] map[Frees:0 Mallocs:0 Size:9728] map[Frees:0 Mallocs:8 Size:10240] map[Frees:0 Mallocs:0 Size:10880] map[Frees:0 Mallocs:0 Size:12288] map[Frees:0 Mallocs:0 Size:13568] map[Frees:0 Mallocs:1 Size:14336] map[Frees:1 Mallocs:1 Size:16384] map[Frees:0 Mallocs:0 Size:18432] map[Frees:0 Mallocs:0 Size:19072]]
  TotalAlloc: 1.2343216e+08
  Sys: 7.5580416e+07
  GCCPUFraction: 0.0002827184106904746
  HeapSys: 6.5929216e+07
  PauseEnd: [1.6202224295363123e+18 1.6202224332640484e+18 1.620222437845849e+18 1.620222442142221e+18 1.6202224486047903e+18 1.6202224530367322e+18 1.6202224576409336e+18 1.6202224655369544e+18 1.6202224706349752e+18 1.620222475030707e+18 1.6202224807290207e+18 1.6202224855478879e+18 1.6202224927551178e+18 1.620222495835903e+18 1.6202225008417254e+18 1.6202225071294241e+18 1.6202225150872466e+18 1.6202225170275773e+18 1.6202225229201805e+18 1.6202225284317148e+18 1.6202225364371917e+18 1.6202225393332452e+18 1.6202225444213166e+18 1.6202225518879022e+18 1.6202225579157356e+18 1.6202225605071227e+18 1.6202225651319862e+18 1.6202225709217244e+18 1.6202225791383334e+18 1.6202225811660173e+18 1.6202225874306568e+18 1.620222593885821e+18 1.620222600717323e+18 1.620222602540015e+18 1.620222607407e+18 1.6202226148884995e+18 1.6202226218298104e+18 1.6202226234656932e+18 1.620222628832819e+18 1.620222636824081e+18 1.6202226434150758e+18 1.6202226460261906e+18 1.6202226505631596e+18 1.620222657519586e+18 1.6202226645167465e+18 1.6202226660369777e+18 1.620222673441941e+18 1.6202226803507407e+18 1.6202226854242e+18 1.6202226868882452e+18 1.6202226934140137e+18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  Mallocs: 873133
  HeapObjects: 22228
  MCacheInuse: 13888
  HeapAlloc: 2.995128e+06
  HeapInuse: 4.595712e+06
  StackInuse: 1.14688e+06
  BuckHashSys: 1.464222e+06
  GCSys: 4.929624e+06
  NextGC: 4.194304e+06
  LastGC: 1.6202226934140137e+18
  Frees: 850905
  HeapIdle: 6.1333504e+07
mux:
  num_connections_handled: 1852
  num_unregistered_handlers: 0
proto:
  num_uncompressed_bytes: 25
  num_uncompressed_requests: 2
  num_compressed_bytes: 0
  num_compressed_requests: 0
  num_compression_misses: 27
  num_precompressed_bytes: 6421
  num_requests: 0
store:
  num_backups: 0
  num_compressed_commands: 0
  num_restores: 0
  num_snapshots: 0
  num_uncompressed_commands: 29
cluster:
  num_get_node_api_resp: 1852
  num_get_node_api: 1852
  num_get_node_api_req: 1852
cmdline: [/rqlited -node-id rqlite-0 -http-addr rqlite-0.rqlite:4001 /node]

See https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by otoolep** [comment]
Please show me the output of 

`curl rqlite-0.rqlite:4001/nodes?pretty`

I need to see the raw response from the node.

**Comment by Dorsosiv** [comment]
bash-4.4$ curl rqlite-0.rqlite:4001/nodes?pretty
bash-4.4$

**Comment by otoolep** [comment]
Sorry, enter this:

`curl -v rqlite-0.rqlite:4001/nodes?pretty`

**Comment by Dorsosiv** [comment]
# curl -v rqlite-0.rqlite:4001/nodes?pretty
*   Trying 10.131.3.47...
* TCP_NODELAY set
* Connected to rqlite-0.rqlite (10.131.3.47) port 4001 (#0)
> GET /nodes?pretty HTTP/1.1
> Host: rqlite-0.rqlite:4001
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< X-Rqlite-Version: 6
< Date: Wed, 05 May 2021 14:02:50 GMT
< Content-Length: 0
< 
* Connection #0 to host rqlite-0.rqlite left intact

**Comment by otoolep** [comment]
You're not running the latest rqlite software. You need to rebuild master. @Theog75 had exactly the same issue.

See https://github.com/rqlite/rqlite/issues/798#issuecomment-831945019

I'm closing this because I'm pretty sure this is the same issue.
