### ISSUE TITLE
version flag to rqlite cli

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#806]
**Is your feature request related to a problem? Please describe.**
no it is not

**Describe the solution you'd like**
when running rqlite --version (to check version of the cli ) I will see an output of the version.

**Describe alternatives you've considered**
I do not have alternatives, I just hope that it is the client for rqlite 6 . (although there is not change in the CLI API. but just to be sure the version flag will be very helpful.)

**Additional context**

**Comment by otoolep** [comment]
Reasonable request. See https://github.com/rqlite/rqlite/pull/807

**Comment by otoolep** [comment]
Fixed, though you will need to build your own code to see the changes until I release 6.0.
