### ISSUE TITLE
rqlite instance panics when cannot get log from other instances

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#812]
**What version are you running?**
unreleased-6.0

**What did you do?**
The instance of rqlite restarted for some reason. the last restart I could capture was because of the following log:

```
Trying to join cluster at rqlite-4.....
[rqlited] 2021/05/21 11:46:40 rqlited starting, version 6, commit unknown, branch unknown
[rqlited] 2021/05/21 11:46:40 go1.16.2, target architecture is amd64, operating system target is linux
[rqlited] 2021/05/21 11:46:40 launch command: /rqlited -node-id rqlite-0 -raft-snap 4096 -raft-timeout 4s -raft-election-timeout 5s -join-attempts 5 -http-addr rqlite-0.rqlite:4001 -raft-addr rqlite-0.rqlite:4002 -join http://rqlite-4.rqlite:4001 /node

            _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |               www.rqlite.com
         |_|

[rqlited] 2021/05/21 11:46:40 no preexisting node state detected in /node, node may be bootstrapping
[rqlited] 2021/05/21 11:46:40 join addresses specified, node is not bootstrapping
[store] 2021/05/21 11:46:40 opening store with node ID rqlite-0
[store] 2021/05/21 11:46:40 ensuring directory at /node exists
[store] 2021/05/21 11:46:40 0 preexisting snapshots present
[mux] 2021/05/21 11:46:40 mux serving on 10.244.5.70:4002, advertising 10.244.5.70:4002
[store] 2021/05/21 11:46:40 first log index: 0, last log index: 0, last command log index: 0:
2021-05-21T11:46:40.096Z [INFO]  raft: initial configuration: index=0 servers=[]
[store] 2021/05/21 11:46:40 no cluster bootstrap requested
[rqlited] 2021/05/21 11:46:40 join addresses are: [http://rqlite-4.rqlite:4001]
2021-05-21T11:46:40.096Z [INFO]  raft: entering follower state: follower="Node at 10.244.5.70:4002 [Follower]" leader=
[rqlited] 2021/05/21 11:46:40 successfully joined cluster at http://rqlite-4.rqlite:4001/join
[mux] 2021/05/21 11:46:40 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[mux] 2021/05/21 11:46:40 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[store] 2021/05/21 11:46:40 waiting for up to 2m0s for application of initial logs
[cluster] 2021/05/21 11:46:40 service listening on 10.244.5.70:4002
[http] 2021/05/21 11:46:40 service listening on 10.244.5.70:4001
[rqlited] 2021/05/21 11:46:40 node is ready
2021-05-21T11:46:41.277Z [WARN]  raft: failed to get previous log: previous-index=375 last-index=0 error="log not found"
panic: interface conversion: driver.Stmt is nil, not *sqlite3.SQLiteStmt

goroutine 26 [running]:
github.com/rqlite/go-sqlite3.(*SQLiteConn).exec(0xc0000bb2c0, 0xd6f5f0, 0xc0000b6060, 0xc00057cc00, 0x166, 0x11628f8, 0x0, 0x0, 0xc0000ab960, 0x47781b, ...)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:803 +0x78e
github.com/rqlite/go-sqlite3.(*SQLiteConn).Exec(0xc0000bb2c0, 0xc00057cc00, 0x166, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd62040, 0xc00014f4d0)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:792 +0x138
github.com/rqlite/rqlite/db.(*DB).Execute.func1(0xc0000abaf0, 0xc9a400, 0xc00014fc50, 0xc0005700a0, 0x501, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:321 +0x2b4
github.com/rqlite/rqlite/db.(*DB).Execute(0xc00014fc50, 0xc0005700a0, 0xc0000e0701, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:356 +0xa5
github.com/rqlite/rqlite/store.(*Store).Apply(0xc000086c00, 0xc00006cae0, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/store/store.go:940 +0x3c7
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0000300a0)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:90 +0x2c6
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc000132600, 0x3f, 0x40)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:113 +0x78
github.com/hashicorp/raft.(*Raft).runFSM(0xc00013ef00)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:216 +0x392
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc00013ef00, 0xc000154eb0)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:144 +0x66

```

**What did you expect to happen?**
I expected it to continue to run or at least try again to find the log from its leader.

**What happened instead?**
when the rqlite instance did not found the log it crashed

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
** Leader has changed since the logs where generated** 
Leader:
rqlite-2.rqlite:4001> .status
cluster:
  addr: 10.244.1.22:4002
  api_addr: rqlite-2.rqlite:4001
  https: false
  timeout: 10s
http:
  addr: 10.244.1.22:4001
  auth: disabled
node:
  start_time: 2021-05-21T11:45:35.824776121Z
  uptime: 2h6m5.724579141s
runtime:
  GOMAXPROCS: 2
  GOOS: linux
  num_cpu: 2
  num_goroutine: 42
  version: go1.16.2
  GOARCH: amd64
store:
  addr: 10.244.1.22:4002
  dir: /node
  dir_size: 6.1370014e+07
  node_id: rqlite-2
  raft:
    protocol_version_min: 0
    fsm_pending: 0
    last_contact: 0
    last_log_term: 3
    latest_configuration: [{Suffrage:Voter ID:rqlite-2 Address:10.244.1.22:4002} {Suffrage:Voter ID:rqlite-3 Address:10.244.3.72:4002} {Suffrage:Voter ID:rqlite-4 Address:10.244.6.178:4002} {Suffrage:Voter ID:rqlite-0 Address:10.244.5.70:4002} {Suffrage:Voter ID:rqlite-1 Address:10.244.9.115:4002}]
    term: 3
    commit_index: 47715
    snapshot_version_max: 1
    snapshot_version_min: 0
    state: Leader
    protocol_version_max: 3
    last_log_index: 47715
    latest_configuration_index: 0
    log_size: 2.5202688e+07
    protocol_version: 3
    applied_index: 47715
    last_snapshot_index: 46597
    last_snapshot_term: 3
    num_peers: 4
  snapshot_interval: 3e+10
  apply_timeout: 10s
  db_conf:
    DSN: 
    Memory: true
  trailing_logs: 5120
  election_timeout: 5s
  heartbeat_timeout: 4s
  request_marshaler:
    compression_batch: 5
    compression_size: 150
    force_compression: false
  snapshot_threshold: 4096
  sqlite3:
    version: 3.35.4
    db_size: 7.6378112e+07
    dsn: 
    fk_constraints: disabled
    path: :memory:
  leader:
    addr: 10.244.1.22:4002
    node_id: rqlite-2
  nodes: [map[addr:10.244.5.70:4002 id:rqlite-0 suffrage:Voter] map[addr:10.244.9.115:4002 id:rqlite-1 suffrage:Voter] map[addr:10.244.1.22:4002 id:rqlite-2 suffrage:Voter] map[addr:10.244.3.72:4002 id:rqlite-3 suffrage:Voter] map[addr:10.244.6.178:4002 id:rqlite-4 suffrage:Voter]]
build:
  version: 6
  branch: unknown
  build_time: unknown
  commit: unknown

rqlite-2.rqlite:4001> .nodes
rqlite-4:
  api_addr: http://rqlite-4.rqlite:4001
  addr: 10.244.6.178:4002
  reachable: true
  leader: false
rqlite-0:
  api_addr: http://rqlite-0.rqlite:4001
  addr: 10.244.5.70:4002
  reachable: true
  leader: false
rqlite-1:
  api_addr: http://rqlite-1.rqlite:4001
  addr: 10.244.9.115:4002
  reachable: true
  leader: false
rqlite-2:
  api_addr: http://rqlite-2.rqlite:4001
  addr: 10.244.1.22:4002
  reachable: true
  leader: true
rqlite-3:
  reachable: true
  leader: false
  api_addr: http://rqlite-3.rqlite:4001
  addr: 10.244.3.72:4002

rqlite-2.rqlite:4001> .expvar
http:
  backups: 0
  executions: 48064
  joins: 4
  loads: 0
  queries: 29043
  authFail: 0
  authOK: 144865
memstats:
  BuckHashSys: 1.838083e+06
  Alloc: 8.268176e+06
  HeapIdle: 2.56786432e+08
  MSpanSys: 393216
  Lookups: 0
  NextGC: 9.577472e+06
  HeapInuse: 1.0698752e+07
  OtherSys: 661597
  LastGC: 1.6216051570171246e+18
  StackInuse: 950272
  MCacheInuse: 2400
  PauseNs: [40900 67800 52700 39800 81901 42000 100800 104600 66600 99600 263001 71500 49400 1.080303e+06 64900 166201 135700 43200 54800 148900 39700 41500 45900 46900 39600 42600 77900 483701 45400 53700 33900 40500 41200 81200 53400 51800 57800 118000 5.079715e+06 43200 64800 42400 41200 213100 48200 119900 74100 35500 477401 200301 57800 36600 31200 62802 34500 52400 493901 63900 1.466304e+06 7.2468317e+07 163602 470501 55100 56800 36900 80800 92501 36601 36000 83000 1.491205e+06 110000 57000 236301 31401 37900 58000 40701 74900 35400 84400 49700 86501 35701 136800 45300 95100 425101 117901 43301 41700 38800 70300 37800 36600 141201 109101 65001 34200 77700 36800 49900 3.652511e+06 27900 39800 79600 38300 143000 75301 36500 46700 114901 38300 49601 36700 55400 67302 38601 195000 38600 25601 5.424916e+06 38900 38300 97700 95700 112300 57800 36800 87900 159900 140300 48401 35900 34500 37600 71400 1.660404e+06 39900 37500 37200 120500 43900 48000 45800 47100 90000 44501 37100 86000 48400 50900 34900 57101 64100 38800 47501 36100 73201 88800 143601 65200 43801 74600 99100 30500 22800 24200 259701 37101 55000 101000 83900 38000 40500 53500 137101 43801 97601 48601 596301 79601 38900 26600 68700 55901 50000 38800 131800 33900 36800 47200 97400 22600 55900 60300 48400 303101 275900 78200 40700 54501 53400 61300 494201 48602 40300 236001 40100 73701 53500 62200 84601 88600 66700 91000 35700 65700 44400 51100 3.31681e+06 36700 234501 127401 54900 49200 137901 168500 73700 111600 41701 42100 40800 51600 109500 41000 54300 37300 114500 36100 99400 40400 63900 73300 89700 159501 116300 41401 160100 43700 75800 109400 85000 24200 131301 49200]
  BySize: [map[Frees:0 Mallocs:0 Size:0] map[Frees:1.525967e+06 Mallocs:1.526707e+06 Size:8] map[Frees:1.44077705e+08 Mallocs:1.44080914e+08 Size:16] map[Frees:6.048522e+06 Mallocs:6.049046e+06 Size:24] map[Frees:6.044328e+06 Mallocs:6.044795e+06 Size:32] map[Frees:1.2185712e+07 Mallocs:1.2195408e+07 Size:48] map[Frees:1.0511298e+07 Mallocs:1.0511872e+07 Size:64] map[Frees:6.455249e+06 Mallocs:6.455743e+06 Size:80] map[Frees:5.688033e+06 Mallocs:5.689386e+06 Size:96] map[Frees:1.317999e+06 Mallocs:1.31814e+06 Size:112] map[Frees:7.616337e+06 Mallocs:7.616547e+06 Size:128] map[Frees:1.18698e+06 Mallocs:1.18706e+06 Size:144] map[Frees:804617 Mallocs:804695 Size:160] map[Frees:1.17735e+06 Mallocs:1.177932e+06 Size:176] map[Frees:642697 Mallocs:642861 Size:192] map[Frees:1.001677e+06 Mallocs:1.001771e+06 Size:208] map[Frees:580078 Mallocs:580103 Size:224] map[Frees:378098 Mallocs:378111 Size:240] map[Frees:667206 Mallocs:667372 Size:256] map[Frees:1.14469e+06 Mallocs:1.144766e+06 Size:288] map[Frees:389897 Mallocs:389930 Size:320] map[Frees:825256 Mallocs:825347 Size:352] map[Frees:356492 Mallocs:356731 Size:384] map[Frees:721652 Mallocs:721754 Size:416] map[Frees:62031 Mallocs:62039 Size:448] map[Frees:146159 Mallocs:146173 Size:480] map[Frees:794414 Mallocs:794487 Size:512] map[Frees:218376 Mallocs:218409 Size:576] map[Frees:71783 Mallocs:71806 Size:640] map[Frees:103536 Mallocs:103566 Size:704] map[Frees:74174 Mallocs:74211 Size:768] map[Frees:31049 Mallocs:31153 Size:896] map[Frees:129771 Mallocs:129831 Size:1024] map[Frees:285420 Mallocs:285495 Size:1152] map[Frees:74536 Mallocs:74589 Size:1280] map[Frees:8591 Mallocs:8618 Size:1408] map[Frees:14163 Mallocs:14172 Size:1536] map[Frees:73415 Mallocs:73436 Size:1792] map[Frees:74257 Mallocs:74277 Size:2048] map[Frees:252059 Mallocs:252089 Size:2304] map[Frees:74241 Mallocs:74256 Size:2688] map[Frees:80953 Mallocs:80960 Size:3072] map[Frees:2671 Mallocs:2672 Size:3200] map[Frees:5523 Mallocs:5527 Size:3456] map[Frees:158200 Mallocs:158273 Size:4096] map[Frees:85619 Mallocs:85626 Size:4864] map[Frees:34238 Mallocs:34244 Size:5376] map[Frees:16897 Mallocs:16899 Size:6144] map[Frees:4796 Mallocs:4796 Size:6528] map[Frees:29080 Mallocs:29083 Size:6784] map[Frees:1390 Mallocs:1390 Size:6912] map[Frees:224367 Mallocs:224387 Size:8192] map[Frees:40206 Mallocs:40212 Size:9472] map[Frees:3550 Mallocs:3555 Size:9728] map[Frees:7986 Mallocs:7992 Size:10240] map[Frees:8315 Mallocs:8315 Size:10880] map[Frees:35906 Mallocs:35910 Size:12288] map[Frees:6229 Mallocs:6232 Size:13568] map[Frees:3284 Mallocs:3284 Size:14336] map[Frees:18639 Mallocs:18641 Size:16384] map[Frees:3848 Mallocs:3848 Size:18432]]
  Sys: 2.84059704e+08
  Mallocs: 3.02942747e+08
  Frees: 3.02922791e+08
  EnableGC: true
  DebugGC: false
  HeapSys: 2.67485184e+08
  MSpanInuse: 96016
  GCSys: 1.2714968e+07
  GCCPUFraction: 0.004217300031298801
  HeapReleased: 2.5628672e+08
  PauseEnd: [1.6216051241271598e+18 1.621605124229934e+18 1.6216051248865167e+18 1.621605125118513e+18 1.6216051256335388e+18 1.6216051261548134e+18 1.621605126578842e+18 1.621605127005306e+18 1.6216051277844772e+18 1.6216051281836416e+18 1.621605128449275e+18 1.6216051290270057e+18 1.621605129432157e+18 1.6216051301530345e+18 1.6216051306940472e+18 1.6216051310471142e+18 1.6216051311465405e+18 1.6216051316208259e+18 1.6216051321454725e+18 1.6216051330077873e+18 1.6216051334467512e+18 1.6216051340268547e+18 1.6216051341379658e+18 1.621605135017018e+18 1.6216051354941245e+18 1.6216051362985265e+18 1.6216051367943414e+18 1.621605137111043e+18 1.621605137437753e+18 1.621605138142503e+18 1.6216051386109501e+18 1.621605139024568e+18 1.6216051397088479e+18 1.6216051401423803e+18 1.621605141032504e+18 1.6216051411527475e+18 1.6216051420412716e+18 1.621605142143455e+18 1.6216051431179374e+18 1.6216051434462984e+18 1.6216051437378076e+18 1.6216051443773202e+18 1.6216051449126728e+18 1.6216051451569027e+18 1.621605145533344e+18 1.6216051457873426e+18 1.621605146150802e+18 1.6216051468522079e+18 1.6216051471636442e+18 1.6216051481404664e+18 1.6216051486310612e+18 1.6216051490942162e+18 1.6216051491787103e+18 1.6216051491883218e+18 1.6216051497499704e+18 1.6216051503810202e+18 1.6216051510170593e+18 1.6216051511730092e+18 1.6216051516870387e+18 1.6216051519841746e+18 1.621605152143925e+18 1.6216051530157778e+18 1.6216051537322412e+18 1.6216051541198415e+18 1.621605154226488e+18 1.6216051545425695e+18 1.6216051550889024e+18 1.621605155124783e+18 1.6216051551820132e+18 1.6216051561461699e+18 1.6216051565043794e+18 1.6216051570171246e+18 1.6216050543856015e+18 1.6216050549360256e+18 1.6216050549717304e+18 1.6216050551365642e+18 1.6216050560448645e+18 1.6216050560572086e+18 1.621605056137222e+18 1.6216050566224468e+18 1.6216050569859272e+18 1.621605057122075e+18 1.6216050573504061e+18 1.62160505760905e+18 1.6216050578437796e+18 1.6216050584827407e+18 1.6216050589852547e+18 1.6216050591122798e+18 1.621605059129273e+18 1.6216050591489265e+18 1.6216050601168346e+18 1.6216050603755635e+18 1.6216050609938348e+18 1.6216050611251935e+18 1.6216050615500803e+18 1.6216050621175828e+18 1.6216050625747077e+18 1.62160506300027e+18 1.621605063167871e+18 1.621605063621009e+18 1.6216050641131873e+18 1.6216050644890578e+18 1.6216050649977106e+18 1.62160506501867e+18 1.621605065078814e+18 1.6216050651242276e+18 1.6216050655361068e+18 1.6216050661153562e+18 1.6216050664865495e+18 1.6216050669887647e+18 1.6216050671442296e+18 1.6216050676929495e+18 1.6216050677868442e+18 1.6216050681417546e+18 1.621605068998401e+18 1.6216050691270397e+18 1.6216050696441032e+18 1.6216050701730107e+18 1.6216050709835277e+18 1.6216050711159882e+18 1.6216050711318838e+18 1.621605071470628e+18 1.6216050723755743e+18 1.6216050729782894e+18 1.6216050731419359e+18 1.6216050735878356e+18 1.6216050739845637e+18 1.6216050741152579e+18 1.621605074921797e+18 1.621605075127046e+18 1.621605076116346e+18 1.6216050768907853e+18 1.621605077008401e+18 1.6216050771303826e+18 1.6216050778421852e+18 1.6216050783538437e+18 1.6216050789815864e+18 1.6216050795290842e+18 1.6216050796877676e+18 1.6216050801200033e+18 1.621605080984401e+18 1.6216050811312655e+18 1.6216050811454884e+18 1.6216050819297923e+18 1.6216050821176497e+18 1.6216050829865047e+18 1.6216050830220846e+18 1.6216050831307743e+18 1.6216050836904824e+18 1.6216050841245128e+18 1.6216050844785615e+18 1.621605084804617e+18 1.6216050849811405e+18 1.6216050855394998e+18 1.6216050859122304e+18 1.6216050861248108e+18 1.6216050867212078e+18 1.6216050869871043e+18 1.621605087151915e+18 1.6216050880380572e+18 1.621605088118441e+18 1.6216050884380716e+18 1.6216050887800835e+18 1.6216050889834063e+18 1.621605089009753e+18 1.6216050890818819e+18 1.6216050890859704e+18 1.6216050891782446e+18 1.621605089200345e+18 1.6216050893959114e+18 1.621605089406227e+18 1.6216050894146156e+18 1.621605089585971e+18 1.6216050896524764e+18 1.6216050901491832e+18 1.6216050904040038e+18 1.621605090992472e+18 1.621605091135e+18 1.6216050914968328e+18 1.6216050916848873e+18 1.621605091778666e+18 1.6216050917898245e+18 1.6216050920826778e+18 1.6216050921083256e+18 1.6216050921183158e+18 1.6216050921893806e+18 1.6216050925025482e+18 1.6216050929875886e+18 1.6216050931104842e+18 1.6216050931347697e+18 1.621605093602165e+18 1.6216050941205376e+18 1.6216050945182195e+18 1.621605094521303e+18 1.6216050945902182e+18 1.6216050946806218e+18 1.621605094986069e+18 1.6216050950005693e+18 1.6216050950968266e+18 1.6216050953828946e+18 1.6216050961259807e+18 1.621605096143609e+18 1.6216050964106788e+18 1.621605096492644e+18 1.6216050969898793e+18 1.6216050975483333e+18 1.621605098123353e+18 1.621605098721867e+18 1.621605099137332e+18 1.62160509918955e+18 1.6216051002341048e+18 1.6216051009829394e+18 1.6216051011075075e+18 1.6216051018374758e+18 1.6216051021231798e+18 1.6216051029931528e+18 1.62160510314767e+18 1.6216051036912105e+18 1.621605104200502e+18 1.6216051045350193e+18 1.6216051050011292e+18 1.621605105498079e+18 1.6216051061241124e+18 1.6216051070088602e+18 1.621605107106884e+18 1.6216051079056696e+18 1.6216051082980603e+18 1.6216051090007508e+18 1.6216051093358313e+18 1.6216051101259784e+18 1.6216051101782413e+18 1.621605110410492e+18 1.6216051111395395e+18 1.621605111401575e+18 1.6216051121340477e+18 1.6216051130148242e+18 1.621605113147327e+18 1.6216051136490496e+18 1.6216051141297103e+18 1.6216051147416056e+18 1.6216051151414694e+18 1.6216051161319398e+18 1.6216051167281984e+18 1.6216051171605783e+18 1.621605118132633e+18 1.6216051186339128e+18 1.6216051190241623e+18 1.621605119224866e+18 1.6216051201381507e+18 1.6216051210028078e+18 1.6216051211471196e+18 1.6216051220091295e+18 1.621605122146528e+18 1.621605122178629e+18 1.6216051230277614e+18 1.621605123485308e+18]
  NumForcedGC: 0
  StackSys: 950272
  NumGC: 22088
  TotalAlloc: 6.2854894232e+10
  HeapAlloc: 8.268176e+06
  HeapObjects: 19956
  MCacheSys: 16384
  PauseTotalNs: 9.024215708e+09
mux:
  num_connections_handled: 77128
  num_unregistered_handlers: 0
proto:
  num_compression_misses: 0
  num_precompressed_bytes: 2.33476505e+08
  num_requests: 0
  num_uncompressed_bytes: 260659
  num_uncompressed_requests: 2268
  num_compressed_bytes: 3.7611028e+07
  num_compressed_requests: 45796
store:
  num_restores: 0
  num_snapshots: 11
  num_uncompressed_commands: 2268
  num_backups: 0
  num_compressed_commands: 45796
cluster:
  num_get_node_api_req: 77128
  num_get_node_api_resp: 77128
  num_get_node_api: 77975
cmdline: [/rqlited -node-id rqlite-2 -raft-snap 4096 -raft-timeout 4s -raft-election-timeout 5s -http-addr rqlite-2.rqlite:4001 -raft-addr rqlite-2.rqlite:4002 /node]
db:
  execute_transactions: 0
  execution_errors: 205
  executions: 364909
  queries: 80852
  query_transactions: 0

See https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by otoolep** [comment]
Thanks for the report, this is a new one to me. I'll look into it, and let me know if it happens again -- and if there is anything special about this node.

**Comment by otoolep** [comment]
I'm definitely interested in debugging this further, anything special about this node? Anything you're doing with the file system underneath it?

**Comment by Dorsosiv** [comment]
nothing special,  it is running on AKS (azure) kubernetes cluster. So I cannot dive too deep about the machine where it runs.
It is running on memory.

**Comment by Dorsosiv** [comment]
I can send the .status and .expvar output of that instance, just in case they will have vital info about it..

**Comment by Dorsosiv** [comment]
Hey, @otoolep  how are you ? 

I got this error again. : 

```
2021-06-23T19:27:12.968Z [WARN]  raft: failed to get previous log: previous-index=90 last-index=0 error="log not found"
[mux] 2021/06/23 19:27:12 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[mux] 2021/06/23 19:27:13 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[mux] 2021/06/23 19:27:13 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[mux] 2021/06/23 19:27:13 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[mux] 2021/06/23 19:27:13 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[store] 2021/06/23 19:27:13 waiting for up to 2m0s for application of initial logs
[mux] 2021/06/23 19:27:13 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[mux] 2021/06/23 19:27:13 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[mux] 2021/06/23 19:27:13 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[cluster] 2021/06/23 19:27:13 service listening on 10.244.65.186:4002
[http] 2021/06/23 19:27:13 service listening on 10.244.65.186:4001
[rqlited] 2021/06/23 19:27:13 node is ready
2021-06-23T19:27:41.963Z [ERROR] raft-net: failed to flush response: error="write tcp 10.244.65.186:4002->10.244.193.225:36536: write: broken pipe"
panic: interface conversion: driver.Stmt is nil, not *sqlite3.SQLiteStmt
goroutine 24 [running]:
github.com/rqlite/go-sqlite3.(*SQLiteConn).exec(0xc0003007e0, 0xd6f5f0, 0xc00002c0a8, 0xc00078e000, 0x450b, 0x11628f8, 0x0, 0x0, 0xc001d57960, 0x47781b, ...)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:803 +0x78e
github.com/rqlite/go-sqlite3.(*SQLiteConn).Exec(0xc0003007e0, 0xc00078e000, 0x450b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:792 +0x138
github.com/rqlite/rqlite/db.(*DB).Execute.func1(0xc001d57af0, 0xc9a400, 0xc0003031d0, 0xc0002bcb40, 0x1401, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:321 +0x2b4
github.com/rqlite/rqlite/db.(*DB).Execute(0xc0003031d0, 0xc0002bcb40, 0xc001422e01, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:356 +0xa5
github.com/rqlite/rqlite/store.(*Store).Apply(0xc00037a480, 0xc0014f0de0, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/store/store.go:940 +0x3c7
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc000a97ba0)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:90 +0x2c6
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc0002d4c00, 0x4, 0x40)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:113 +0x78
github.com/hashicorp/raft.(*Raft).runFSM(0xc0003ae000)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:216 +0x392
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0003ae000, 0xc000304c00)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:144 +0x66
```

**Comment by otoolep** [comment]
Hmmm, this is definitely confusing. Do you have the log from the very start of the node coming up? That is not shown above.

If it happens again, can you provide me the whole log, right from the start?

**Comment by otoolep** [comment]
Also, can you be sure you run the official 6.0 release? I know you used to build your own 6.0 but you should run the official release if you can. Otherwise be sure to build HEAD.

**Comment by Dorsosiv** [comment]
ok Ill check that

**Comment by Dorsosiv** [comment]
@otoolep  and the logs that you requested are the same as I gave in the description. nothing to special about them. Suddenly the rqlite crashes

**Comment by otoolep** [comment]
OK, thanks. How often is this happening for you?

**Comment by otoolep** [comment]
Every couple of days? Once a week?

**Comment by otoolep** [comment]
The log from above is older code, I've added more logging in 6.0.1. Can you run the latest version, and send me the logs? Download latest version (or build HEAD on master).

https://github.com/rqlite/rqlite/releases/tag/v6.0.1

**Comment by Dorsosiv** [comment]
it happens spontaneously (perhaps not ... :thinking: ) could it be because the "storage " on the memory ended that the sqlite will have a panic ?

Ill update the rqlite we have and Ill update you if it happens again

**Comment by otoolep** [comment]
OK, please let me know what you see. I'm keen to understand this issue, and hopefully fix it.

**Comment by otoolep** [comment]
Also, please be sure that *every* node is running the same version of software. Please run the same version on every node. If this happens again, I'll next provide a special debug version to you which can log even more information about the error.

Something is getting pushed down into the SQLite layer that it doesn't like, but I can't see what it is right now.

**Comment by Dorsosiv** [comment]
Ok Ill let you know

**Comment by otoolep** [comment]
Pretty sure this is the same as https://github.com/rqlite/rqlite/issues/830
