### ISSUE TITLE
How to create SQLite database file on each disk of a 3 nodes cluster?

### ISSUE THREAD

**Issue by moving-digital** [rqlite/rqlite#817]
Hello @otoolep 

I was reading the following [DESIGN.md](https://github.com/rqlite/rqlite/blob/master/DOC/DESIGN.md) because I would like my RQLite database consisting of a cluster of 3 nodes, to be permanent in case of reboot of the 3 servers at the same time.

I've read that "_By default the SQLite layer doesn't create a file. Instead it creates the database in RAM. rqlite can create the SQLite database on disk, if so configured at start-time._"

Would you know how to configure the SQLite database on disk, knowing that I'm dealing with 3 nodes in the cluster?

Thanks

**Comment by otoolep** [comment]
Pass `-on-disk` to rqlited on startup to use an on-disk SQLite file. However the SQLite file is recreated on startup every time, just so you know (though it will happen very quickly). See:

https://github.com/rqlite/rqlite/blob/master/README.md#in-memory-databases
