### ISSUE TITLE
rqlited Raft log control option doesn't control Snapshot logging

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#820]
**Is your feature request related to a problem? Please describe.**
I would like to decrease the amount of logs created by rqlite 

I would like the log-level to show logs that are more critical that the level I selected as a client.

for example, if I set the log-level to warning, then Ill see in the logs the warning and errors and fatals that the rqlite will have

**Describe the solution you'd like**
having an option for log level 

**Describe alternatives you've considered**
there is no alternative

**Comment by otoolep** [comment]
In my experience the Raft code generates the most logs. Are you aware of the `-raft-log-level` option? 

E.g.

`./rqlited -raft-log-level=ERROR data`

Is that sufficient?

**Comment by Dorsosiv** [comment]
@otoolep thanks for the answer, Ill check if it helped and notify you

**Comment by Dorsosiv** [comment]
looks like it helped. Thanks

**Comment by Dorsosiv** [comment]
Hi, I saw this weird behavior : 

notice that in the second line in the launch command the raft-log-level is ERROR and we still get INFO from the rqlited.



```
[rqlited] 2021/07/06 21:31:27 launch command: /rqlited -node-id rqlite-0 -raft-snap 12288 -raft-timeout 6s -raft-election-timeout 8s -join-attempts 5 -http-addr rqlite-0.rqlite:4001 -raft-addr rqlite-0.rqlite:4002 -raft-log-level ERROR -join http://rqlite-4.rqlite:4001 /node
[mux] 2021/07/06 21:31:27 received handler registration request for header 1
[mux] 2021/07/06 21:31:27 received handler registration request for header 2
[cluster] 2021/07/06 21:31:27 service listening on 10.254.11.183:4002
[mux] 2021/07/06 21:31:27 mux serving on 10.254.11.183:4002, advertising 10.254.11.183:4002
[rqlited] 2021/07/06 21:31:27 no preexisting node state detected in /node, node may be bootstrapping
[rqlited] 2021/07/06 21:31:27 join addresses specified, node is not bootstrapping
[store] 2021/07/06 21:31:27 opening store with node ID rqlite-0
[store] 2021/07/06 21:31:27 ensuring directory at /node exists
[store] 2021/07/06 21:31:27 0 preexisting snapshots present
[store] 2021/07/06 21:31:27 first log index: 0, last log index: 0, last command log index: 0:
[store] 2021/07/06 21:31:27 no cluster bootstrap requested
[rqlited] 2021/07/06 21:31:27 join addresses are: [http://rqlite-4.rqlite:4001]
[rqlited] 2021/07/06 21:31:27 successfully joined cluster at http://rqlite-4.rqlite:4001/join
[store] 2021/07/06 21:31:27 waiting for up to 2m0s for application of initial logs
[rqlited] 2021/07/06 21:31:27 store has reached consensus
[http] 2021/07/06 21:31:27 service listening on 10.254.11.183:4001
[rqlited] 2021/07/06 21:31:27 node is ready
[store] 2021/07/06 22:13:12 node snapshot created in 25.916232ms
2021-07-06T22:13:12.884Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/4-12450-1625609592884.tmp
[store] 2021/07/06 22:13:13 snapshot and persist took 946.333003ms
[store] 2021/07/06 23:03:58 node snapshot created in 21.477105ms
2021-07-06T23:03:58.242Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/4-24870-1625612638242.tmp
[store] 2021/07/06 23:04:00 snapshot and persist took 2.299629481s
[store] 2021/07/06 23:54:22 node snapshot created in 38.994128ms

```

**Comment by otoolep** [comment]
Hmmm, that doesn't look right -- I'll take a look.

**Comment by otoolep** [comment]
I see the issue, I'll have to think about how to best address it. Basically the setting doesn't apply to the logger used for Snapshot logging. In practice this will result in a small amount of logging every time a snapshot is taken. This shouldn't be an issue in practice, I assume, since snapshotting doesn't happen very often in a normal deployment.

**Comment by Dorsosiv** [comment]
Besides the snapshot logs other logs are being stopped , right ? 

If so than it is fine for now. Thanks :)

**Comment by otoolep** [comment]
Yes, as far as I can see -- it's just that log now. Your report is correct, but I think it's of limited impact. I will think about this issue though, and leave it open for now.

**Comment by otoolep** [comment]
Renamed to better describe remaining issue.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/pull/1610 will help a lot.
