### ISSUE TITLE
we are getting an error and I did not found what is its source in the rqlite code

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#821]
**What version are you running?**
release 6.0 rqlite version

**What did you do?**
run containers with rqlite-go client. I got the error : 
"could not split host: missing port in address"

**What did you expect to happen?**
I expected to find it in the rqlite-go client code

**Comment by otoolep** [comment]
I guess it's coming from here: https://golang.org/src/net/ipsock.go?s=4766:4832#L158

Can you include a port when passing an address to the client library? Otherwise we will need to modify the client library.

**Comment by otoolep** [comment]
I'm assuming this is a configuration issue, and you're not passing the full address to the client -- you must pass both the IP address and port in the form addr:port. If you don't, you'll get this error.

If you're still seeing this error, even when using the correct format, please re-open the bug.

**Comment by Dorsosiv** [comment]
the thing is we do pass the full host and port. it might be a specific case which might have caused the code to not find a port ... :thinking: 

Any way, this error has not returned in a while so thank you :)
