### ISSUE TITLE
Add experimental support golang native sqlite driver

### ISSUE THREAD

**Issue by zhangyongding** [rqlite/rqlite#828]
**Is your feature request related to a problem? Please describe.**
The current driver has CGO bindings, so dynamic dependencies appear during cross-compilation

**Describe the solution you'd like**
Do not rely on the CGO  

**Describe alternatives you've considered**

**Additional context**
https://pkg.go.dev/modernc.org/sqlite

**Comment by otoolep** [comment]
I did consider it, but want the real SQLite engine.
