### ISSUE TITLE
rqlite: query with command line is broken 

### ISSUE THREAD

**Issue by elv-gilles** [rqlite/rqlite#854]
**What version are you running?**
latest master at `a71bcd3` 

**What did you do?**
follow the basic steps in [cmd/README.md](https://github.com/rqlite/rqlite/tree/master/cmd/rqlite)
Step `SELECT * FROM foo` does not report anything

**What did you expect to happen?**
cli to report all records from table

**What happened instead?**
nothing

The problem comes from commit [e1e2398](https://github.com/rqlite/rqlite/commit/e1e239888a8c43b6a5cfc9acfed6462c51040a23) - that is missing a `fallthrough`.
see: https://github.com/rqlite/rqlite/blob/master/cmd/rqlite/main.go#L159-L162

It should be:

```
			case "SELECT":
				fallthrough
			case "PRAGMA":
				err = queryWithClient(ctx, client, argv, timer, line)
```

**Comment by otoolep** [comment]
Thank you, you are right.
