### ISSUE TITLE
Get cluster status via API?

### ISSUE THREAD

**Issue by adamklaff** [rqlite/rqlite#875]
I would like to be able for my application to know whether it’s the leader of a cluster or not so it can decide whether to send data to an external service as part of a regular job.

**Describe the solution you'd like**
I’d like to be able to retrieve this via an API endpoint and/or via client libraries

**Comment by otoolep** [comment]
Have you examined the output of the `status/` endpoint?

https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by adamklaff** [comment]
Somehow I missed this. This should work great. Thanks!
