### ISSUE TITLE
HTTP Range Query VFS

### ISSUE THREAD

**Issue by chadbrewbaker** [rqlite/rqlite#906]
Sorry, I browsing the source I may have missed it.

Is there a config to use HTTP range queries on AWS S3 buckets like https://github.com/dacort/athena-sqlite/blob/eff71802b31c4fc0eb708e7c9930dc94d7533222/lambda-function/vfs.py#L24 ?

**Comment by otoolep** [comment]
I do not understand your question. Did you post on the wrong repo?
