### ISSUE TITLE
rqlited: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by rqlited)

### ISSUE THREAD

**Issue by NikitaDef** [rqlite/rqlite#910]
**What version are you running?**
rqlite/rqlite:6.6.2 and rqlite/rqlite:6.6.1

**What did you do?**
docker pull rqlite/rqlite:6.6.2
docker run rqlite/rqlite:6.6.2

and same
docker pull rqlite/rqlite:6.6.1
docker run rqlite/rqlite:6.6.1

**What did you expect to happen?**
Run rqlite and see logs on console 
**What happened instead?**
Rqlite crashes
**rqlited: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by rqlited)**

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**
Don't see
See https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md
yes

But vesion of rqlite/rqlite:6.6.0 works without any promblem

**Comment by otoolep** [comment]
Can you try again? I just made this change:

https://github.com/rqlite/rqlite-docker/commit/f9b675189f871666e91d4a063262db575d36cabc

and regenerated the 6.6.2 Docker images.

**Comment by NikitaDef** [comment]
> Can you try again? I just made this change:
> 
> [rqlite/rqlite-docker@f9b6751](https://github.com/rqlite/rqlite-docker/commit/f9b675189f871666e91d4a063262db575d36cabc)
> 
> and regenerated the 6.6.2 Docker images.

I did
```
docker pull rqlite/rqlite:6.6.2
docker run rqlite/rqlite:6.6.2
```
rqlite works after your change.
Thank you
