### ISSUE TITLE
single node mode restart failed

### ISSUE THREAD

**Issue by tiswong** [rqlite/rqlite#928]
**What version are you running?**
6.3.0
**What did you do?**
I use the single node mode to start rqlite. The data mode is `on-disk`. After writing about 10 million lines of data, the restart cannot succeed. After restart, i found through the log that the data mode has changed to `In-memory`, and an error will be returned  `error="createInMemory: database or disk is full"`, because the value of `s.lastCommandIdxOnOpen` is not 0;
```go
if !s.dbConf.Memory && !s.snapsExistOnOpen && s.lastCommandIdxOnOpen == 0 {
		s.db, err = s.createOnDisk(nil)
		if err != nil {
			return fmt.Errorf("failed to create on-disk database")
		}
		s.onDiskCreated = true
		s.logger.Printf("created on-disk database at open")
	} else {
		// We need an in-memory database, at least for bootstrapping purposes.
		s.db, err = s.createInMemory(nil)
		if err != nil {
			return fmt.Errorf("failed to create in-memory database")
		}
		s.logger.Printf("created in-memory database at open")
	}
```
**What did you expect to happen?**

**What happened instead?**

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**

See https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by otoolep** [comment]
Thanks for your report. I think I know what is going on.

To speed up restart of nodes that use `-on-disk` rqlite first restores the SQLite database to RAM, then it copies it to the disk. I guess this could fail if the SQLite database exceeds the memory limits (as you and I worked on before). 

I could add a flag to `rqlited`, so that it never performs this optimization. However it could mean slow restarts, but if youre using a memory-based disk it might be fine. Are you using a memory-based disk? Do you want such a flag?

**Comment by otoolep** [comment]
This is where it would have switched to on-disk, if it made it that far:

https://github.com/rqlite/rqlite/blob/003301aee677788838adc5f7342d50c8540f6d1c/store/store.go#L987

**Comment by tiswong** [comment]
> This is where it would have switched to on-disk, if it made it that far:
> 
> https://github.com/rqlite/rqlite/blob/003301aee677788838adc5f7342d50c8540f6d1c/store/store.go#L987

Yes, I noticed the code in the new version, but when the data is large, the code can't be executed here

**Comment by tiswong** [comment]
> Thanks for your report. I think I know what is going on.
> 
> To speed up restart of nodes that use `-on-disk` rqlite first restores the SQLite database to RAM, then it copies it to the disk. I guess this could fail if the SQLite database exceeds the memory limits (as you and I worked on before).
> 
> I could add a flag to `rqlited`, so that it never performs this optimization. However it could mean slow restarts, but if youre using a memory-based disk it might be fine. Are you using a memory-based disk? Do you want such a flag?

I use a real disk because the test data stored may actually exceed 2GB or more

**Comment by otoolep** [comment]
@tiswong -- are you able to build a branch? I've got a PR open that will allow you disable the in-memory initialization of on-disk databases. I'd like to know if it'd worked for you before developing further. To disable it pass `-on-disk-startup ` to `rqlited`.

I'd like to know if your system starts when passed this flag.

**Comment by otoolep** [comment]
>I use a real disk because the test data stored may actually exceed 2GB or more

Is your disk actually on a disk, or is it on a RAM disk?

https://github.com/rqlite/rqlite/blob/master/DOC/PERFORMANCE.md#in-memory-database-limits

**Comment by tiswong** [comment]
> > I use a real disk because the test data stored may actually exceed 2GB or more
> 
> Is your disk actually on a physical disk, or is it on a RAM disk?
> 
> https://github.com/rqlite/rqlite/blob/master/DOC/PERFORMANCE.md#in-memory-database-limits
on physical disk

**Comment by tiswong** [comment]
> > Thanks for your report. I think I know what is going on.
> > To speed up restart of nodes that use `-on-disk` rqlite first restores the SQLite database to RAM, then it copies it to the disk. I guess this could fail if the SQLite database exceeds the memory limits (as you and I worked on before).
> > I could add a flag to `rqlited`, so that it never performs this optimization. However it could mean slow restarts, but if youre using a memory-based disk it might be fine. Are you using a memory-based disk? Do you want such a flag?
> 
> I use a real disk because the test data stored may actually exceed 2GB or more

ok, thank you , i'll test this flag and feed back the results to you.

**Comment by tiswong** [comment]
> @tiswong -- are you able to build a branch? I've got a PR open that will allow you disable the in-memory initialization of on-disk databases. I'd like to know if it'd worked for you before developing further. To disable it pass `-on-disk-startup ` to `rqlited`.
> 
> I'd like to know if your system starts when passed this flag.

ok, thank you , i'll test this flag and feed back the results to you.

**Comment by tiswong** [comment]
hi, I tested this PR and it started successfully. I have another question. I use a physical disk. Why does the memory still occupy 3.8GB after startup. Through pprof analysis, it is found that `runtime.malg` occupies a lot of memory

**Comment by tiswong** [comment]
> @otoolep hi, I tested this PR and it started successfully. I have another question. I use a physical disk. Why does the memory still occupy 3.8GB after startup. After about half an hour, the memory recovered to 160MB

**Comment by otoolep** [comment]
>I tested this PR and it started successfully. 

OK, great. I'll test this implementation some more and then make it part of an upcoming release.

>on physical disk

I just want to make sure you're aware that if you can make a RAM-based disk, place the SQLite file on that disk, but leave that Raft log on a physical disk, you'll get much better performance but still be able to create SQLite databases larger than 2GB. That's what the doc below is about:

https://github.com/rqlite/rqlite/blob/master/DOC/PERFORMANCE.md#in-memory-database-limits

**Comment by otoolep** [comment]
>Why does the memory still occupy 3.8GB after startup. After about half an hour, the memory recovered to 160MB

I *think* it's got to do with the way BoltDB works. It allocates a lot of memory at the start, as the Raft log is replayed. Eventually a snapshot kicks in, and removes a lot of entries from the Raft log (which causes BoltDB to release the memory). I think.

**Comment by otoolep** [comment]
From: https://github.com/boltdb/bolt#caveats--limitations

_Bolt uses a memory-mapped file so the underlying operating system handles the caching of the data. Typically, the OS will cache as much of the file as it can in memory and will release memory as needed to other processes. This means that Bolt can show very high memory usage when working with large databases. However, this is expected and the OS will release memory as needed._ 

Hashicorp uses BotltDB for its Raft storage.

**Comment by tiswong** [comment]
> From: https://github.com/boltdb/bolt#caveats--limitations
> 
> _Bolt uses a memory-mapped file so the underlying operating system handles the caching of the data. Typically, the OS will cache as much of the file as it can in memory and will release memory as needed to other processes. This means that Bolt can show very high memory usage when working with large databases. However, this is expected and the OS will release memory as needed._
> 
> Hashicorp uses BotltDB for its Raft storage.

OK, I see. Thanks. If raft runs for a long time, will it cause memory overflow of the virtual machine when restarting?

**Comment by otoolep** [comment]
> If raft runs for a long time, will it cause memory overflow of the virtual machine when restarting?

This is a difficult question to answer, and would require extensive testing. It may depend on a lot of factors.

**Comment by otoolep** [comment]
You can always increase the snapshot-and-truncation rate, which will keep the Raft log smaller. This may help prevent large usage of memory on startup. You do this by setting `-raft-snap` and `-raft-snap-int` to lower values than the default. You could try halving them to start.

**Comment by otoolep** [comment]
Fixed on master.
