### ISSUE TITLE
Support encryption of inter-node communication

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#93]
The TCP connections between each node -- the Raft connections -- should support encryption. This means support TLS encryption between nodes.

**Comment by mainframe** [comment]
+1 must have for production setups.

**Comment by otoolep** [comment]
@mainframe --- correct, a new node joining the cluster is not authenticated by default though you can user-level permissions to exercise some control over this process:

https://github.com/rqlite/rqlite/blob/master/doc/SECURITY.md#user-level-permissions

You can therefore pass a password to node when it starts up, which is required by other nodes before accepting the join request. There are many other ways to lock down your cluster too.

As for using serf, I don't have that much experience with it, and anyway one of the main points of rqlite is simplicity -- a single binary, that clusters easily. Requiring a second system like serf would be a major complication.

**Comment by otoolep** [comment]
Top of tree now supports node-to-node encryption, and it will be part of the 4.0 release.
