### ISSUE TITLE
Run rqlite through Jepsen testing

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#94]
It would be fun to do this.

https://github.com/aphyr/jepsen

**Comment by otoolep** [comment]
- http://www.refactorium.com/distributed_systems/Hacking-up-a-testing-environment-for-jepsen-and-influxdb/
- http://www.refactorium.com/distributed_systems/InfluxDB-and-Jepsen-Chapter-II-Where-is-influxdb-on-the-cap-scale/
- https://www.infoq.com/articles/jepsen
- https://github.com/abailly/jepsen-vagrant
- http://www.datastax.com/dev/blog/testing-apache-cassandra-with-jepsen

**Comment by otoolep** [comment]
As far as I know, by using STRONG read consistency, rqlite should be ready for jepsen testing.

cc @progamer71

**Comment by progamer71** [comment]
@otoolep
Sorry, I did not search before ask.
Anyway, thanks you.

**Comment by wildarch** [comment]
We have created Jepsen tests for rqlite as part of a university course: https://github.com/wildarch/jepsen.rqlite.

The tests included focus on strict serializability, linearizability and sequential consistency. Our tests found no violations of those properties, provided `STRONG` read consistency is enabled. 

I would not call them a complete test suite, and we are by no means experts in Jepsen or concurrency testing in general, but it seems like rqlite maintains consistency even for some tricky cases where network faults occur, which is pretty neat! :tada: :smile: 

@otoolep I am curious if you would be interested in including the tests into the rqlite testing setup? Alternatively I could propose to the maintainer of Jepsen that we merge them there, the repository appears to include tests for quite a few DBMS already.

**Comment by otoolep** [comment]
@wildarch -- this is great, thanks very much. I would be very interested in including this in the tests I run, primarily on CircleCI. How long do they take to run?

I read your blog post -- it's great. Do you have it posted anywhere else? I'd like to post on Hacker News etc.

**Comment by otoolep** [comment]
Made it to the front page of HN: https://news.ycombinator.com/item?id=31089363

**Comment by otoolep** [comment]
I think we can consider this issue closed -- thanks @wildarch
