### ISSUE TITLE
Does adding an additional node automatically pull data from the database leader

### ISSUE THREAD

**Issue by risharde** [rqlite/rqlite#955]
Hi, just beginning to use rqlite and I was wondering how additional nodes work. Is it that when you add a new node, the database will automatically be pushed to the new node or is there something more that needs to be configured for this to happen.

Sorry if it's a dumb question, just need to confirm that it does something like this for automatic scaling.

**Comment by otoolep** [comment]
When a node successfully joins (via the `-join` param) it automatically gets the full state from the cluster -- that is the point of joining. This can take a few seconds, depending on the size of the SQLite database.

**Comment by otoolep** [comment]
I'm assuming this answers your question.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#growing-a-cluster
