### ISSUE TITLE
spurious 500 errors on queries

### ISSUE THREAD

**Issue by nferch** [rqlite/rqlite#958]
Have been seeing some seemingly random 500 errors to the `/db/query` endpoint, e.g.

"""
curl -n 'https://10.69.44.157:4001/db/query?q=SELECT id from table'                                                                   
json: error calling MarshalJSON for type *http.DBResults: no DB results set
"""

I have seen this on both SELECT and CREATE TABLE statements.

Any ideas as to what might be causing this?

From what I can tell from the code, this response occurs when neither the `ExecuteResult` or the `QueryRows` are populated in the `DBResults` (https://github.com/rqlite/rqlite/blob/b9db6e4903b426a16e7a25af0d23e8396477ff2c/http/service.go#L118). Unfortunately this error state is preventing any potential error from the `Cluster.Execute()` call from being surfaced.

Perhaps a code change like https://gist.github.com/4cf758659710b1d626c0feb2222eb2bf would fix this. Would like to try this out on my own cluster but it seems a little less than trivial to build a Docker container with local modifications.

Can hack at this a bit more when I have a little more time, but curious if I'm missing anything obvious.

**Comment by otoolep** [comment]
Can I see the schema for the table?

**Comment by nferch** [comment]
here's the two statements that I'm positive have failed:

"""
                CREATE TABLE IF NOT EXISTS usps_mailpieces (
                    date TEXT NOT NULL,
                    mailpiece_id TEXT)
"""

"""
SELECT *
FROM usps_mailpieces
WHERE date="2022-01-10" AND mailpiece_id="399131667388%27"
"""

**Comment by otoolep** [comment]
No issues against a brand new node (that I can see):
```bash
~ $ curl -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
>     "CREATE TABLE IF NOT EXISTS usps_mailpieces (date TEXT NOT NULL,mailpiece_id TEXT)"
> ]'
{
    "results": [
        {
            "time": 0.000226702
        }
    ],
    "time": 0.017660336
}~ $ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=SELECT * FROM usps_mailpieces  WHERE date="2022-01-10" AND mailpiece_id="399131667388%27"'
{
    "results": [
        {
            "columns": [
                "date",
                "mailpiece_id"
            ],
            "types": [
                "text",
                "text"
            ],
            "time": 0.000113823
        }
    ],
    "time": 0.001481351
~ $ 
```
 I don't doubt it's happening, but clearly it's not simple. I'll look into exposing the error better, as you suggest.

**Comment by otoolep** [comment]
New Docker image available, 6.10.2, which should expose the underlying error. Let me know what you get.

**Comment by nferch** [comment]
Thanks, deployed this, will keep an eye out for any instances of the failure.

**Comment by otoolep** [comment]
Any more occurrences of this? I may close as not-reproducible, but at leas we have better error handling in there which will help you diagnose next time (if and when).

**Comment by nferch** [comment]
Nope, feel free to close. Thanks for the improved error handling!
